### ISSUE TITLE
Spock unit tests are not working after upgrading to Micronaut 4

### ISSUE THREAD

**Issue by munishchouhan** [micronaut-projects/micronaut-core#10051]
### Expected Behavior

We are trying to upgrade our application from Micronaut 3 to 4
I have followed this blog 
https://micronaut.io/2023/05/09/upgrade-to-micronaut-framework-4-0-0/
Now I am getting the below message when running unit tests

<img width="373" alt="Screenshot 2023-10-30 at 13 06 07" src="https://github.com/micronaut-projects/micronaut-core/assets/6575288/7c65ebf5-87e4-4f6e-8905-e8992f65c194">

Our application have Unit tests in groovy spock

### Actual Behaviour

Unit tests should run

### Steps To Reproduce

1. you can check my PR https://github.com/seqeralabs/wave/pull/318

### Environment Information

- Mac OS 14.0
- Java : OpenJDK 64-Bit Server VM Corretto-17.0.8.7.1 (build 17.0.8+7-LTS, mixed mode, sharing)

### Example Application

https://github.com/seqeralabs/wave

### Version

4.0.1

**Comment by merscwog** [comment]
@munishchouhan I checked out your 314-update-to-micronaut-41 branch, and the reason is that Spock 2.x generates JUnit5 tests.  The default test runner within Gradle is JUnit 4-based, and it will not recognize newer JUnit 5 tests.

Adjust your test {} block in your build.gradle to contain useJUnitPlatform() to tell Gradle to use the JUnit 5 test runner:
```groovy
test {
    useJUnitPlatform()
}
```

Also, while examining the dependencies of the project, it seems that the version of io.seqera:lib-mail referenced uses older versions of groovy and micronaut -- it may be that you had a locally built version that already upgraded those as well, but I had to configure the build.gradle file to adjust the transitive dependencies to make everything consistent:

```groovy
dependencies {
    // due to things pulled in from io.seqera:lib-mail
    modules {
        module('org.codehaus.groovy:groovy') {
            replacedBy('org.apache.groovy:groovy', 'new org since groovy 4.x')
        }
        module('org.codehaus.groovy:groovy-templates') {
            replacedBy('org.apache.groovy:groovy-templates', 'new org since groovy 4.x')
        }
        module('org.codehaus.groovy:groovy-nio') {
            replacedBy('org.apache.groovy:groovy-nio', 'new org since groovy 4.x')
        }
        module('io.micronaut:micronaut-bom') {
            replacedBy('io.micronaut:micronaut-core-bom', 'new org and module name since 4.x')
        }
    }
}
```
