### ISSUE TITLE
Broken Link To DefaultByteBufAllocatorConfiguration

### ISSUE THREAD

**Issue by jeffscottbrown** [micronaut-projects/micronaut-core#10202]
### Issue description

At [docs.micronaut.io/4.2.0/guide/configurationreference.html](https://docs.micronaut.io/4.2.0/guide/configurationreference.html) the DefaultByteBufAllocatorConfiguration link at the top of the page is 404'ing.  The same is true for other versions of the docs.

**Comment by wetted** [comment]
@melix @sdelamo thoughts?

It appears the problem is that `DefaultByteBufAllocatorConfiguration` is an `@Internal` class, and I believe we don't generate javadocs for classes marked with that annotation.

We need to do one of:

1. generate the javadoc if we plan to publish the configuration
2. don't create the javadoc link for it on the configuration page if the class is @internal`
3. don't publish the configuration reference at all if the class is `@Internal`

For 1 or 2, maybe add an attribute to `@Internal` to help control docs generation (or is that too much mixing concerns...and I don't know how the plugin works yet anyway)?

I'm not sure what the right choice is, but whatever it is I'm pretty sure that requires a change to the docs generator for `micronaut-build`

**Comment by sdelamo** [comment]
I tried to remove the `@Internal` annotation but it is not enough.

**Comment by wetted** [comment]
> I tried to remove the `@Internal` annotation but it is not enough.

I figured it out. There are four classes and interfaces in the `io.micronaut.buffer.netty` package. The docs task generates javadocs for a non-internal interface and an internal factory class, but not for the other two classes (both internal).

The generated docs are for the public types. The non-generated are for the package scope types.

We probably shouldn't be creating javadocs links to for non-public types since generated javadocs don't exist.

**Comment by wetted** [comment]
I confirmed that changing`DefaultByteBufAllocatorConfiguration` to `public` visibility solves the problem. I also checked a handful of other links on the configuration refence page and didn't find others. I think we should just make the class public. It's already final.
