### ISSUE TITLE
StringIndexOutOfBoundsException on startup since 4.2.0

### ISSUE THREAD

**Issue by mattlong-finocomp** [micronaut-projects/micronaut-core#10209]
### Expected Behavior

My micronaut.server.context-path is set to a path of /app in application.properties.
In a test with rebuildContext=true I override this to an empty string in a Property annotation to verify the behaviour of an interceptor in different scenarios (not included or necessary in example application).
The application should start up without issue as if the context path wasn't set.
This works in Micronaut 4.1.6 and has been broken since 4.2.0.

If there was a method to unset a configuration property for a single test that's what i'd be looking to use, this was the closest thing I could come up with.

### Actual Behaviour

The application fails to start due to an StringIndexOutOfBoundsException in ConfigurableUriNamingStrategy.
This class is unchanged, so something else has changed that actually executes ConfigurableUriNamingStrategy.
This class could be more robust in handling null / empty context-paths.

### Steps To Reproduce

In linked example application:
Run MicronautContextPathErrorSpec - it will pass as micronautVersion in gradle.properties is set to 4.1.6
Change the version to 4.2.0 or 4.2.1 and rerun the spec.
The test will now fail.

### Environment Information

OS: Pop!OS 22.04
Java: 17

### Example Application

https://github.com/mattlong-finocomp/micronaut-context-path-error

### Version

4.2.0

**Comment by jeremyg484** [comment]
There are multiple issues at play here...

First, the reason your test fails with 4.2 and not 4.1 is because there was a bug in Micronaut Test that has been resolved in 4.2 with https://github.com/micronaut-projects/micronaut-test/pull/873, wherein the first invocation of a spec method annotated with`@Property` was not causing the `ApplicationContext` to refresh - thus `ConfigurableUriNamingStrategy` ends up still being present with the context path still set to "/app".

Second, we should probably fix `ConfigurableUriNamingStrategy` to be more forgiving and properly handle an empty string.
