### ISSUE TITLE
Build with GRPC KSP processing fails 

### ISSUE THREAD

**Issue by erkieh** [micronaut-projects/micronaut-core#10647]
### Expected Behavior

Build to succeed or give a good error message

### Actual Behaviour

> Task :kspKotlin FAILED
e: [ksp] Originating element: meAsParent
e: [ksp] Index 0 out of bounds for length 0
e: [ksp] Originating element: meAsParent
e: [ksp] Index 0 out of bounds for length 0
e: Error occurred in KSP, check log for detail

### Steps To Reproduce

gradle build

If I remove 
ksp("io.micronaut.validation:micronaut-validation-processor")
from build.gradle.kts it succeeds

### Environment Information

windows java 21

### Example Application

https://github.com/erkieh/grpc-ksp-fail

### Version

4.3.7

**Comment by timyates** [comment]
Confirmed as failing...

`meAsParent` seems to come [from the protocol buffers library](https://github.com/protocolbuffers/protobuf/blob/704d0454ddc58da683e8cec22896ff3498089549/java/core/src/main/java/com/google/protobuf/GeneratedMessage.java#L473)...  Trying to work out what is going on...

**Comment by timyates** [comment]
So it seems to be that Ksp is processing `build/generated/source/proto/main/java/com/example/DemoReply.java` and then is failing...  I'm not sure Ksp processing Java code makes sense...

**Comment by timyates** [comment]
The issue is caused here in our Ksp processing

https://github.com/micronaut-projects/micronaut-core/blob/8aa812f8ba38a791afab952a4d5769effc90c825/inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/AbstractKotlinElement.kt#L292-L296

we are expecting `typeParameters` and `type.arguments` to have the same size, which they seemingly do not in this case...

Investigations continue

**Comment by timyates** [comment]
@erkieh Think https://github.com/micronaut-projects/micronaut-core/pull/10811 fixes it 🤞 

Thanks for reporting this!

**Comment by erkieh** [comment]
Thanks for fixing!
