### ISSUE TITLE
Latest version in Maven Repos is 4.3.7

### ISSUE THREAD

**Issue by mdeso** [micronaut-projects/micronaut-core#10675]
### Issue description

While upgrading to Micronaut 4 I just noticed that the latest version of Micronaut platform in Maven Central is 4.3.7:
https://mvnrepository.com/artifact/io.micronaut.platform/micronaut-platform

This causes any builds with Micronaut >= 4.3.8 to fail (with the Micronaut Gradle plugin 4.3.5).

**Comment by rbhambhra** [comment]
I have noticed that there is lag before micronaut-platform is updated.
Its usually less than a month so waiting is not a problem for me
But am curious why there is a delay
Thanks

**Comment by sgammon** [comment]
Micronaut Core's version is just the version for Micronaut Core. Core stays ahead of all the other modules, because they build against Core

My suspicion (I am not a member of the Micronaut team) is that the Micronaut Platform version is published every so often, when a full tree of versions can safely be frozen together; that would include the Core version amongst them, but it would make the Platform version distinctly separate

Remember that there are Gradle plugins to account for as well. These typically follow the Platform version, not the Core version, so to update everything together, the Platform version lags behind Core a bit.

That is just my guess and experience as a user, and it can be quite confusing to know when a platform version release has occurred by just following Core. I usually check the [platform catalog plugin](https://micronaut-projects.github.io/micronaut-gradle-plugin/latest/#sec:micronaut-platform-catalog-plugin) as my main `micronautVersion`. Note that if you use the platform catalog plugin, you can also [override the version of core you use](https://micronaut-projects.github.io/micronaut-gradle-plugin/latest/#sec:overriding-version), or for any other dependency.

So it is possible to use Micronaut Platform v4.3.7 with Micronaut Core latest, if you _really_ need to, and this is a case where I'd do that (build errors)

**Comment by yawkat** [comment]
Yes, as @sgammon says, the micronaut-platform version ("Micronaut version") does not match the micronaut-core version since 4.x. micronaut-platform 4.3.7 actually uses micronaut-core 4.3.12. If you need a newer version of micronaut-core than is in the latest micronaut-platform, you can update those dependencies manually.

**Comment by mdeso** [comment]
The concept makes sense but is it documented somewhere? Neither in the descriptions/docs of micronaut-core nor micronaut-platform I found an explanation of this. There is only a short section about the BOM in the upgrade guide but that is not very helpful.

**Comment by sdelamo** [comment]
@mdeso see: https://github.com/micronaut-projects/micronaut-platform/discussions/200
