### ISSUE TITLE
[AOP]: ConstructorInterceptor is not working

### ISSUE THREAD

**Issue by HristoP96** [micronaut-projects/micronaut-core#11044]
### Expected Behavior

A class implementing the ConstructorInterceptor should be able to intercept the respective object's contrusctor pre/post its invoke, based on the InterceptorBinding of the advice that the interceptor is listening to throught the InterceptorBean.

### Actual Behaviour

A class implementing the ConstructorInterceptor is not intercepting consctructors on/post/pre object creation.

### Steps To Reproduce

1. Clonse this repo https://github.com/HristoP96/aop-demo-1
2. Run the project
3. Watch the console

**Expected** behavior:
 After a Product contsructor is invoked, the interceptor should print _"Product created"_ and afterwards the program should print _Is my product favorite false_
 
 **Actual behavior**:
 The program only prints _Is my product favorite null_

### Environment Information

- Windows 11
- JDK 17

### Example Application

https://github.com/HristoP96/aop-demo-1

### Version

4.4.2

**Comment by nilols** [comment]
I think the problem here is that `new Product()` in the `ApplicationEventListener` circumvent everything, you probably need a `@Factory` or something that can create `Product` beans for the interceptor to work (so that you create the bean through micronaut)

I did a quick test by changing your example a bit
```
@Singleton
public class OnStart implements ApplicationEventListener<StartupEvent> {
    @Inject
    ProductService productService;

    @Override
    public void onApplicationEvent(StartupEvent event) {
        productService.addProduct(event.getSource().createBean(Product.class)); // <-- here
        System.out.printf("Is my product favorite %s%n", productService.getProduct(0).getFavorite());
    }
}
```

```
@Singleton
@InterceptorBean(FavouriteSetter.class)
public class FavouriteInterceptor implements ConstructorInterceptor<Product> {

    @Override
    public @NonNull Product intercept(@NonNull ConstructorInvocationContext<Product> context) {
        Product target = context.proceed(); // <--- and here 
        System.out.println("Product created");
        try {
            Field field = target.getClass().getDeclaredField("favorite");
            field.setAccessible(true);
            field.set(target, false);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            e.printStackTrace();
        }
        return target;
    }
}
```

and my output is 
```
Product created
Is my product favorite false
```

**Comment by graemerocher** [comment]
constructor interception cannot work when you directly use `new` as described in the previous comment

**Comment by rsalbergaria** [comment]
Hello,

I am trying to use the solution mentioned. However, I am encountering an issue where instantiating a Product bean using Named does not work as expected, and the interceptor is not being triggered.

Here is the code I am using: 

`
@Singleton
public class ProductServiceApplication {

    private final ProductService productService;
    private final Product product;

    public ProductServiceApplication(ProductService productService, @Named("teste") Product product) {
        this.productService = productService;
        this.product = product;
    }

    public void addProduct() {
        productService.addProduct(product);
    }

    public Product getProduct(int index) {
        return productService.getProduct(index);
    }
}

`

Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [com.example.stuff.Product] exists for the given qualifier: Named('teste').

When I attempt to instantiate a Product bean using the Named annotation, the dependency injection fails with the error above. Additionally, it seems that using Named prevents the interceptor from being triggered.

Question: Is it possible to use Named in this context and still have the interceptor work as expected? If so, could you provide guidance on how to achieve this?

**Comment by rsalbergaria** [comment]
@HristoP96  @graemerocher @nilols
