### ISSUE TITLE
Hibernate Validator Annotation Processor Usage?

### ISSUE THREAD

**Issue by hc-codersatlas** [micronaut-projects/micronaut-core#1119]
Can the Hibernate Validator Annotation Processor be used or is this already provided by Micronaut? Sorry this wasn't mentioned in the docs. To be clear, referring to: https://docs.jboss.org/hibernate/validator/6.0/reference/en-US/html_single/#validator-annotation-processor

It's used for some checks at compile time.

Thanks!

**Comment by graemerocher** [comment]
Should be possible, just a matter of configuration the annotation processor

**Comment by hc-codersatlas** [comment]
Thanks, maybe good to update the documentation. My issue was same as #991. Didn't know the other annotation processors have to be placed before the Micronaut ones. All good.

**Comment by jameskleeh** [comment]
Closing this as the other issue was resolved. @hc-codersatlas If you think the documentation can be improved here please submit a PR, however with the recent change I'm not sure any issues should arise unless the other annotation processor produces classes that Micronaut should also process or if the other annotation processor modifies the byte code of a class that Micronaut should process. In both of those cases the processor should be executed first, however there is no way to guarantee that since ordering is not supported afaik.
