### ISSUE TITLE
Properties from environment are ignored if already defined

### ISSUE THREAD

**Issue by sschnabe** [micronaut-projects/micronaut-core#1191]
### Steps to Reproduce

1. Create [application](https://github.com/sschnabe/micronaut-properties/blob/master/src/main/java/io/micronaut/issue/Application.java#L13) that uses property `my-stuff.my-property`
2. Add default value to [application.yaml](https://github.com/sschnabe/micronaut-properties/blob/master/src/main/resources/application.yaml) inside the final jar
3. Run application with Environment `MY_STUFF_MY_PROPERTY=value-from-env`

### Expected Behaviour

Application logs value from environment:

```
~/code/micronaut-properties$ export MY_STUFF_MY_PROPERTY=value-from-env
~/code/micronaut-properties$ mvn clean package && java -jar target/micronaut-properties-0.0.1-SNAPSHOT.jar 
...
14:17:04.826 main INFO io.micronaut.issue.Application Value: value-from-jar
14:17:04.840 main INFO io.micronaut.runtime.Micronaut No embedded container found. Running as CLI application
```

If i remove the default value it works:

```
~/code/micronaut-properties$ export MY_STUFF_MY_PROPERTY=value-from-env
~/code/micronaut-properties$ rm src/main/resources/application.yaml
~/code/micronaut-properties$ mvn clean package && java -jar target/micronaut-properties-0.0.1-SNAPSHOT.jar 
...
14:17:04.826 main INFO io.micronaut.issue.Application Value: value-from-env
14:17:04.840 main INFO io.micronaut.runtime.Micronaut No embedded container found. Running as CLI application
```

### Actual Behaviour

Application logs value from jar.

### Environment Information
- **Operating System**: Ubuntu
- **Micronaut Version:** 1.0.4
- **JDK Version:** openjdk 11.0.1 2018-10-16

### Example Application
see [micronaut-properties](https://github.com/sschnabe/micronaut-properties)

**Comment by graemerocher** [comment]
Currently you are referring to `my-stuff.my-property` if you change it to `my-stuff-my-property` it works as expected. We have not implemented the former because it would increase memory consumption to store every variation of dots and hyphens

**Comment by jameskleeh** [comment]
@graemerocher The documentation shows `my-stuff.my-property` as an example. Perhaps that table should be more clear on what precise combinations of `.-` are created. https://docs.micronaut.io/latest/guide/index.html#propertySource

**Comment by ilopmar** [comment]
I think it's not a matter of documentation. The issue is that not all the combinations showed in the documentation are generated, only the combinations separated by `.` but not with `-`. So, defining the environment variable `MY_APP_MY_STUFF` only the combinations 2, 3 and 4 are generated:
![image](https://user-images.githubusercontent.com/559192/54278263-2df3b980-4592-11e9-97f3-4710d4dea05d.png)

That's why when looking in the application for `my-app.my-stuff` the original value is found and the value defined in the environment variable is not used.
I think we have two options to fix this:
- When generating the different property names for the environment variable, also generate the combinations with `-` as mentioned in the documentation: https://github.com/micronaut-projects/micronaut-core/blob/afc3fb377fea37f942c1a251be19b58f9f989b22/inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java#L628
- When looking for the value make the "normalized" value (the one with all "dots") takes preference over the rest.

**Comment by graemerocher** [comment]
Option 1 is the way to go
