### ISSUE TITLE
Enhance the CLI to allow a profile to define the mainClassName

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#1207]
To generate a "function" project with Graal support we do:
```
mn create-function mn-graal-function --features=graal-native-image
```

The issue is that the class used as an entry point for Graal is set in both `build-native-image.sh` script and `Dockerfile` to `-H:Class=mn.graal.function.Application`. To be able to run the function in Graal it needs to be `-H:Class=io.micronaut.function.executor.FunctionApplication`.

With this enhancement every profile or feature would be able to define the `mainClassName` used.

**Comment by benrhine** [comment]
Once the following prs are both merged you will be able to specify the a custom main as follows
`mn create-app my-app-cust -m com.io.MyCustomApplication` or
`mn create-function cust-graal-function -f graal-native-image -m com.io.Custom`

when setting the custom `mainClassName` the full package + name must be specified as we cant assume its in the default package

These prs must be done together or it will break code generation
https://github.com/micronaut-projects/micronaut-profiles/pull/207
https://github.com/micronaut-projects/micronaut-core/pull/2437

**Comment by benrhine** [comment]
@ilopmar if you get a moment take a look at the prs - I have updated as per our conversation such that the `native-image.properties` file is updated as you have mentioned above. I have made the place that is set in the `AbstractCreateCommand` so if we need to make updates around this in the future it should be pretty easy. Are there any cases it shouldnt be the above? If there are those are not currently handled.

@jameskleeh while working on this I misunderstood Ivans intent and before I spoke with him I added a feature where you can custom specify the general `mainClassName` for apps and functions. I'm not sure what the use case would be but could be useful, do you think we should keep it? Or should I close these prs and create a separate one with just the part Ivan wanted?

**Comment by benrhine** [comment]
ok trying again @ilopmar please try out the following prs. https://github.com/micronaut-projects/micronaut-core/pull/2458 and https://github.com/micronaut-projects/micronaut-profiles/pull/215. Give everything a good once through (command-wise) as going this updated route of being able to specify the `mainClassName` extends across profiles and features.

As stated in the prs if a `mainClassName` is specified in a feature it will overrid the value specified in the profile. So in the case of generating a function with a native image it will choose the `mainClassName` set on the feature instead of the general function profile.
