### ISSUE TITLE
Inconsistent and confusing errors during injection of bean X when unrelated bean Y can't resolve a property.

### ISSUE THREAD

**Issue by KrzysztofKowalczyk** [micronaut-projects/micronaut-core#1246]
Having one bean depending on property "a" and one bean with scheduled task depending on property "b", if property "a" is defined but "b" is missing, the first bean cannot be injected in most cases.

It fails with very confusing errors complaining about property "a" not being defined, when it clearly is.

If one use the property in Value annotation and have http-client on classpath at the same time the bean would actually inject, but the value of the property will be empty 😱 

Workaround:
- use Require annotation on the scheduled bean to stop it from running

### Steps to Reproduce

See tests in example application.

### Expected Behaviour

When we inject a bean that has a property and the property is defined, injection should work. 
Additionally the injected bean should have properties properly initialised.

There is argument to be have what the failure of eager beans should cause:
- no exception during injection of unrelated  bean
- exception during startup
- exception during injection of the other bean but with real reason

### Actual Behaviour

Currently even though a property "x" is provided, during injection bean that is requiring "x", complains about it not being available and:
- fails with NoSuchBeanException in case of using it in Property annotation
- fails with ConfigurationException in case of using it in Client annotation
- fails with DependencyInjectionException in case of using it in Value annotation and not having http-client dependency on the classpath
- injects beans but has null value for the property in case of using it in Value annotation and having http-client on the classpath 🤔 

### Environment Information

- **Micronaut Version:** 1.0.4

### Example Application

Two projects with one specification each, example stacktraces provided there:
https://github.com/KrzysztofKowalczyk/micronaut-problems/blob/master/wrong-property-reported/src/test/groovy/micronaut/problems/ConfusingErrorSpec.groovy
https://github.com/KrzysztofKowalczyk/micronaut-problems/blob/master/wrong-property-reported2/src/test/groovy/micronaut/problems/ConfusingErrorSpec2.groovy

**Comment by KrzysztofKowalczyk** [comment]
There also seem to be a race condition, for instance there are 2 test cases "null value" and "null value2". The only difference between them is order in the spec (first and last) and thread sleep in the first one.
Without the thread sleep the first one sometimes passes, but mostly fails.
With the thread sleep I have not seen it succeed. 
The second almost always succeed if all tests are run, but it can fail, especially if run separately from idea.

**Comment by jameskleeh** [comment]
In the `wrong-property-reported` module, the test `ConfusingErrorSpec#null value` is failing because you are not providing a property for the scheduled method. That bean then fails to be created and then shuts down the context. The "race condition" you may have seen would have sometimes caused the property to be retrieved before the shutdown completed.

In the `wrong-property-reported` module, the test `ConfusingErrorSpec#no such bean reported` is failing because having only `@Property` on a field does not cause a bean to be created for the class. Perhaps it should as `@Value` does.

In the `wrong-property-reported` module, the test `ConfusingErrorSpec#wrong property reported missing - ConfigurationException` is invalid. There is nothing in place that would cause the value of the property to be returned.

In the `wrong-property-reported2` module, the test `ConfusingErrorSpec2#wrong property reported - DependencyInjectionException` fails for the exact same reason as `ConfusingErrorSpec#null value`.

The following diff causes the tests to pass https://gist.github.com/jameskleeh/9b3cc3686200c4037223e3599a708135

Summary:
1) We should consider creating beans if only `@Property` is annotated in the class, similar to `@Value`.
2) We should consider throwing an error if the context is attempted to be used after it has been shut down

**Comment by KrzysztofKowalczyk** [comment]
Ah, yes copy and paste bug in `ConfusingErrorSpec#wrong property reported missing - ConfigurationException`, the assertion was not the problem, the wrong message in ConfigurationException was. Updated the examples. also merged the "fixes" and commented them out to still fail.

The broken scheduled bean is provided on purpose to cause a context shutdown with a known reason.
Thus those test cases show that last reported exceptions does not inform me properly of the reason they failed. The actual reason is reported in the log earlier. 
I think I would like the reason of context shutdown to be rethrown after the shutdown when I try to use it. Or explicitly tell that the context is shutting/shut down and one need to check earlier exception.

Also I would expect `ConfusingErrorSpec#null value` to fail with exception not with wrongly initialised bean as it does.
Finally I still don't understand why removing http-client from the classpath for "null value" test change the behaviour of this test to throw exception as in `ConfusingErrorSpec2`. It is the same test, but in one case it returns null in another it throws exception.

It did not occur to me I could use `@Parallel(shutdownOnError = false)`  
https://github.com/micronaut-projects/micronaut-core/blob/1.0.x/src/main/docs/guide/ioc/scopes/builtInScopes.adoc might need a mention about that.

**Comment by jameskleeh** [comment]
I implemented the suggestion about `@Property`, however the exception for the context being closed will have to wait until a later version. I've filed https://github.com/micronaut-projects/micronaut-core/issues/1421 to track that issue.
