### ISSUE TITLE
Unexpected HTTP Routing Logic

### ISSUE THREAD

**Issue by emazzotta** [micronaut-projects/micronaut-core#1303]
### Steps to Reproduce

1. Checkout this sample repository https://github.com/emazzotta/micronaut-route-matching
2. Start the application
3. Navigate to: http://localhost:8080/v1/input/my_custom_input.csv

### Expected Behaviour

I expect the route annotated with `@Get(uri = "/{id}.csv")` to be matched and `@Get(uri = "/{id}")` to be ignored, since `@Get(uri = "/{id}.csv")` is a "closer" match.

### Actual Behaviour

I get an error message as a response:
```
"message": "More than 1 route matched the incoming request. 
The following routes matched /v1/input/my_custom_input.csv: 
GET - /v1/input/my_custom_input.csv, 
GET - /v1/input/my_custom_input.csv"
```

Is this expected or a genuine issue?

### Environment Information

- **Operating System**: macOS Mojave 10.14.3
- **Micronaut Version:** 1.0.1
- **JDK Version:** openjdk version "11" 2018-09-25

**Comment by jameskleeh** [comment]
Just FYI `@Get(uri = "/{id}.csv")` would be chosen over `@Get(uri = "/{id}.{format}")`

**Comment by emazzotta** [comment]
@jameskleeh Thanks for the hint, unfortunately that would not solve my use case.

I'd like a "non-extension"-route to be the "default" route:
`@Get(uri = "/{id}")` 

But if the route ends in `.csv` or `.pdf` I'd like the route with the corresponding annotation to be matched over the "default" route: 
`@Get(uri = "/{id}.csv")`
`@Get(uri = "/{id}.pdf")`

**Comment by jameskleeh** [comment]
@emazzotta You can make it so the default route won't get executed if there is an extension

`@Get(uri = "/{id:((?!\\.).)*}")`

**Comment by jameskleeh** [comment]
Unfortunately it would require some non trivial API changes in order to be able to differentiate the route matches and make a decision on which one should be used. I think we will need to shelve this until 2.0

**Comment by saw303** [comment]
@jameskleeh is this really a breaking change that has to wait until Micronaut 2.0? Let me explain what @emazzotta and I are currently trying to workaround.

Given the following REST controller that allows you to read a `session` in JSON or PDF representation.

```
@Controller("/v1/sessions")
@Validated
public class SessionsResource {
  
  @Get(
      uri = "/{id}"
  )
  @Produces("application/json")
  public SessionsGetResourceModel getEntity(String id) {
    return new SessionsGetResourceModel(id);
  }

  @Produces("application/pdf")
  @Get(
      uri = "/{id}.pdf"
  )
  public HttpResponse getEntityPdf(String id) {
    return HttpResponse.noContent();
  }
}
```

and the two HTTP requests:

- Query the JSON `session`

```
GET http://localhost/v1/sessions/AA-BB-CC
Accept: application/json
```

- Download the `session` as a PDF.

```
GET http://localhost/v1/sessions/AA-BB-CC.pdf
Accept: application/pdf
```

**This is what Micronaut 1.1.RC2 does:**

1. It ask the router to find UriRouteMatch for the current request `io.micronaut.web.router.Router#find(io.micronaut.http.HttpRequest<?>)`
2. For my request examples above it will find two `UriRouteMatch`
- GET /v1/sessions/{id}.pdf -> $SessionsResourceDefinition$Intercepted#HttpResponse getEntityPdf(String id) (application/json )
- GET /v1/sessions/{id} -> $SessionsResourceDefinition$Intercepted#SessionsGetResourceModel getEntity(String id) (application/json )
3. Size the result contains more than one match Micronaut decides to fail.

**This is what would help Micronaut to decide the correct match:**

Since the controller methods `getEntityPdf` and `getEntity` both declare different media types by their `@Produces`.  The following image show the to `UriRouteMatch` instances that could easily filtered by what they produce and by what the client is requesting for (Accept Header).

<img width="674" alt="cbc-osl____dev_adcubum_swica_cbc-osl__-____gradle_caches_modules-2_files-2_1_io_micronaut_micronaut-http-server-netty_1_1_0_RC2_3ce1785fbcc3c336f488ac08de1ed211e56ae46a_micronaut-http-server-netty-1_1_0_RC2-sources_jar__io_micronaut_http_se" src="https://user-images.githubusercontent.com/71073/55387138-2ab87180-5531-11e9-8772-551947b9017a.png">

Regarding 2.0 what change do you have in mind? Can we contribute something? This is currently really painful when it comes to implementing REST API with multiple representations.
