### ISSUE TITLE
Breaking change with @Configuration packages and requirements in 1.1 M2

### ISSUE THREAD

**Issue by marceloverdijk** [micronaut-projects/micronaut-core#1306]
As discussed on gitter it seems there is a breaking change with @Configuration packages and requirements due to https://github.com/micronaut-projects/micronaut-core/commit/d9c69f98c782d3c45eb5af9f25f1ba6f12d867b4

This for example causes an issue with the `micronaut-graphql` module which has a `package-info.java` like:

```
@Configuration
@RequiresGraphQL
package io.micronaut.configuration.graphql;

import io.micronaut.context.annotation.Configuration;
```

But in this case the `@Controller` beans in this package are not created.

**Comment by graemerocher** [comment]
The cause of the breaking change is that `@Requires(beans=Foo.class)` no longer works when applied to a `@Configuration` package because the configurations are loaded before the beans, thus when the condition runs it sees an empty context with no beans in it. Prior to the change the beans where loaded already.

**Comment by marceloverdijk** [comment]
I assume keeping @Requires on package level is still recommended approach?

**Comment by marceloverdijk** [comment]
Thx, using the build-snapshot it works for me again.
