### ISSUE TITLE
Auth handling incorrectly reports 401 for invalid request but with correct credentials

### ISSUE THREAD

**Issue by markjfisher** [micronaut-projects/micronaut-core#1595]
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

There appears to be an issue when sending an invalid request (e.g. "...?someQuery=^") but with valid authentication credentials.

When no security is enabled, the request correctly gets handled by an ExceptionHandler that picks up the invalid request.

When security is enabled the response is 401, despite having correct credentials. It should pass the auth check, then fail at the ExceptionHandler and return a 400, but doesn't get that far.

Full details in the linked github repo.

### Steps to Reproduce

1. Add security to controller
2. Have an ExceptionHandler that handles bad URIs
3. Send an authenticated request to controller that has an invalid request

### Expected Behaviour

Should get 400 thrown by the Exception Handler, as the request was authorised, but the request was invalid.

### Actual Behaviour

Get 401 unauthorized

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 1.1.0
- **JDK Version:** JDK11

### Example Application

https://github.com/markjfisher/mn-auth-issue

**Comment by jameskleeh** [comment]
The issue is that the once per request filters are getting executed for the error request. Typically once per request filters get executed first when the server receives the request, then not executed again for error conditions. In this case the server is never receiving the request as normal and error handling is kicked off first. This is causing the once per request filter to be executed for the error request which is unexpected.
