### ISSUE TITLE
Graal: @Introspected doesn't work for inner classes

### ISSUE THREAD

**Issue by knyttl** [micronaut-projects/micronaut-core#1620]
### Steps to Reproduce

1. This happens for project compiled with Graal. There are no issues running directly on JDK.
2. Implement a @Introspected data class A and @Introspected data class inside some other class. Eg.:

```
@Controller
class MyController {
    @Get("/")
    fun test(): DataClassX {
       return DataClass("a")
    } 

   // inside a class
   @Introspected
   data class DataClassA(val string: String)
}

// outside of a class
@Introspected
data class DataClassB(val string: String)
```

3. If you try to return `DataClassB`, it will work correctly as the @Introspected annotation works correctly outside of a class. If you try to return `DataClassA`, it will always return and empty object.

### Expected Behaviour

@Introspected should work on all classes.

### Actual Behaviour

@Introspected doesn't work on inner classes.

### Environment Information

- **Operating System**: Any
- **Micronaut Version:** 1.1.0 SNAPSHOT
- **JDK Version:** JDK8

**Comment by jameskleeh** [comment]
This is supported in version 2

**Comment by binoysankar** [comment]
Hi,

I am facing the same issue with Micronaut 2.2.1 version. I use protoc compiler to convert proto files to java objects.
By default it creates inner classes in one single .java file. eg: try the below proto definition (for testing purpose).

**syntax = "proto3";

option java_multiple_files = true;

message Country {
  CountryNames countrynames = 1;
}

message CountryNames
{
  message Address {
    message TemporaryAddress {
      string temporaryAddress = 1;
    }
    string address = 1;
    TemporaryAddress temporaryAddress = 2;
  }
  Address address = 1;
}**

I added an option to split the java classes into multiple ones by using "option java_multiple_files = true;"
But even though you can see "TemporaryAddress" is an inner class of Address and CountryName.
I created an application which accepts json string which validated against the proto definition and I get an exception stating "missing method getTemporaryAddress". I have annotated with @Introspected which doesn't work for native-image.

Snippet of code for validating the json.
`final Country.Builder builder = Country.newBuilder();
 JsonFormat.parser().merge(jsonString, builder);` 

this issue is only when I convert it to the native-image

**Comment by jameskleeh** [comment]
@binoysankar That seems unrelated to this issue. Please file an issue in micronaut-grpc

**Comment by binoysankar** [comment]
> @binoysankar That seems unrelated to this issue. Please file an issue in micronaut-grpc

Sure I will file and issue in grpc. Actually I am not using grpc server or its full functionality. I have the normal micronaut Application which validates a json string with proto definition and saves into db (if validation is successful). 

I managed to resolve the issue having a workaround by splitting the .proto files to have maximum one inner class and import the split protos and rewire it together(issue is if we have more than 2 inner classes it doesn't Introspect classes below 2nd nested class, seems weird or my observation is wrong).
