### ISSUE TITLE
Improve @Infrastructure bean documentation

### ISSUE THREAD

**Issue by DBarthe** [micronaut-projects/micronaut-core#1785]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x]  Full description of the issue provided (see below)

### Steps to Reproduce
1. Create a bean with `@Infrastructure` annotation
2. Add a method listener method with `@EventListener` and `@Async`
3. Publish the corresponding event from anywhere

### Expected Behaviour

The already instantiated `@Infrastructure` bean should receive the event. 

### Actual Behaviour

A new `@Infrastructure` bean is instantiated and receive the event.

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 1.1.2
- **JDK Version:** Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

### Example Application 

For instance :
```java
@Infrastructure
public class MyService {

    public MyService() {
       // constructor ...
    }

    @EventListener
    @Async
    public void onPreflightCompleted(PreflightCompletedEvent event) {
        // start things ...
    }
}
```

And from somewhere else:
```java
eventPublisher.publishEvent(new PreflightCompletedEvent());
```

This might be related to #1345 and I guess it would be the same with `@Context` beans.

**Comment by graemerocher** [comment]
`@Infrastructure` beans don't specify a scope. You would need to add `@Singleton` to it otherwise a new bean will be created each time it is retrieved

**Comment by DBarthe** [comment]
Thanks @graemerocher  for clarification, I was confused by the doc which states "Infrastructure is a @Context scope..."

**Comment by graemerocher** [comment]
Seems worthy of a doc fix

**Comment by binkley** [comment]
Question on this:
```
@Context
@Infrastructure
class DatabaseSetup(dataSource: DataSource) { /* ... */ }
```
Based on the existing documentation, I had the impression that `@Infrastructure` was of context scope.  (Clearly from reading this issue, that is not the case.)

Since `@Context` is a meta-annotation, would it make sense for Micronaut to add `@Context` onto the declaration of the `@Infrastructure` annotation?

**Comment by graemerocher** [comment]
Currently `@Infrastructure` doesn't define any concrete scope. So it can be a singleton, prototype or whatever. The actual meaning of this annotation is for defining beans that cannot be replaced using `@Replaces`. The documentation is currently mistaken. 

We cannot change this behaviour now because that would be a breaking change and we currently follow semantic versioning and try not to break API compatibility and behaviour in 1.x release. Having said that I am not sure changing the behaviour is even desirable.
