### ISSUE TITLE
Unable to use environment variable with json syntax of CMD in Docker

### ISSUE THREAD

**Issue by ashishkujoy** [micronaut-projects/micronaut-core#1820]
Unable to use the JSON syntax of specifying CMD or ENTRYPOINT with micronaut
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. create a sample app using CLI 
    mn create-app org.learning.document-service --features=kotlin,kafka
2. change CMD of docker file to json syntax 
```dockerfile
     CMD ["java" ,"-Dmicronaut.environments=${PROFILE}", "-XX:+UnlockExperimentalVMOptions" ,"-XX:+UseCGroupMemoryLimitForHeap" ,"-Dcom.sun.management.jmxremote" ,"-noverify ${JAVA_OPTS}" ,"-jar", "document-service.jar"]
```
3. build image
```sh
 docker image build -t document-service .
```
4. run container
```sh
docker container run -e PROFILE=dev -p 8080:8080 document-service
```
### Expected Behaviour
micronaut should have picked up value of PROFILE but has not evaluated $PROFILE vaiable
Tell us what should happen
value of PROFILE is not picked up

### Environment Information

- **Operating System**: TODO
- **Micronaut Version:** 1.1.2
- **JDK Version:** 1.8.0_202

### Example Application

- https://github.com/ashishkujoy/document-service

**Comment by graemerocher** [comment]
What does this have to do with JSON?

**Comment by ashishkujoy** [comment]
> What does this have to do with JSON?

In JSON syntax environment variable is not getting evaluated while without JSON syntax environment variable is getting evaluated.

You can refer to this spring boot dockerized app https://github.com/ashishkujoy/spring-web-app
It evaluates the environment variable even in JSON syntax of CMD.

**Comment by graemerocher** [comment]
Where exactly is the JSON defined?

**Comment by ashishkujoy** [comment]
> Where exactly is the JSON defined?

In docker file 

CMD ["java" ,"-Dmicronaut.environments=${PROFILE}", "-XX:+UnlockExperimentalVMOptions" ,"-XX:+UseCGroupMemoryLimitForHeap" ,"-Dcom.sun.management.jmxremote" ,"-noverify ${JAVA_OPTS}" ,"-jar", "document-service.jar"]

This is known JSON array format of specifying command to be executed while running container.

You get more info about format of specifying CMD here https://docs.docker.com/v17.09/engine/reference/builder/#cmd

**Comment by graemerocher** [comment]
There is nothing Micronaut specific here this is related to Docker

**Comment by ashishkujoy** [comment]
> There is nothing Micronaut specific here this is related to Docker

Just wondering how spring is handling that.

**Comment by szczebel** [comment]
@graemerocher I observed that resolution of 'micronaut.environments' has a different behavior than for  other properties, as defined by https://docs.micronaut.io/latest/guide/index.html#_property_value_binding

The difference is that underscores resolve to dots for all properties except for micrinaut.environments.
 
I.e. I can specify `docker run -e some_property=xxx` and value xxx will be properly resovled in `@Value("${some.property}")`. But `docker run -e micronaut_environments=xxx` does NOT work, i.e. xxx is not reported as active environment.

is that expected behavior?

In order to pass environment to app running in container, I had to adjust my entrypoint to explicitly copy the value like so:
`CMD java -Dmicronaut.environments=${micronaut_environments} -jar server.jar`.
Not a big deal, just not very consistent; and if this cannot be addressed in Micronaut, I'd sugegst adding it to official guide, so others don't burn their time on it like I did.

**Comment by haaah** [comment]
@szczebel Do you still encounter this behaviour? Would you like to submit an issue?

**Comment by szczebel** [comment]
@haaah , I have not check on this since the time of adding the comment, so cannot say if anything changed with newer micronaut versions.

And given that I'm not working with micronaut nowadays, I'm not really keen on reproducing, opening and tracking an issue, sorry. If community has not raised it in some other issue, then maybe this does not require attention/priority anyways.
