### ISSUE TITLE
Don't generate beans if @Inject is present but the type is not declared a bean

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#1859]
Currently we generate a bean definition if there is a method or field annotated with `@Inject` regardless if the type is declared a bean. This IMO is not good behaviour as the scope of the bean is undefined.

It is also inconsistent as there is no way to achieve the same with constructor injection and constructor injection really is preferred approach so this encourages bad practise.

### Steps to Reproduce

Define a class:

```java
package test;

import javax.annotation.PostConstruct;

class Test {

    @Inject
    void setFoo(Foo foo) {
    

    }
}
```

### Expected Behaviour

A bean should not be generated without an undefined scope (either `@Prototype`, `@Singleton` or `@Context` as it can lead to unpredictable behaviour

### Actual Behaviour

A bean is generated.

**Comment by jameskleeh** [comment]
What about factory methods that are just annotated with `@Bean`? There is no explicit scope there either. Perhaps `@Bean` should be annotated with `@DefaultScope(Prototype.class)` ?

**Comment by benmccann** [comment]
It's a little unclear to me what is being proposed here, so I just want to check that the following would still be valid:

```
@Controller("/hello") 
public class HelloController {

  @Inject FooBar foo;
  
  @Get 
  public String index() {
    return "Hello World " + foo; 
  }

}

public class FooBar {

  @Inject FooBar() {}

  public String toString() {
    return "foo world";
  }
  
}
```

**Comment by graemerocher** [comment]
No that would not be valid. You would need to declare a bean scope to make it a bean such as Singleton

**Comment by benmccann** [comment]
I would be very upset if this change were made and it probably would stop me from using Micronaut. It saves a lot of unnecessary annotations, visual clutter, and boilerplate code to default no scope to prototype scope. It also would be inconsistent with other DI frameworks such as Guice and Dagger leading to higher learning curve and higher migration costs (e.g. I have projects I'm considering migrating from Play to Micronaut). If it were implemented, I hope it would at least be with an option that could be disabled. (Or alternatively that DI systems were made pluggable so that I could use something like Dagger instead though that seems less feasible)

> It is also inconsistent as there is no way to achieve the same with constructor injection and constructor injection really is preferred approach so this encourages bad practise.

I was confused by this statement. You can write constructors with just an `@Inject` annotation and no declared scope today (i.e. defaulting to prototype scope).

Also, while I understand why constructor injection is the preferred approach, I typically use field injection for controllers because it's far less verbose. E.g. compare this:

```
@Controller("/hello") 
public class HelloController {

  @Inject FooBar foo;
  @Inject HelloWorld hello;
  @Inject Example example;
  
}
```

To this:
```
@Controller("/hello") 
public class HelloController {

  private final FooBar foo;
  private final HelloWorld hello;
  private final Example example;
  
  @Inject
  public HelloController(FooBar foo, HelloWorld hello, Example example) {
    this.foo = foo;
    this.hello = hello;
    this.example = example;
  }

}
```

I've been writing controllers in other frameworks (e.g. Play Framework with Guice) for many years and have never encountered a bug due to this style that would have been avoided with constructor injection, so for me it would be imposing a large cost to solve a problem I've never had.

**Comment by graemerocher** [comment]
Ok we will consider your feedback and maybe make it a compiler option or something. Thanks for the feedback.
