### ISSUE TITLE
registerSingleton doesn't work

### ISSUE THREAD

**Issue by asarkar** [micronaut-projects/micronaut-core#1879]
Following up on Gitter [chat](https://gitter.im/micronautfw/questions?at=5d2467fcd0e06b667572d0b3):

```
val builder = Micronaut.build()
  .classes(Application::class.java) as ApplicationContextBuilder
builder.build()
  .registerSingleton(Clock::class.java, Clock.systemUTC())
  .start()
```

the above code is supposed to register a singleton bean of type `Clock`, but it doesn't work for Kotlin constructor injection. A fully-working sample application is available [here](https://github.com/asarkar/txn-stats).

If [Application.kt](https://github.com/asarkar/txn-stats/blob/master/src/main/kotlin/org/asarkar/stats/Application.kt) is modified as shown above, the constructor injection [here](https://github.com/asarkar/txn-stats/blob/master/src/main/kotlin/org/asarkar/stats/Statistics.kt#L18) fails, which can be easily seen by running [this](https://github.com/asarkar/txn-stats/blob/master/src/test/kotlin/org/asarkar/stats/StatsControllerTest.kt) test.

v1.2.0.RC1

**Comment by graemerocher** [comment]
The issue is that the static `main` method is not executed when running tests since this is only used as the entry point when running the application directly.

You can resolve the issue by modifying your `Application` class as follows:

```kotlin

import io.micronaut.context.annotation.*
import io.micronaut.context.*
import io.micronaut.runtime.Micronaut
import java.time.Clock
import javax.annotation.PostConstruct

@Context
class Application {
    @PostConstruct
    fun onStart(context : ApplicationContext) {
		context.registerSingleton(Clock::class.java, Clock.systemUTC())
    }
}

fun main(args: Array<String>) {
    Micronaut.run(Application::class.java)
}
```

Note that for the application if you reference the main class you need to use `org.asarkar.stats.ApplicationKt` instead of `org.asarkar.stats.Application`
