### ISSUE TITLE
Allow an Environment with mixed casing property resolution

### ISSUE THREAD

**Issue by agentgt** [micronaut-projects/micronaut-core#1893]
See this comment:
https://github.com/micronaut-projects/micronaut-core/issues/1217#issuecomment-510654772

Some of the below is repeated from the comment link above.

While I was hooking in our configuration framework with Micronaut (through the Environment) I stumbled over the kebab casing resolution.

I have hard time understanding why do all this kebab case resolution instead of just explicit resolution particularly:

 * Because Java is inherently camel case.
 * Spring allows camel case and just about every other java configuration framework.
 * Its very confusing to see a property name change names
 * Certain frameworks expect Class name configuration: Hystrix
 * Here is a typesafe config using spec to generate code: https://github.com/carueda/tscfg (camel cased).

In my experience the only time complicated property resolution has to happen is environment variables and that largely can be avoided by either not allowing it (ie environment variables are just locked to upper camel case) or by using special prefixes and then doing some resolution on that. Otherwise its doing something special about (".") which most folks are familiar with (e.g. TypeSafe Config path).

From the documentation:

> Micronaut still allows specifying the latter in configuration, but normalizes the properties into kebab case form to optimize memory consumption and reduce complexity when resolving properties. The following table summarizes how properties are normalized from different sources

I really have hard time buying this particularly after seeing #1714 .  Also particularly because there is lots of regular expression and parsing going on anyway in the property resolution.

Furthermore microservices are supposed to be you know micro and are not gigantic monolithic applications with 1000s of properties (in argument of the memory concern). However we do already have 10-20 microservices already in Spring and various other technologies that already have mixed casing properties some of which are stored in configuration services. To get an ideal one to one if we switch to micronaut would require updating all of those properties.

It also confusing from an API perspective because PropertySource has an iterator for the "real" key names that are not kebab cased.

Thus the following does not work:

```
for (String key : propertySource) {
    environment.getProperty(key, ....);
}
```

Its seems like you are really fighting what most Java developers expect and its seems overcomplicated for reasons that are not documented nor apparent.

However I'm not sure if the solution is perhaps to have a new PropertySourceConvention or to make Environment more pluggable especially since so much micronaut code is already doing the kebab case.

**Comment by jameskleeh** [comment]
> I really have hard time buying this particularly after seeing #1714

If you don't believe the current behavior was done for the reasons we state then that is your choice. We certainly aren't deceiving anyone about our motivations. As a response to the issue above we implemented solutions to reduce or eliminate the issue entirely. It wouldn't be ideal to forgo environment overrides because in some environments the default behavior would result in many more properties than others.

> However we do already have 10-20 microservices already in Spring and various other technologies that already have mixed casing properties some of which are stored in configuration services. To get an ideal one to one if we switch to micronaut would require updating all of those properties.

I don't understand why you would have to change anything in any of your configuration services. The configuration can be stored in camel case, however when retrieving the configuration in Micronaut, you would retrieve it kebab case. That doesn't require any changes to any of your configuration sources or other services.

> Its seems like you are really fighting what most Java developers expect and its seems overcomplicated for reasons that are not documented nor apparent.

It may not be what most Java developers expect, however that doesn't mean it is a bad design. The reasons that you quoted are document and apparent. Storing the properties normalized means they are only stored once (memory consumption and performance in lookup). When resolving the property you do not need to be concerned with which case the property was stored in. You can always reference it in kebab case and thus that is less complex. 

You could argue that it should work more like Spring where you can define and resolve properties in either case and it will work, however when designing a framework with low memory consumption as a main tenant, sometimes small sacrifices in usability must be done. This was the choice in this case.

I personally don't see any compelling arguments as to why this should be changed. I'll leave this open for a while in case you would like to provide further arguments.

**Comment by agentgt** [comment]
> If you don't believe the current behavior was done for the reasons we state then that is your choice.

My choice could be a myriad of things however I'm trying to adopt the framework as well as help you w/ adoption. From your tone you seem to have a very opinionated point of view as well as the framework which I'm fine with but I need reasons and the performance reasons don't seem backed. When opinions and frameworks aren't backed with some proof I have less buy in... aka adoption.

I didn't see any jmh benchmarks for the environment other than the recently added #1714 .  

I presume the memory concerns are the interning of string hashing keys? If the environment resolves properties explicitly by name I don't understand how this takes more memory.

I'm trying to understand and I haven't had a good explanation. 

> We certainly aren't deceiving anyone about our motivations.

Ditto. I'm trying to help with adoption as well as make it easier for people including my own team to embrace the framework.

It is not that I think you are deceiving. It is that I don't agree it is a problem from what I have seen from `DefaultEnvironment` particularly since `DefaultEnvironment` is already doing:

```
    private final Collection<String> packages = new ConcurrentLinkedQueue<>();
    private final ClassPathAnnotationScanner annotationScanner;
    private Collection<String> configurationIncludes = new HashSet<>();
    private Collection<String> configurationExcludes = new HashSet<>();
    private final AtomicBoolean running = new AtomicBoolean(false);
    private Collection<PropertySourceLoader> propertySourceLoaderList;
    private final Map<String, PropertySourceLoader> loaderByFormatMap = new ConcurrentHashMap<>();
    private final Map<String, Boolean> presenceCache = new ConcurrentHashMap<>();
    private final AtomicBoolean reading = new AtomicBoolean(false);
```

As well as numerous regular expression pattern matching etc etc.

>  It wouldn't be ideal to forgo environment overrides because in some environments the default behavior would result in many more properties than others.

I'm not sure I fully understand this. Do you mean environment variables? Speaking of opinions. I have fairly strong opinions about storing lots of config in environment variables however I realize in the docker world it is very common so I understand the need for environment variable resolution... up to point. Is the memory concerns because of environment variable name resolution? I guess why was kebab case picked in the first place? Was it arbitrary or is there something nice about it that I'm missing?

> however when designing a framework with low memory consumption as a main tenant, sometimes small sacrifices in usability must be done. This was the choice in this case.

I believe explicit property resolution will have equally if not lower memory consumption since there is less interning of strings going on. 

The things is even if it is a memory problem the better standard would have been camel case. You could standardize on that instead of "-". I realize it's too late for that but that would have been a better choice IMO.

**Comment by agentgt** [comment]
@jameskleeh 
Ignore my previous comment. For some reason I missed half your comment on the kebab explanation.

I will close the issue as I'm mostly satisfied with the explanation albeit I do not agree w/

> I don't understand why you would have to change anything in any of your configuration services. The configuration can be stored in camel case, however when retrieving the configuration in Micronaut, you would retrieve it kebab case. That doesn't require any changes to any of your configuration sources or other services.

and

> When resolving the property you do not need to be concerned with which case the property was stored in. You can always reference it in kebab case and thus that is less complex

I think no resolution is the best and least complex. ie you don't rename the property.

If I already have properties in other non micronaut code that then calls micronaut's environment I have to call `NameUtils.hyphenate()`  (ie `getProperty(NameUtils.hyphenate(.))`).

Secondly what happens when I need to reference "test-somethingBlahStuff"? What do I pass in to `Environment.getProperty` to get that property? What happens if I have another property called "test-something-blah-stuff"? These are complexities.

I also booted up an application with 1000s of properties and the additional memory consumption was marginal based on the operating system reporting. Not even a noticeable % difference. Boot up time did increase though (which makes me wonder if this is a time vs space thing).  I'll need to play around more and put it in isolation since the libraries we are using seem to be loading far more into memory.

For now I'll close the issue.

**Comment by graemerocher** [comment]
@agentgt Thanks for the feedback really, we do want to help folks adopt the framework and if there is some concrete problem that you can point to which our current implementation is causing let us know.

Let me explain a little bit about the way it works in Micronaut and how it relates to performance and memory consumption and the behaviour of the framework in general.

### Storage and Normalization of keys

Micronaut has to integrate with a whole range of libraries and and external third parties configuration objects. Each uses its own convention. For example Hibernate uses lower case under score separate properties. Kafka uses purely lower case dot separated. 

There is no standard in Java for how properties are to be defined so the ecosystem is a mess. Storing a single format and converting to other formats is the best way to tackle that problem and we use lower case kebab separated. Storing the raw keys as well would actually not consume that much more memory as noted but it has side effects.

### Performance of Key Resolution and ConfigProperties

As you know we allow the definition of simple classes annotated with `@ConfigProperties` that are bound from keys. It is fairly complex to compute the relationship between a `@ConfigProperties` bean like:

```java
@ConfigProperties("foo.bar")
class FooProperties {
       String barStuff
}
```
And the key format used to resolve each property. The reason it is complex is because you can have nested config properties, you can have `ConfigProperties` that extends from other `ConfigProperties`. You can declare `ConfigurationBuilder` that pull in properties that other libraries.

If we were to do this computation at runtime startup performance and memory would suffer. This is what Boot does. Micronaut instead at compilation time computes the key for each property and stores it in annotation metadata such as the `barStuff` property in the above example is stored as `foo.bar.bar-stuff` and we don't have to do this computation and the resolution is fast (just a map lookup).

This combined with the fact that `ConfigProperties` does not use reflection makes the binding very fast and memory efficient. If we were to not normalize the keys into a fixed format then we would have to do some complex and expensive computation to try to normalize and do mutliple lookups at runtime which would impact startup and memory consumption (since we would have to cache that lookups)

### Storing Both Normalized and Original Keys

So lets say we store both the normalized and the original key. In this case both `foo.bar.barStuff` and `foo.bar.bar-stuff`. It may seems innocent to do so but it has behavioural implications. For example if you had an `@EachProperty("foo.bar")` you would have 2 beans instead of 1.

I addition for external libraries you may end up with duplicates and potential invalid config passed to a third party library.

### Potential Improvements

Now what I would really like to see is some concrete examples from you of where you are seeing a problem with this. You mention for example using `getProperty(..)`. In general we discourage direct usage of this but one improvement could be to add a `getNormalizedProperty(..)` method if that helps?

Another potential improvement would be to store the original keys as an option and have a `getOriginalProperty(..)` or `getRawProperty(..)` method. 

These are all things that may could help, but what would help us is if you presented some concrete examples of config properties that are causing you a problem. This is probably the first time we have heard from a user that this particular issue is preventing adoption of the framework, but if it is we would like to see how we can address that and provide solutions.

**Comment by agentgt** [comment]
> These are all things that may could help, but what would help us is if you presented some concrete examples of config properties that are causing you a problem.

We have our own custom message bus library and custom configuration wrapper that are very analogous to Hystrix and [Archaius](https://github.com/Netflix/archaius) respectively (coincidental convergent evolution that our library is similar to how Netflix's work).

Libraries like Hystrix need dynamic properties. What I mean by dynamic properties is that they may change during runtime and that the overall number of properties may or may not be known even on initialization.

This is different than Micronaut where almost all of the properties are known at compile time or very shortly after initialization. Furthermore the properties don't change till reboot as they are often bound to a configuration object.

While the argument could be made that our message bus endpoints and Hystrix `Commands` configuration could wired up as bean managed by micronaut our library just doesn't work that way as it is dynamic. e.g. its not like a bunch of named DataSources where `@EachBean` or `@EachProperty` can be used.

> These are all things that may could help, but what would help us is if you presented some concrete examples of config properties that are causing you a problem.

I did early showing that you need to translate property names passed to `getProperty` using NameUtils.hyphenate. I was trying to hook our configuration framework to resolve on Micronauts (e.g. like another PropertySource).  We have decided to no longer do this for the dynamic configuration portion of our application  because of the limitations/confusion of Micronaut's property resolution. Furthermore we have our own configuration framework that has been tuned that we are using directly hence the main reason I decided to close. 

Since I wrote our configuration framework I do have some strong opinions of configuration and memory usage and thus when I see claims of we did so and so naming scheme to save memory I have doubts particularly because now any framework like mine has to re-resolve the names and then cache them which completely defeats the purpose of memory saving. NameUtils is expensive (regex) and is not garbage free so we will want to cache.

> There is no standard in Java for how properties are to be defined so the ecosystem is a mess. Storing a single format and converting to other formats is the best way to tackle that problem and we use lower case kebab separated. Storing the raw keys as well would actually not consume that much more memory as noted but it has side effects.

Furthermore almost all of Micronauts configuration gets turned into translation configuration objects which are then fed into the library. That is the library is never configured directly from the configuration which I think is completely fine for a framework like this but is not "memory efficient" albeit does improve lookup (space vs time).  For example for Flyway there is a FlywayConfiguration object. Literally every Micronaut module I found does this so it really begs the question why resolution needs to happen. Just standardize on kebab case and expect kebab case (ignoring environment variables). It doesn't matter because Micronaut is handing off an object and not configuration to these other libraries (ie the modules have their own factories). Thus you shouldn't care how the rest of the Java world (other libraries) does their configuration naming scheme. I understand why a standard was picked but don't understand the need for the resolution. I'm not sure I see or understand the "side effects" given the above?

Anyway If you are providing a configuration source explicit is better both in terms of memory and understanding of how it works (imagine if some KV store did what NameUtils does). 

I have come to the conclusion that Micronaut does not provide this and is not this. The configuration is to help facilitate factories and that is it. And this is good because it is a microservice framework that boots fast and dynamic configuration is not needed as much (because you can just reboot).

That is why I closed the issue. However I would stop saying you picked kebab casing for memory/ performance reasons particularly when just using YAML (snake) library to load up config makes the savings irrelevant (if there really are any) :).

Let me know though i you want me to reopen it. 

For now we are just wiring in our configuration framework into beans that do not need dynamic  properties and had Spring `@Value / @Named`. While @jameskleeh is right that I don't need to change the source configuration names I will I assume have to go change the old Spring annotated configuration names to kebab case?

Anyway I was pushing Micronaut but I am loosing the battle and we might just pick Dagger + Jooby at this point because of these kinds non straight forward behavior.

**Comment by agentgt** [comment]
Just to be clear on what I mean by explicit resolution:

 > Storing Both Normalized and Original Keys
So lets say we store both the normalized and the original key. In this case both foo.bar.barStuff and foo.bar.bar-stuff. It may seems innocent to do so but it has behavioural implications. For example if you had an @EachProperty("foo.bar") you would have 2 beans instead of 1.

Not if you do zero resolution. e.g. explicit. `foo.bar.barStuff` would not work since you standardized on kebab casing.

> I addition for external libraries you may end up with duplicates and potential invalid config passed to a third party library.

Like I said earlier in almost every Micronaut module I saw a configuration object is built which is then used by a `@Context` or `@Factory` to then build the third party libraries objects. Hibernate, RabbitMQ and many more do not appear to read from `Environment.getProperty`. Instead a Configuration bean is made either through `@EachProperty/@EachBean` and friends. 

Thus I'm not sure how invalid config is getting passed.

**Comment by graemerocher** [comment]
It is true the framework is optimized for using configuration objects bound from the environment and not doing explicit calls to getProperty, which is in fact discouraged as it leads to a mess IMO

We have the notion of refresh for handling dynamic changes. I am aware of how Hystrix and Archuis work although I don’t believe the approach taken there is in any way better.

We are happy to discuss adding new APIs that make explicit calls easier but to be frank if this issue is enough to convince you that Micronaut is not the right choice then I am not sure there is much more to be said

**Comment by agentgt** [comment]
> We are happy to discuss adding new APIs that make explicit calls easier but to be frank if this issue is enough to convince you that Micronaut is not the right choice then I am not sure there is much more to be said

It's not me alone. It's a team decision and it's large part the amount of code that would need to be changed as well as avoiding coupling (to avoid future migration issues if we need to). I'm looking into seeing how many properties we have that have mixed casing and other than the dynamic ones I'm not seeing many so far anyway (ie for the `@Named` injected scalar/string properties).... however I just can't wait till the next framework 5 years from now doesn't allow `"-"` (just joking around :) ).

FWIW I prefer Micronaut over the dagger + something else approach.

As for the the refreshing of dynamic properties... sigh... Yes in large part this happened when Spring-like more monolithic apps were built. We have been around for some time and thus a reboot was expensive. Again that is another reason why I closed the issue but I wanted to give you the context. Perhaps we will eventually migrate off doing this but we will need to test more.

Also I closed the issue because I appear to be the only one to have issue with it :)

**Comment by Andy2003** [comment]
Configuring Freemarker will not be possible with the kebab-case conversion:

    micronaut:
      views:
        freemarker:
          settings
            urlEscapingCharset: UTF-8

will result in this Error:

```
Caused by: freemarker.core.Configurable$UnknownSettingException: Unknown FreeMarker configuration setting: "url-escaping-charset"
	at freemarker.core.Configurable.unknownSettingException(Configurable.java:2813)
	at freemarker.core.Configurable.setSetting(Configurable.java:2731)
	at freemarker.template.Configuration.setSetting(Configuration.java:3390)
	at freemarker.core.Configurable.setSettings(Configurable.java:2879)
	at io.micronaut.views.freemarker.$FreemarkerViewsRendererConfigurationPropertiesDefinition.injectBean(Unknown Source)
	at io.micronaut.views.freemarker.$FreemarkerViewsRendererConfigurationPropertiesDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1511)
	... 81 common frames omitted
```

Freemarker expects: `urlEscapingCharset` or `url_escaping_charset`

**Comment by agentgt** [comment]
Just for my edification and @graemerocher can correct me:

Freemarker Micronaut plugin Probably needs to call `NameUtils.hyphenate()` or  `unhyphenate` if its going to pass the property through but my bet is that `urlEscapingCharset` it is going to have to be added to  micronaut Freemarker's `FreeMarkerConfiguration` object.

That is it will be fairly difficult or maybe not possible for other libraries to read key/value like configuration from Micronaut and the preferred approach is creating a POJO that represents the configuration. 

Is that right @graemerocher ? 

In many ways I like and prefer this approach albeit its sort of Spring-lets-wrap-everything w/ a thin wrapper.

**Comment by jameskleeh** [comment]
@agentgt That is not correct. We have a `MapFormat` annotation that can transform the key to camel case. The properties will not need to be explicitly defined in the configuration object

**Comment by graemerocher** [comment]
Correct transformation is probably lower case under score separated like Hibernate https://github.com/micronaut-projects/micronaut-sql/blob/master/hibernate-jpa/src/main/java/io/micronaut/configuration/hibernate/jpa/JpaConfiguration.java#L219

**Comment by agentgt** [comment]
Interesting about `MapFormat`. That maybe useful for our migration purposes. For some reason I missed that in the documentation or thought it wasn't configuration related.

**Comment by agentgt** [comment]
I think `MapFormat` will basically fulfill our needs. I wasn't aware that it would allow raw property access through `MapFormat.keyFormat`.

If I knew about this sooner I probably would have made less a deal about not being able to access raw properties however I still would like `@Value` and/or `@Named` to use the raw property name.

Some DI frameworks will pull configuration properties from `@Named` if the value is a scalar and isn't found as a registered bean (Spring does not do this but Weld and Guice do). We use Guice in a few projects.  What do you think about making `@Named` use raw property access?

**Comment by graemerocher** [comment]
seems like a neat idea

**Comment by nkatakkar** [comment]
Kind of stuck with Micronaut's seemingly different naming convention for Java. 
While Micronaut uses the Naming Convention that the team has found reasons to use, I am trying to figure out solution to my POC that I am doing for my new project.

We connect to Oracle Database using SSL certificates. For this we need to set some properties on the DataSource which are then passed on to Oracle Driver which is oracle driver requirement and have no control. Due to the actual key name getting changed, now the driver refuses to connect as it is not finding SSL certificate.

e.g my application yml is

datasources:
  default:
     url: JDBC SSL URL No need to provide user password
     dataSourceProperties:
        javax.net.ssl.keyStore=""
       javax.net.ssl.keyStorePassword=""

For couple of days, couldn't figure out why Oracle driver wasn't able to connect. Then dawned on me -  actual property passed in java.util.Properties to Oracle Driver is java.net.ssl.key-store (and not keyStore ..oh dear!) Oracle driver tries to look for keyStore but the property is nowhere to be find although it's right there sitting under different key-store.

I bump into this post while trying to see if there's a way to default to usual camelCase naming. If the performance or efficiency of handling it is the reason then OK! Great!. But I still would have preferred an option that allows certain properties in yml to be used as is and no transformation- especially when passed on to 3rd party and have no control.

May be there is a way and I haven't found it yet.  Appreciate your help if you can point me in right direction.

I have had to use @Replaces before with DefaultGraphQLInvocation as I needed access to underlying HttpRequest (HttpRequest has SSL certificates and wasn't even able to invoke Authentication Providers for SSL So just did it with Filter) I am now looking to do something similar and replace DataSourceFactory - not sure it will work. But don't like the idea of having to override framework beans over and again to get desired behavior - I hope all this is in built and it's just my lack of understanding for now.

**Comment by graemerocher** [comment]
@nkatakkar please report an issue to https://github.com/micronaut-projects/micronaut-sql/issues for this one. 

We need to know which datasource pool you are using. Thanks

**Comment by nkatakkar** [comment]
micronaut-jdbc-hikari
Also tried micronaut-jdbc-tomcat
Looking at code from tomcat jar, perhaps easier to Replace that than the Hikari one.

**Comment by nkatakkar** [comment]
Also I don't think this is SQL issue. This is the way Micronaut handles properties. Nothing to do with SQL in my opinion.

**Comment by graemerocher** [comment]
The issue is that `dataSourceProperties` on the `DatasourceConfiguration` for hikari is not specifying the key format to use for the properties (in this case `RAW`). Once that issue is resolved then it will work as expected.

**Comment by nkatakkar** [comment]
Thank you. 
When I tried using it with micronaut tomcat , I had similar issues. However, when I look at the code, setDbProperties is hardwired with StringConvention.UNDER_SCORE_SEPARATED.
So for now seems like I can Replace this bean and I will try that.
Will there be a way to specify the StringConvention to use in the yml for selective properties ?Or else every time will need to Replace framework bean - which I will like to avoid.

**Comment by graemerocher** [comment]
Once the underlying issue is resolved you won't need to replace the string convention. You also do not need to replace the bean either. Since programmatic configuration is also possible with a `BeanCreatedEventListener` such as:

```java
class DatasourceConfigurationCustomizer implements BeanCreatedEventListener<DatasourceConfiguration> {
       DatasourceConfiguration onCreated(BeanCreatedEvent<DatasourceConfiguration> event) {
             DataSourceConfiguration bean = event.getBean();
             Properties properties =   new Properties()
            // set your custom properties here
            ...
             bean.setDataSourceProperties(properties);
             return bean;
      }
}
```

**Comment by nkatakkar** [comment]
Many Thanks. :)
That worked ! And whole lot better than having to replace bean.
I am able to connect to Oracle DB with SSL keystore now.

Have noted it down to look for the resolution of this issue. But for now have been able to proceed ahead with my POC.

For my graphql issue will raise it on micronaut-graphql.
Again - thank you for your help.

**Comment by nkatakkar** [comment]
I tested it with both - Hikari and tomcat. Both worked fine with the DatasourceConfigurationCustomizer 
Will go with Hikari.
Just an observation - Hikari tries to connect on application startup, where as tomcat seems to be lazily initialized and only connects when actual DB call is made. 
But it is working quite well now. Thank you.
