### ISSUE TITLE
Question: Micronaut Security vs Spring Security

### ISSUE THREAD

**Issue by michael-fl** [micronaut-projects/micronaut-core#1935]
Hello,

one of the reasons (possibly the only reason) for our company to choose Spring Boot for our new microservice architecture was to integrate the solid and production proven Spring Security library. I'm interested in the state of Micronaut Security, particularly compared to Spring Security. I was not able to find some blogs or statements on the internet regarding this topic, therefore asking here. I'd love to switch from Spring Boot to Micronaut, however I'm not sure about security issues.

**Comment by graemerocher** [comment]
Hi @michael-fl so Spring Security is a very broad ranging security solution that includes integration in a variety of scenarios that predate Microservices by some distance including things like container managed security, JavaEE integration and so on.

Micronaut Security (https://github.com/micronaut-projects/micronaut-security) is Micronaut's official security solution and addresses a much narrower scope for Microservices using current best practices and standards such as JWT, OpenID Connection, OAuth 2 and so on.

It has fewer configuration options because in a Microservice scenario you simply don't need the additional bells and whistles that Spring Security has to offer. That said Spring Security is very modular and if you wish to integrate parts of it into Micronaut Security then that is very possible. For example we've often seen cases where it makes sense to use the Crypto module from Spring Security within Micronaut Security.

Ultimately Spring Security is just another Java library so you can infact simply plug it into Micronaut if you so choose.

Hope this helps!

**Comment by michael-fl** [comment]
Hi @graemerocher,
thanks for your good explanation. This helps a lot!

**Comment by mrts** [comment]
Hi @graemerocher, thank you for explaining the Micronaut view regarding Spring Security!

What I (and I'm sure others as well) miss the most in Micronaut Security is the [Spring Security Expression-Based Access Control](https://docs.spring.io/spring-security/site/docs/5.2.1.RELEASE/reference/htmlsingle/#el-access), especially _Method Security Expressions_. 

Will the following example from Spring Security docs

```java
@PreAuthorize("hasPermission(#contact, 'admin')")
public void deletePermission(Contact contact, Sid recipient, Permission permission);
```

work with Micronaut if I plug Spring Security in? Getting annotation processing to work seems non-trivial.
