### ISSUE TITLE
Upgrade Gradle build to Gradle 5.5 and use java-library and java-platform plugins

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#1970]
Gradle now has built in support for publishing BOMs and defining platforms.

We should shift to the native support and remove our custom solution.

**Comment by zendern** [comment]
Im thinking of picking this up. @graemerocher any issues with that since its already been marked for milestone 1.3.0?? Just wondering if it has already been started.  

FWIW Im tired of dealing with intellij complaining about the java version since it runs on java 11 and the gradle version <4.7 doesn't play nicely together with not java 11 projects. I could also just downgrade my intellij jvm too but why :) 
https://youtrack.jetbrains.com/issue/IDEA-210875#focus=streamItem-27-3407199.0-0

**Comment by gijsleussink** [comment]
@zendern need any help? What's the status?

**Comment by zendern** [comment]
> @zendern need any help? What's the status?

I opened a draft PR to get the tests running every time I changed something. 
https://github.com/micronaut-projects/micronaut-core/pull/2128

Currently I am a little stuck on the shadowJar stuff (The non working WIP code is here https://github.com/zendern/micronaut-core/tree/gradle-upgrade-shadow-jar-stuff). The `core` module creates a shadow jar but when I configure the publishing.gradle file to output it as a shadowJar now the other modules that depend on it will not compile.

If you have cycles I wouldn't mind a little help. You can DM me on gitter and I can give you more details on where its at, how i've validated thus far, etc, etc. 

I believe its the last thing that will be needed before we can open a real PR and get more eyes on it.

**Comment by vnesek** [comment]
@zendern if it helps, I've few small micronaut projects running with gradle 5.5+. Everything works fine if you keep shadowJar plugin on 4.0.4.

When using shadowJar 5+, build passes without any warning or error messages however built artifact doesn't include dependencies. I lost few hours trying to figure out what's a problem but haven't been able to figure it out.
