### ISSUE TITLE
Boolean client channel options via env variables throws ClassCastException

### ISSUE THREAD

**Issue by markjfisher** [micronaut-projects/micronaut-core#2005]
When I use an environment variable to set a Boolean value for a Channel Option, I get a ClassCastException:

`MICRONAUT_HTTP_SERVICES_FOO_CHANNEL_OPTIONS_SO_KEEPALIVE=false`

```
WARN  io.netty.bootstrap.Bootstrap - Failed to set channel option 'SO_KEEPALIVE' with value 'false' for channel '[id: 0xf230c6ff]'
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
```

It works in yaml config, but doesn't work from environment variable matching.

**Comment by jameskleeh** [comment]
Can you post the full stacktrace or a sample application

**Comment by markjfisher** [comment]
I've create a minimal example at https://github.com/markjfisher/mn-channel-options with README.md explaining how to cause it.

**Comment by jameskleeh** [comment]
So while this is an issue, the way this is implemented is not recommended.

Using environment variables to override configuration options that are named (`@EachProperty`) will cause issues because many more of those items will be created than intended. In your example the following services will be created:

* `micronaut.http.services.foo`
* `micronaut.http.services.foo-channel`
* `micronaut.http.services.foo-channel-options`
* `micronaut.http.services.foo-channel-options-so`
* `micronaut.http.services.foo-channel-options-so-keepalive`

So instead of using the environment to directly override a property, use the environment variable in your config

```
micronaut:
    http:
        services:
            foo:
                channel-options:
                    so_keepalive: ${SOME_ENV_VAR}
```

You could even use the same environment variable name as long as you excluded it from config while building the context. That and the above is described here https://docs.micronaut.io/latest/guide/index.html#propertySource

**Comment by markjfisher** [comment]
Thanks James for the additional info, we've used the pattern you mentioned before, but I didn't like the double hit of having to create an environment variable, and configure it in the application.yaml,  when micronaut already reads environment variables directly into configuration, so the application.yml section is not required. I hadn't (however) noticed the warning section before in the property source notes. When you say those services are created, do you mean additional generated code?

I wonder if the same CCE will happen with ConfigMaps as PropertySources in a k8s environment?

We only have a few values configured by setting an environment variable in our deployment.yaml, but want to move them to the new micronaut-kubernetes way of using ConfigMaps, but I think that's just key/value pairs too, but exposed as PropertySources.

I'll be doing that work at some point soon, so I'll let you know how I get on with it.

**Comment by dnovitski** [comment]
Hi, I've hit the same issue with setting the AUTO_READ option, when injected from system environment:

`micronaut.server.netty.child-options[AUTO_READ]=false`

I did not see anywhere that the `[..]` was supported, but it works. However, the value passed to Netty is a String type, and it does not like that:

`i.n.b.ServerBootstrap:449 - Failed to set channel option 'AUTO_READ' with value '0' for channel '[id: 0x46baf7f3, L:/172.17.0.3:8080 - R:/172.17.0.1:47002]' `

**Comment by dnovitski** [comment]
Furthermore I'd like to add my opinion that System Environments should be on par with application.yml, or atleast should strive to be. System Environment should not be a second rate citizen to application.yml

**Comment by graemerocher** [comment]
Seems to be fixed by https://github.com/micronaut-projects/micronaut-core/pull/3056
