### ISSUE TITLE
InMemorySessions don't expire

### ISSUE THREAD

**Issue by RawkBR** [micronaut-projects/micronaut-core#2084]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Enable Sessions on the `hello-world-java` example project
2. Create `SessionCreatedEvent` and `SessionExpiredEvent` listeners
3. Add Session parameter to the Controller method
4. Send a request

### Expected Behaviour
Sessions should expire after an interval

### Actual Behaviour
Sessions don't expire, `SessionExpiredEvent`s are never fired.
Setting `micronaut.session.max-inactive-interval=1m` with any value doesn't seem to work either.

### Environment Information

- **Operating System**: Ubuntu 
- **Micronaut Version:** 1.2.0
- **JDK Version:** 1.8

### Example Application
https://gitlab.com/nmurakami/micronaut-hello-world-java-session-problem

**Comment by ShariqGHub** [comment]
@jameskleeh - It seems this issue is still there. Can you please confirm if this is completed or still open. Here is what I tried.

We are using the micronaut’s InMemorySession to store some objects. We want InMemorySession to get invalidated after a maxInactiveInterval of say 15 mins.
 We have used the set "maxInactiveInterval" property to 15 mins, and even other time limits. But the InMemorySession object is not getting invalidated. I took a heapdump and still see the object in the heap.
So, can you suggest - How to clear InMemorySession from Heap Memory area, as setting maxInactiveInterval is not working? 

Posted the same in the [Gitter Forum](https://app.gitter.im/#/room/#micronautfw_questions:gitter.im/$Vs2gmHhmnQZq40yLtVJGHdi5V_vtEQ5oxqNRefuayQY), but havent got a response.
