### ISSUE TITLE
We want to know what application can be applied with 1.0.0 Snapshot version?

### ISSUE THREAD

**Issue by ggservice007** [micronaut-projects/micronaut-core#214]
We now are using this framework.

It is very nice and cool.

We want to know what application can be applied with 1.0.0 Snapshot version.

Our use case is for processing a lot of^2 data.

Thanks regards.

**Comment by graemerocher** [comment]
I'm not sure I understand the question, you want to know what types of applications can be built with Micronaut?

**Comment by ggservice007** [comment]
Yes, we are building high concurrent bigdata application based on PaaS platform. Is Micronaut suitable for developing web application for this type?

**Comment by graemerocher** [comment]
Absolutely. Just to note that if high concurrence is important then you should write your data access logic in a non-blocking manner using non-blocking drivers if possible. Otherwise shift the work to the IO thread pool and configure your thread pools to handle blocking operations and load appropriately
