### ISSUE TITLE
Support InputStream as Controller parameter

### ISSUE THREAD

**Issue by phxql** [micronaut-projects/micronaut-core#2281]
Hi,

i would like to propose `@Body InputStream` as a controller parameter. We don't want to use reactive programming and would like to stream the HTTP request body from client to the server. At the moment this doesn't work, so we are using a really ugly hack:

```java
public HttpResponse upload(@Body Flowable<byte[]> flowable) {
            PipedOutputStream outputStream = new PipedOutputStream();
            PipedInputStream inputStream = new PipedInputStream(outputStream);

            new Thread(() -> {
                flowable.blockingSubscribe(
                        outputStream::write,
                        Throwable::printStackTrace
                );
                try {
                    outputStream.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }).start();

 // do something with the inputStream
}
```

I think it would be great if Micronaut could provide a non-reactive way to stream the request body.

**Comment by graemerocher** [comment]
So in this case we would have to run the operation on different thread since it would occupy a thread using blocking I/O though I am not opposed to the idea as for certain use cases like reading a zip file which requires a `ZipInputStream` (I am not aware of another way in Java to read zip files). However we need to consider carefully how we handle this case. Would be be that simply declaring `@Body InputStream inputStream` is enough to indicate that we must run this on a separate thread so as to not block? Probably.. requires additional thought.

Note that your hack is actually unlikely to be thread safe. You would need to control back pressure. since you may end up with overlapping calls to `OutputStream.write` which could mangle the data. If you refer to the javadoc for `blockingSubscribe` it states that it `The operator consumes the source Flowable in an unbounded manner`

You would probably need to use `blockingSubscribe(Consumer<? super T> onNext, int bufferSize)` and pass in a size you wish to use to buffer the chunks of byte[] you are going to receive in the case of back pressure.

**Comment by phxql** [comment]
Thanks for the hint, i have fixed that.

**Comment by jameskleeh** [comment]
Also you don't have to start the thread yourself and do blockingSubscribe. You can use `.observeOn(Schedulers.newThread())` and then subscribe normally

**Comment by binoysankar** [comment]
I am currently migrating Spring boot to Micronaut and facing the same scenario which in one of the POST endpoint I am having InputStream as body. I used the code above which @phxql used and its working. 
@jameskleeh Would like to know how to use `.observeOn(Schedulers.newThread())` as am not very good in rxjava and couldn't make it work as below.

`byteStream.observeOn(Schedulers.newThread(), false, Observable.bufferSize()).subscribe(outputStream::write, Throwable::getMessage);` 
I am sure I am doing it wrong can somebody help me here.
