### ISSUE TITLE
MessageSource interpolate should be part of get message

### ISSUE THREAD

**Issue by niravassar** [micronaut-projects/micronaut-core#2332]
`MessageSource` in micronaut has a ` @Nonnull Optional<String> getMessage(@Nonnull String code, @Nonnull MessageContext context);` signature. This takes a key and will get the value of the message. However, it does not support message parameters, whereas you can send in value which will fill the placeholders such as `{0} and {1}`.

There is a interpolate signature: `@Nonnull String interpolate(@Nonnull String template, @Nonnull MessageContext context);`. This takes a message template with placeholders and also the `MessageContext` which can contain variables, intended to fill the place holders. 

I feel this functionality should be contained in the `getMessage` functionality. When getting a message currently it is a "two step" process, where it could conceivably be done through the `getMessage` api. 

For example, for thymeleaf views, I did this to populate the template with variables:

https://github.com/micronaut-projects/micronaut-views/blob/8848688e848cddfceb78c893b2dceacfffba653a/views-thymeleaf/src/main/java/io/micronaut/views/thymeleaf/MicronautThymeMessageResolver.java#L48

**Comment by jameskleeh** [comment]
I guess the crux of this is that if you pass a context with variables to the `getMessage` method, it's natural to assume those variables would be used to interpolate the message.

Thoughts @graemerocher ?

**Comment by C06A** [comment]
Would your problem go away if you would use Groovy or Kotlin instead of Java and use String interpolation feature there to create your key?

**Comment by szczebel** [comment]
Can I vote this up?
Just came across this issue in my project, and found the two-step process of resolution as quite surprising from its design standpoint.

**Comment by jeffbrown** [comment]
> Can I vote this up?

Yes.  Thanks for the feedback.

**Comment by graemerocher** [comment]
The reason for this originally is it is how the Validator API spec separates message resolution with a separate `interpolate` message for interpolation since the latter is not free from a performance perspective. I can understand how it is confusing however since the behaviour is different to how for example Spring behaves. We can consider updating it.

**Comment by szczebel** [comment]
Yup, my case was migrating a SpringBoot app, so the surprise/confusion came right from there.

I'd even go with a convenience method of:
`MessageSource.getMessage(String key, String... params)`
so that the `MicronautThymeMessageResolver.translateMessagesToMap(...)` can be part of `MessageSource` module. Otherwise lots of people will be copying it around or reinventing in their projects.
