### ISSUE TITLE
@Error handlers cannot return a Single and causes a internal server error response but no error log

### ISSUE THREAD

**Issue by StephenOTT** [micronaut-projects/micronaut-core#2396]
Micronaut: 1.2.6
Kotlin: 1.3.50

When using a error handler (tested with a local error handler) if you set the return as `Single<HttpResponse<JsonError>>` it will always cause a internal error response with a `{}` body. But there is no error that shown in the logs.

**Comment by willbuck** [comment]
Could you help me better understand what you mean @StephenOTT ? This is sounding very similar to https://github.com/micronaut-projects/micronaut-core/issues/2324

**Comment by TFaga** [comment]
I've experienced the same issue. Please find a super quick example showing the problem.

```java
@Controller("/v1/forms")
@Produces(MediaType.APPLICATION_JSON)
public class FormController {

    @Get("/{id}")
    public Single<Form> get(@PathVariable("id") UUID id) {
        return Single.error(new NotFoundException());
    }

    /// Errors
    @Error(exception = NotFoundException.class)
    public Single<HttpResponse<ApiError>> notFound(HttpRequest request, NotFoundException e) {
        
        return Single.just(
                HttpResponse.notFound(new ApiError(UUID.randomUUID(), "resource.not.found"))
        );
    }
}
```

When calling `/v1/forms/:id`, which triggers the `get` method of the above controller, instead of returning a `404` with the correct response (`ApiError` json) as per the error handler, it returns a `500` and and empty JSON `{}`. If you don't use a reactive return type (i.e. just `HttpResponse<ApiError>`, the error handler works as expected with the correct status code and json body.

Micronaut: 1.3.4
Java: 13

**Comment by graemerocher** [comment]
Thanks we will take a look. Note there is no value in returning a single there since your code is not doing anything that would benefit from reactive programming

**Comment by TFaga** [comment]
Thanks and agreed. Just wanted to make sure returning a non-reactive class does not trigger a context switch to an IO thread to process the error handler, such as returning a non-reactive class in a normal controller method does.
