### ISSUE TITLE
@Error global handler documentation is missing 'global=true' annotation parameter, but tests are failing if provided.

### ISSUE THREAD

**Issue by marcpa00** [micronaut-projects/micronaut-core#2434]
Thanks for reporting an issue for Micronaut, please review the task list below before submitting the
issue. Your issue report will be closed if the issue is incomplete and the below tasks not completed.

NOTE: If you are unsure about something and the issue is more of a question a better place to ask questions is on Stack Overflow (http://stackoverflow.com/tags/micronaut) or Gitter (https://gitter.im/micronautfw/). DO NOT use the issue tracker to ask questions.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. from master, make sure tests are green (specifically test-suite, test-suite-groovy, test-suite-kotlin)
2. Set the global parameter to true for the @Error annotation on error method: see patch attached
[doc-global-error-annotation.patch.txt](https://github.com/micronaut-projects/micronaut-core/files/3902825/doc-global-error-annotation.patch.txt)
3. run the tests : 14 failures in test-suite, 7 in test-suite-groovy, 7 in test-suite-kotlin

### Expected Behaviour

Documenting correctly the @Error global annotation should not interfere badly with the tests.

### Actual Behaviour

Fixing the documentation by setting global=true in the annotation parameters effectively installs a global error handler that is used and interferes with some test assertions.

### Environment Information

- **Operating System**: macOS
- **Micronaut Version:** 1.2.6
- **JDK Version:** java version "1.8.0_201"

### Example Application

- see Pull Request #2433 (closed, this issue reported instead)

**Comment by marcpa00** [comment]
Maybe a potential solution would be to have a custom exception that is never thrown in the unit tests and bind the global error handler to it ?

**Comment by jameskleeh** [comment]
The solution is to ensure the controller is only loaded for the tests its executing for by using `@Requires(spec.name = ...)` like we do many other places in the test suites

**Comment by lgathy** [comment]
Thanks for taking a look into this. I think since this class serves demonstrative purposes for the documentation only (if I am not mistaken) it would be best to modify the test cases accordingly. Since this example is named and intended to be a global error handler if it is really not doing that, then best would be to modify the expectations in the tests, or alternatively the method body so that it does not interfere with the current tests.

@jameskleeh I don't know for sure where and how to add that exactly. Would that be the class or just the method itself? And what to set as spec.name? If it is not effecting the snippet directly then I would consider that a good solution. Otherwise, it would add confusion to the documentation.

@marcpa00 Sorry, I did not find your already existing issue+PR.

**Comment by jameskleeh** [comment]
No worries, I’ll take care of it
