### ISSUE TITLE
Constraint validation exception when repository returns optional with 1.3.0.M2

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#2608]
After upgrading an application with Micronaut Data JDBC to Micronaut 1.3.0.M2 one test that returned an empty optional failed.

### Steps to Reproduce

Create an entity:
```java
@Entity
@Table(name = "USER")
public class UserEntity {

    @Id
    @NotNull
    @Nonnull
    private String id;

    @Nonnull
    @NotBlank
    private String name;

    // Constructor, getters and setters
}
```

Create a repository:
```java
@Validated
@JdbcRepository(dialect = Dialect.H2)
public interface UserRepository extends CrudRepository<UserEntity, String> {

    @NotNull
    Optional<UserEntity> findByName(@NotBlank @Nonnull String name);
}
```

Create a test:
```groovy
@MicronautTest
class UserRepositorySpec extends Specification {

    @Inject
    UserRepository userRepository

    void 'try to find a user by name that does not exist'() {
        when:
        Optional<UserEntity> optUser = userRepository.findByName('Iván')

        then:
        optUser.isEmpty()
    }
}
```

The test fails with:
```
optional: must not be null
javax.validation.ConstraintViolationException: optional: must not be null
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:137)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at mn.data.constraint.optional.UserRepositorySpec.try to find a user by name that does not exist(UserRepositorySpec.groovy:16)
```

### Expected Behaviour

The test should pass. It passed with 1.3.0.M1

Removing the `@NotNull` make the test pass but it should pass with the annotation because an empty `Optional` is not `null`.

### Environment Information

- **Operating System**: Linux Mint 19.3
- **Micronaut Version:** 1.3.0.M2
- **JDK Version:** Openjdk 11

### Example Application

- https://github.com/ilopmar/mn-data-empty-optional

**Comment by jameskleeh** [comment]
So in general we assume the constraints apply to the value when wrapper types are used. For example `@Max(10) OptionalLong value`. It's clear there the annotation applies to the value inside the optional and not the optional itself. I don't know how we would distinguish between that use case and this one. The change in M2 was to enable return type validation to work where it wasn't being applied at all previously

**Comment by graemerocher** [comment]
Yeah I am not sure `@NotNull` even makes sense if you return `Optional`

**Comment by ilopmar** [comment]
I didn't know that the constraints are applied to the value when wrapper types are used, so I think this makes sense. We used this a lot in another 1.2.x project and started doing the same for a new project in 1.3.0.M1.

**Comment by miguelaferreira** [comment]
I just bumped into this issue after upgrading to micronaut `1.3.2` and, while not trying to re-open the issue, I would like to offer my thoughts on this.

I understand the argument of having validation on the inner-values when using a wrapper type. However, a wrapper type can also exist in the domain of the application, in which case I'm not sure the framework would detect it.

> Yeah I am not sure @NotNull even makes sense if you return Optional

My concern is inline with comment @graemerocher's, in the sense that Optional is an object and objects are nullable, therefore, in my opinion, `@NotNull` makes as much sense for Optional as it does for any other object. Having the framework decide what is a wrapper object and what is not seems flakey because it can lead to different behaviours on the same type of activities. 

If nothing else, this behaviour seems confusing to me and it's not just because it changed from one version to the other.

**Comment by jameskleeh** [comment]
@miguelaferreira Would it be confusing if you had `@Max(10) Optional<Long> optionalLong` and it didn't work because it wasn't possible to validate the value inside the optional?

**Comment by miguelaferreira** [comment]
@jameskleeh Yes, it is just as confusing.

I would expect that the annotation apply to the returned object. 
Having said that, I do see value in matching on inner values, but in that case I would prefer to see it explicitly on the annotation(s). 

```
@InnerValueValidation(@Max(10)) Optional<Long> optionalLong
```
or
```
@UnboxedMax(10) Optional<Long> optionalLong
```

Otherwise mixing semantics is always going to be confusing.

**Comment by graemerocher** [comment]
This is actually how the bean validation spec says things should behave so I see now issue with the current behaviour

**Comment by jameskleeh** [comment]
@miguelaferreira See https://beanvalidation.org/2.0/spec/#constraintdeclarationvalidationprocess-containerelementconstraints-implicitunwrapping

**Comment by miguelaferreira** [comment]
Thanks for the pointers. Having reviewed the specs it seems logical to me that numeric validations attached to a type that wraps a number imply the unwrapping of the value. However, for generic validation properties like `@NotNull` (which apply to any kind of object) the spec offers ways to disambiguate the expected behaviour. They even provide an example of how `@NotNull` should work with respect to unwrapping.
```java
@NotNull(payload = Unwrapping.Skip.class)
private StringProperty name;
```
or (my own example)
```java
@NotNull(payload = Unwrapping.Unwrap.class)
private Optional<String> name;
```
This approach to disambiguation seems very much inline with what I was proposing. Knowing that micronaut's default is to always unwrap values, I will test how can I disable that with the annotations I just learned about.
