### ISSUE TITLE
MongoDB SSL connection not working - doesn't pick up streamType

### ISSUE THREAD

**Issue by liefra** [micronaut-projects/micronaut-core#262]
When connecting to a MongoDB server using SSL (e.g. using MongoDB Atlas) , the Mongo driver requires the use of a `NettyStreamFactoryFactory`. This can be configured using `streamType=netty` parameter in the connection `URI`.

Currently this `streamType` parameter is not being picked up nor have I found any configuration option in `ReactiveMongoConfiguration`.

### Steps to Reproduce

```java
@Context
public class MongoDbTest {

    private MongoClient mongoClient;

    @Inject
    public MongoDbTest(MongoClient mongoClient) {
        this.mongoClient = mongoClient;
    }

    @PostConstruct
    public void test() {

        // Not working
        Observable.fromPublisher(mongoClient.listDatabases())
                .blockingIterable().forEach(System.out::println);

    }
    public static void main(String[] args) {
        Micronaut.run(MongoDbTest.class);
    }
}
```

```yaml
micronaut:
    ssl: true

mongodb:
    uri: mongodb+srv://username:password@clusterxxx.mongodb.net/?streamType=netty
    ssl:
      enabled: true
```

### Expected Behaviour

Using the `MongoClients.create` or `MongoClientSettings.builder()` directly works.

```java
@Context
public class MongoDbTest {

    private MongoClient mongoClient= MongoClients.create("mongodb+srv://username:password@clusterxxx.mongodb.net/?streamType=netty");

    @PostConstruct
    public void test() {

        // This works
        Observable.fromPublisher(mongoClient.listDatabases())
                .blockingIterable().forEach(System.out::println);

    }

    public static void main(String[] args) {
        Micronaut.run(MongoDbTest.class);
    }
}
```

### Environment Information

- **Micronaut Version:** master

**Comment by graemerocher** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-core/commit/0886d4789175f11e946ae6bcd58c3bee0a32da5e

Note that if you specify `mongodb.uri` the other settings are not taken into account. Use `mongodb.host` if you wish configure the other settings. This is because the driver expects you to *either* pass a connection string or a mongo client settings, but not both

**Comment by graemerocher** [comment]
I've rolled back some of the changes here. It seems there is no way to specify the `streamType` and also provide custom settings to mongo (like the codecs etc.) this is because the method in the `com.mongodb.async.client.MongoClients` is private:

```
private static MongoClient create(final MongoClientSettings settings,
                                      @Nullable final MongoDriverInformation mongoDriverInformation,
                                      @Nullable final String requestedStreamType)
```

So if you pass a `ConnectionString` you cannot specify codecs. If you pass a `MongoClientSettings` you can specify codecs but not the `requestedStreamType`

This deserves an issue in the driver.

**Comment by graemerocher** [comment]
I have created https://jira.mongodb.org/browse/JAVA-2884 to track this

**Comment by graemerocher** [comment]
Pushed a workaround
