### ISSUE TITLE
Improve AnnotationMapper#map by passing the Element

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-core#2642]
Sometimes when writing annotation mappers, it is useful to access the element being visited.

I can put together a PR to implement this.

**Comment by graemerocher** [comment]
We could do this, however the issue is we wouldn't be able to expose annotation information about the element because the annotation metadata is under construction, hence it is a circular problem.

The best we could do is pass the element to `map` and an `EmptyAnnotationMetadata` instance associated with it.

**Comment by graemerocher** [comment]
I don't think we are going to fix this, for cases where this is necessary and you need to inspect the element a `TypeElementVisitor` is better
