### ISSUE TITLE
Set-cookie on redirect

### ISSUE THREAD

**Issue by alexwilbur** [micronaut-projects/micronaut-core#2650]
### Task List

- [ X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Configure the micronaut HTTP client to follow redirects
2. Set a cookie as part of an HTTP Redirection response
3. The client will follow the redirect

### Expected Behaviour

The cookie that was set as part of the 302 redirect should be passed to the redirect endpoint

### Actual Behaviour

The cookie is ignored.

### Environment Information

- **Operating System**: Mac
- **Micronaut Version:** 1.2.8
- **JDK Version:** 8

### Example Application

Unfortunately do not have one at this point, but I can create if needed.

**Comment by jameskleeh** [comment]
@alexwilbur Do you have any references to other clients that operate this way? curl for example doesn't do what you're describing. It seems to be a big ask of a client to implement the security measures required in order to ensure cookie data doesn't get sent to where it shouldn't.

Edit: The Java http client (in Java 11+) also does not behave this way

**Comment by ghost** [comment]
No, I don't. You can close this. Agree it does not make sense to implement anything non-standard. Thanks!
