### ISSUE TITLE
All bean definitions are recreated during re-compilation

### ISSUE THREAD

**Issue by jbushdiecker** [micronaut-projects/micronaut-core#2922]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. On a Gradle project with micronaut-inject-java as an annotationProcessor, assemble the project
2. Make a simple change like changing the return of a method in a plain Java class
3. Use gradle assemble --debug to recompile

### Expected Behavior

Micronaut should not need to recreate bean definitions for classes that have not changed

### Actual Behavior

Micronaut recreates bean definitions for all annotated classes, regardless of whether they have changed

### Gradle Output

In the debug level Gradle output, org.gradle.internal.execution.impl.OutputsCleaner logs that it views all the Micronaut generated .class files as stale, and deletes them
```
2020-03-12T11:51:24.005-0500 [DEBUG] [org.gradle.internal.execution.impl.OutputsCleaner] Deleting stale output file 'C:\Users\jackson\IdeaProjects\annotationTest\build\classes\java\main\com\example\$Singleton1Definition.class'.
2020-03-12T11:51:24.006-0500 [DEBUG] [org.gradle.internal.execution.impl.OutputsCleaner] Deleting stale output file 'C:\Users\jackson\IdeaProjects\annotationTest\build\classes\java\main\com\example\$Singleton1DefinitionClass.class'.
2020-03-12T11:51:24.007-0500 [DEBUG] [org.gradle.internal.execution.impl.OutputsCleaner] Deleting stale output file 'C:\Users\jackson\IdeaProjects\annotationTest\build\classes\java\main\com\example\$Singleton2Definition.class'.
2020-03-12T11:51:24.008-0500 [DEBUG] [org.gradle.internal.execution.impl.OutputsCleaner] Deleting stale output file 'C:\Users\jackson\IdeaProjects\annotationTest\build\classes\java\main\com\example\$Singleton2DefinitionClass.class'.
2020-03-12T11:51:24.011-0500 [DEBUG] [org.gradle.internal.execution.impl.OutputsCleaner] Deleting stale output file 'C:\Users\jackson\IdeaProjects\annotationTest\build\classes\java\main\com\example\$Singleton3Definition.class'.
2020-03-12T11:51:24.011-0500 [DEBUG] [org.gradle.internal.execution.impl.OutputsCleaner] Deleting stale output file 'C:\Users\jackson\IdeaProjects\annotationTest\build\classes\java\main\com\example\$Singleton3DefinitionClass.class'.
2020-03-12T11:51:24.012-0500 [DEBUG] [org.gradle.internal.execution.impl.OutputsCleaner] Deleting stale output file 'C:\Users\jackson\IdeaProjects\annotationTest\build\classes\java\main\com\example\MyClass.class'.
2020-03-12T11:51:24.016-0500 [DEBUG] [org.gradle.internal.execution.impl.OutputsCleaner] Deleting stale output file 'C:\Users\jackson\IdeaProjects\annotationTest\build\classes\java\main\META-INF\services\io.micronaut.inject.BeanDefinitionReference'.
```

These deleted files are then regenerated by Micronaut

```
2020-03-12T11:51:24.450-0500 [ERROR] [system.err] Note: Creating bean classes for 3 type elements
```

### Environment Information

- **Operating System**: Windows 10 64-bit
- **Micronaut Version:** 1.3.3
- **JDK Version:** 1.8.0_201
- **Compiler Args:** -Amicronaut.processing.incremental=true

### Example Application

https://github.com/jbushdiecker/BeanDefinititionsDeletedExample

**Comment by croudet** [comment]
May be related to https://docs.micronaut.io/1.3.3/guide/index.html#incrementalannotationgradle

**Comment by cynic783** [comment]
From the bug report he is already using the micronaut.processing.incremental=true flag.
> Compiler Args: -Amicronaut.processing.incremental=true

**Comment by graemerocher** [comment]
@oehme Do you know what could be the cause of this one is?

As per #2718 we are feeding Gradle the correct information now.

**Comment by graemerocher** [comment]
Associated Gradle issue report https://github.com/gradle/gradle/issues/12150

**Comment by oehme** [comment]
Micronaut is defined as an aggregating processor, which means all annotated classes need to be reprocessesed, no matter what has changed (they are not recompiled though, just fed into the annotation processor again.). For more fine grained reprocessing, you'd need an isolating processor, which can only have a single originating element per output file.

**Comment by graemerocher** [comment]
So what would you suggest happen on the Micronaut side since isolating doesn’t fit our use case?

Is there a way to know that the classes fed back into the processor haven’t changed so that we don’t have to output what has already been output?

**Comment by oehme** [comment]
All your output files are deleted, so you have to recreate them. There's nothing you can do if isolating doesn't fit your use case. What you could think about is whether you have annotations that work in an isolating way and separate out a processor for these. Otherwise reprocessing all your annotated classes is the best we can do.

**Comment by graemerocher** [comment]
Why are these output files deleted though? Why is Gradle deleting them?

**Comment by oehme** [comment]
Because they are outdated - Your processor is aggregating, which means we must assume that any change to one of the annotated files (or any newly added file) could completely change the shape of the output.

**Comment by graemerocher** [comment]
Can’t even recall myself I think we discussed this as one point and decided on aggregating although it does seem like isolating fits our use case better. 

We do at times make decisions based on the presence of another type using elements.getTypeElement though

**Comment by oehme** [comment]
As long as that type is reachable from the signatures of the annotated element (e.g. a method return type, filed type etc.), that's still isolating. Aggregating is needed when you create things like registries or manifests that list all annotated elements.

**Comment by graemerocher** [comment]
This is a much bigger issue for us than previously thought. Part of Micronaut fits the isolating model since for each bean we generated 2 classes into the `build/classes/java/main` directory. So we can say in that case we are "isolating". 

However the same processor also generates a single `META-INF/services/io.micronaut.inject.BeanDefinitionReference` file containing a reference to 1 of the 2 classes generated. This fits your "aggregating" use case of service registries.

Splitting this up into 2 processors (1 isolating and 1 aggregating) would be 

1) inefficient as we would have to traverse the AST twice and keep that traversal consistent across both processors and 
2) complicated as somehow we would have to track that a class was actually generated by processor A to ensure processor B does not generate a missing class in the registry case

I am really unsure how to take this forward. @oehme any suggestions?

**Comment by graemerocher** [comment]
So I tried a quick spike of splitting our annotation processors so that the one that does the `META-INF/services` registry is `aggregating` and the one that does the generation of class files is `isolation` and it doesn't seem to solve the problem.

I see the following output:

```
2020-03-23T17:28:29.037+0100 [DEBUG] [org.gradle.internal.execution.impl.OutputsCleaner] Deleting stale output file '/Users/graemerocher/dev/micronaut/apps/BeanDefinititionsDeletedExample/build/classes/java/main/META-INF/services/io.micronaut.inject.BeanDefinitionReference'.
2020-03-23T17:28:29.038+0100 [DEBUG] [org.gradle.internal.execution.impl.OutputsCleaner] Deleting stale empty output directory '/Users/graemerocher/dev/micronaut/apps/BeanDefinititionsDeletedExample/build/classes/java/main/META-INF/services'.
2020-03-23T17:28:29.038+0100 [DEBUG] [org.gradle.internal.execution.impl.OutputsCleaner] Deleting stale empty output directory '/Users/graemerocher/dev/micronaut/apps/BeanDefinititionsDeletedExample/build/classes/java/main/META-INF'.
```

With no explanation as to why these are being deleted

**Comment by graemerocher** [comment]
Note that prior to this change I did receive a message saying that `META-INF/services/io.micronaut.inject.BeanDefinitionReference` was causing a rebuild because it was isolating and didn't have an original element. Now it is being generated in an aggregating processor and yet the problem is still there.

**Comment by graemerocher** [comment]
I have reported an associated Gradle issue to track this problem https://github.com/gradle/gradle/issues/12612

**Comment by oehme** [comment]
It's expected that the META-INF file would be deleted every time, since it could be affected by any changed or newly added file (any such change could add a new bean annotation). But the Beans themselves should not be deleted in that case. The Bean processor should be able to tell that they are already there. Note that it will still be invoked, since the classes are reprocessed to recreate the META-INF file and that means all processors will see them. If the bean classes are deleted too, that would be a bug in Gradle.

Regardless I think this is not worth the complexity on your side, since as you said it doubles the effort of traversing the AST. An alternative would be not to generate such a registry at all - I'm not sure what it is used for, but there are other injection frameworks like Dagger that are purely isolating. In Dagger for example, the user has to explicitly write "Module" classes that define which Beans they want to be available in their injector.

**Comment by oehme** [comment]
I think I've found why the isolating processor is invoked: The dependency analysis is very cautious and adds a dependency edge in [both directions](https://github.com/gradle/gradle/blob/c84e2be15b2d9a371528924b1d72c9a3935a08c9/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java#L49) - So if any output derived from some file is changed (e.g. a user messes with a generated file by hand), then all outputs of that file are considered outdated, no matter which processor created them.

**Comment by graemerocher** [comment]
We cannot change this now as it would be a massive breaking change. It would also hugely harm the user experience if users had to manually define modules. This file is used by Micronaut to discovery bean definitions on the classpath using the standard service loader pattern.

We have dozens of modules published and used already by users that uses this pattern so it is not something we can easily just switch away from.

In my latest change I found a way to avoid reprocessing the AST by using a hacky solution of setting a static property from the originall processor to another aggregating processor that writes the metadata. This is introduces less complexity, but because of this bidirectional dependency analysis as you said it doesn't fix the problem.

**Comment by oehme** [comment]
I understand that you probably can't change this anymore, but I'm afraid in that case you'll just have to live with all beans being re-processed, since that's the definition of an aggregating processor.

**Comment by graemerocher** [comment]
PR submitted https://github.com/micronaut-projects/micronaut-core/pull/3227

**Comment by oehme** [comment]
That's a clever solution. You're still reprocessing the same number of types, but writing only one output file. I'll keep that in mind for similar processors.
