### ISSUE TITLE
Specifying --test spock errors create-app in 2.0.0.M1

### ISSUE THREAD

**Issue by erichelgeson** [micronaut-projects/micronaut-core#2953]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

```
$ mn create-app myapp --test spock
```

### Expected Behaviour

Creates an app with spock testing framework

### Actual Behaviour

```
| Error Error occurred running Micronaut CLI: positional parameter at index 0..* (NAME) should be specified only once
```
### Environment Information

- **Operating System**: osx
- **Micronaut Version:** 2.0.0.M1
- **JDK Version:** 11

### Example Application

n/a

**Comment by graemerocher** [comment]
@remkop has something changed in PicoCLI? I don't really understand how this regression occurred. We have the following definition in `CreateAppCommand`:

```groovy
    @Parameters(arity = '0..1', paramLabel = 'NAME', description = 'The name of the application to create.')
    String appname = ""
```

It seems when we run the CLI it is trying to add the app name twice but only under certain circumstances (like the one above)

**Comment by remkop** [comment]
@graemerocher I see the same error with micronaut 1.3.2, so looks like this has been there for a while...

I was able to reproduce the error in both 1.3.2 and 2.0.0.M1. 
After the error message, the usage message of the `create-app` subcommand is printed. It is a bit long so I won't paste it here, but the problem is that there is no `--test` option defined for `create-app`.

Picocli then treats `--test` as an unmatched option, and `spock` as a positional argument, resulting in the slightly obscure error message "positional parameter at index 0..* (NAME) should be specified only once".

When running `mn create-app myapp --test=spock`, we get the clearer error message "Unknown option: '--test=spock'".

The solution is to add a `--test` option to the `create-app` command.

**Comment by graemerocher** [comment]
Interesting, seems like the correct syntax is `mn create-app myapp --features spock`. @erichelgeson did `--test spock` work before? I am not sure it did

**Comment by erichelgeson** [comment]
I'm not sure if it worked before, only tried in 2.0.0.M1 - I was just putting together features and languages from the docs to create an app - I boiled it down to this command that still gave the error, though my original command was:
```
mn create-app myapp --features=jetty-server,hibernate-gorm,management,http-client,jdbc-hikari --lang groovy --test spock
```
Which would seem to be to be valid based off the docs.

**Comment by remkop** [comment]
This command seems to work:

```
mn create-app myapp --features=jetty-server,hibernate-gorm,management,http-client,jdbc-hikari,spock --lang groovy
```

@erichelgeson  Can you point to the misleading docs? I had a quick look but couldn't find it.
https://docs.micronaut.io/latest/guide/index.html#createProject shows that `create-app` does not have a `--test` option. However, the next command, `create-cli-app`, *does* have a `--test` option, I can imagine this may cause some confusion...

**Comment by erichelgeson** [comment]
That was the confusion - I assumed create-app/create-cli-app/create-function/etc all had the same base, eg defining lang/test/features i wanted for what I was creating.
