### ISSUE TITLE
[Feature Request] Parse `set-cookie` response headers into Cookies

### ISSUE THREAD

**Issue by eahrold** [micronaut-projects/micronaut-core#3082]
Currently it's possible to get the `set-cookie` headers as a `List<String>`

```
HttpHeaders headers = response.getHeaders();
List<String> cookies = headers.getAll(HttpHeaderNames.SET_COOKIE)
```

But then in order to add those to subsequent requests, they must be converted into `io.micronaut.http.cookie.Cookie`

It would be nice to have a `response.getCookies()` that returns `Set<Cookie>` ready for use in follow-up requests.

**Comment by koziolk** [comment]
@graemerocher I would like to work on it.

**Comment by graemerocher** [comment]
Sounds good!

**Comment by jantosi** [comment]
Hi, @graemerocher, this has been sitting for a while - if @koziolk (:wave:) doesn't mind, I'd like to contribute. So far, I have a simple PoC parser that returns a cookie name, value, and an instance `io.micronaut.http.cookie.CookieConfiguration` - which can be plugged directly to `io.micronaut.http.simple.cookies.SimpleCookie` I think.

Should I assign this issue to myself?

**Comment by graemerocher** [comment]
Absolutely PRs welcome!

**Comment by jantosi** [comment]
Opened a PR, https://github.com/micronaut-projects/micronaut-core/pull/3883 - let me know what you think, @graemerocher. It felt natural to add `getCookies()` as a method of HttpMessage, as many of its implementing classes already have such a method, but I'm happy to talk about what might be needed here.

**Comment by mjalvarez** [comment]
Hi guys, I just ran into this issue where a service returns this header `Set-Cookie: xyz_adm_adm_org_user_time_zone_id=Singapore Standard Time; expires=Wed, 09-Jun-2021 08:00:06 GMT; path=/` 

Using this client:
```
RxHttpClient client = new DefaultHttpClient(new URL('https://another.service.url.com/oauth/signin'), configuration)
Flowable<HttpResponse<TokenResponse>> responseFlowable = client.exchange(request, Argument.of(TokenResponse))
```

`FullNettyClientHttpResponse` receives a `NullPointerException` from `NettyCookies` since it decodes in STRICT mode and fails the cookie value "Singapore Standard Time" because of the whitespaces, then logs a warning:

```
An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException: null
        at io.micronaut.http.netty.cookies.NettyCookies.<init>(NettyCookies.java:78)
        at io.micronaut.http.client.netty.FullNettyClientHttpResponse.<init>(FullNettyClientHttpResponse.java:99)
        at io.micronaut.http.client.netty.DefaultHttpClient$12.channelReadInstrumented(DefaultHttpClient.java:2204)
        at io.micronaut.http.client.netty.DefaultHttpClient$12.channelReadInstrumented(DefaultHttpClient.java:2076)
```
...and then the client finally times out:

```
ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Read Timeout
io.micronaut.http.client.exceptions.ReadTimeoutException: Read Timeout
        at io.micronaut.http.client.exceptions.ReadTimeoutException.<clinit>(ReadTimeoutException.java:26)
        at io.micronaut.http.client.netty.DefaultHttpClient.lambda$null$36(DefaultHttpClient.java:1178)
```

---

I'm wondering if 

- There is a way to handle this gracefully and still capture the response while ignoring the invalid cookie headers, and I just don't know it yet
- This a known issue that will be fixed in the next release, otherwise file a separate issue
