### ISSUE TITLE
Deadlock while trying to send event from another thread inside @PostConstruct

### ISSUE THREAD

**Issue by Im-dex** [micronaut-projects/micronaut-core#3124]
Micronaut version: 1.3.4

It seems that micronaut stuck in deadlock at DefaultBeanContext:2588 when you trying to do some asynchronous work in @PostConstruct which leads to event sending. 

https://github.com/Im-dex/micronaut-deadlock

**Comment by graemerocher** [comment]
This is probably #3070

Thanks for the reproducer, will take a look

**Comment by graemerocher** [comment]
Added a `publishEventAsync` method which will solve your use case

**Comment by Im-dex** [comment]
@graemerocher The issue is a little bit more complex than just sending events from user code. I have found out this issue while calling declarative http client (annotated with @Retryable) within @PostConstruct method. When retry happens it is trying to send event and stuck in a deadlock. I think that micronaut itself could contain a lot of code sending events in a synchronous manner and this fix does nothing with that.

**Comment by graemerocher** [comment]
Whilst I agree, unfortunately great care needs to be taken when it comes to using `@PostConstruct` and resolving beans at the same time because when `@PostConstruct` is invoked the bean is currently in the middle of being created and is holding a lock on the bean registry until it is created to make sure that it is impossible to create duplicate singletons.

If users have complex logic within a `@PostConstruct` then I would recommend ensuring the beans involved in that method are annotated with `@Context` to ensure they are initialized prior  to `@PostConstruct` being called.

Alternatively in Micronaut 2.x you can consider using the eager initialization features.
