### ISSUE TITLE
Model is null when using freemarker view inside grall vm

### ISSUE THREAD

**Issue by pohorelec** [micronaut-projects/micronaut-core#3441]
Micronaut throws 'The following has evaluated to null or missing:' exception in graalvm image when using freemarker view renderer. It throws on line when I try to get any property from model object.

I tried to add this:

`--initialize-at-run-time=io.micronaut.views.freemarker.$FreemarkerViewsRendererConfigurationPropertiesDefinition,io.micronaut.views.freemarker.FreemarkerViewsRenderer`

when building native image but result was same.

If I run code outside grallvm everything works fine.

Micronaut version: 1.3.5 (also tried 1.3.6 with same result)

**Comment by ilopmar** [comment]
Have you declared the templates as graalvm resources? You probably need something like this: https://github.com/micronaut-graal-tests/micronaut-views-graal/blob/1.3.x_freemarker/src/main/resources/META-INF/native-image/example.micronaut/views-graal-application/native-image.properties#L1

Also please take a look at that test application because it works with GraalVM. Here we pass a model to the view: https://github.com/micronaut-graal-tests/micronaut-views-graal/blob/1.3.x_freemarker/src/main/java/example/micronaut/ViewsController.java#L20

**Comment by pohorelec** [comment]
Thank you for the tip.. 

I found out that I was missing @Introspected annotation for model objects.

Now it works as a charm :)

**Comment by ilopmar** [comment]
Glad it works now :-)
