### ISSUE TITLE
@Singleton Bean created twice 

### ISSUE THREAD

**Issue by rafaelrasso** [micronaut-projects/micronaut-core#3615]
### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

The Steps are in README.md of my [Demo](https://github.com/rafaelrasso/demo-micronaut-singleton-problem)

### Expected Behaviour

Create only one instance of @Singleton class.

### Actual Behaviour

Two instances are being created when the health check is performed before the exception handler

### Environment Information

- **Operating System:** Mac OS X 10.15.5
- **Micronaut Version:** 2.0.0
- **JDK Version:** OpenJDK 11.0.7

### Example Application

- [Demo](https://github.com/rafaelrasso/demo-micronaut-singleton-problem)

**Comment by kbachl** [comment]
Is there any workaround for this available?

**Comment by olejnikk** [comment]
As a workaround, you can split `HealthIndicator` and `ExceptionHandler` into two separate singletons. `ExceptionHandler` would modify the state of `HealthIndicator`.

I've done some debug in this area because it looks like a quite serious issue. That's the results for the fail case:
- health check call leads to first `DemoHealth` instance creation, that is ok
- after `BeanContextException` is thrown, Micronaut tries to find bean matching `ExceptionHandler<BeanContextException, HttpResponse<Object>>`
- in `DefaultBeanContext::getBeanInternal` right concrete candidate is found  (`DemoHealth` bean definition)
- method `findExistingCompatibleSingleton` does not return existing `DemoHealth` instance what leads to `getBeanForDefinition` and new instance as a result

What happens with `findExistingCompatibleSingleton` inside `DefaultBeanContext::getBeanInternal`:
- we're trying to find a bean of exact type as a bean definition `DemoHealth` but with type qualifier which requires matching with ExceptionHandler type arguments - `<BeanContextException, Object>`: `bean = findExistingCompatibleSingleton(definition.getBeanType(), qualifier, definition);`. That bean would never be found since `DemoHealth` has no type arguments. We can't look for bean with `beanType` (`ExceptionHandler`) because we may find some existing bean instead of the best matching candidate which has not been initialized and registered yet
- there is no try to find bean by `beanType` - it only happens when no concrete candidate is found

I opened PR with unit test and solution proposition. It's not a perfect solution as I'm new to core internals, but it might highlight the problem. In `ClosestTypeArgumentQualifier` I score each type of `beanType` class hierarchy against each candidate, not just strictly the given type.
