### ISSUE TITLE
Review the impact of bean definition change on function support

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#3707]
Regarding https://github.com/micronaut-projects/micronaut-core/commit/b84d722badc09a55914d05dab21b8f967f59b3f2

I believe this may also completely break our current function support.

For example https://github.com/micronaut-projects/micronaut-azure/blob/master/doc-examples/example-java/src/test/java/example/BlobFunction.java#L8

Which subclasses a parent class and just uses `@Inject`

My current feeling is we may need to roll back this change and make sure it only applies to `abstract` classes

**Comment by graemerocher** [comment]
Looks like we at least need to update the templates in Micronaut Launch https://github.com/micronaut-projects/micronaut-starter/blob/master/starter-core/src/main/java/io/micronaut/starter/feature/function/azure/template/raw/azureRawFunctionTriggerJava.rocker.raw#L18

**Comment by jameskleeh** [comment]
@graemerocher I don't think the change will break this because at least in the case of azure, the class isn't a bean.

https://github.com/micronaut-projects/micronaut-azure/blob/bbc32e3f08a6e453747557a1997a394e5a94d1d3/azure-function/src/main/java/io/micronaut/azure/function/AzureFunction.java#L49

It's simply injected from the context. 

For GCP, the standard FunctionInitializer is used which registers the instance as a singleton manually and optionally injects it https://github.com/micronaut-projects/micronaut-core/blob/master/function/src/main/java/io/micronaut/function/executor/FunctionInitializer.java#L47
