### ISSUE TITLE
`RecoveryInterceptor` should be applied only on `@Recoverable` in the next major version

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-core#3719]
At the moment `@Fallback` can be used without  `@Recoverable` on the class.

https://github.com/micronaut-projects/micronaut-core/pull/3711

**Comment by jameskleeh** [comment]
@dstepanov That is because `@Client` itself is annotated with `@Recoverable`. See https://github.com/micronaut-projects/micronaut-core/blob/7d2c721cd429dedeedfde3a13076b72714ae4c17/http-client-core/src/main/java/io/micronaut/http/client/annotation/Client.java#L43. If you are proposing that clients should not be recoverable by default, what is the reasoning?

**Comment by dstepanov** [comment]
@jameskleeh I have mistakenly assumed `RecoveryInterceptor` is applied everywhere by default, but it looks like it was only for `@Client`'s, it's not that bad then.
Maybe in the next major version it can be removed so there is no extra call to resolve the fallback if you don't need it.
