### ISSUE TITLE
RequestBean does not bind Principal or Authentication

### ISSUE THREAD

**Issue by volnei** [micronaut-projects/micronaut-core#3869]
As discussed on Gitter, the @RequestBean annotated bean was not binding the Principal or Authentication instances. HttpRequest was binded succesfully.

### Steps to Reproduce

Try to bind the Principal or Authentication beans to an @RequestBean annotated parameter bean on an controller method, using ```@Get()```

Bean
```java
package user.api;

import java.security.Principal;

import io.micronaut.core.annotation.Introspected;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Introspected
public class GetMeRequest {

    private Principal principal;

}
```

Controller
```java
    @Get("/me")
    public Maybe<GetMeResponse> me(@RequestBean GetMeRequest request) {
        // ... 
    }   
```
I've tried using template portion on url too, same problem.
```java
    @Get("/me{?request*}")
    public Maybe<GetMeResponse> me(@RequestBean GetMeRequest request) {
        // ... 
    }   
```

### Expected Behaviour

The principal must be binded with current authenticated user.

### Actual Behaviour

Returns an error

```
Required argument [Principal principal] not specified
```
### Environment Information

- **Operating System**: MacOS Big Sur 
- **Micronaut Version:** 2.0.0
- **JDK Version:** 11

**Comment by asodja** [comment]
There is also test that typed value is injected that uses Principal, so this should work: [RequestBeanSpec](https://github.com/micronaut-projects/micronaut-core/blob/8fdb9010e1753af34aece11a9dc1c58539f3cf3e/http-client/src/test/groovy/io/micronaut/http/client/aop/RequestBeanSpec.groovy#L250). 

Does it work if you use `Optional<Principal>` or annotate it with `@Nullable`?

**Comment by volnei** [comment]
Still not working even with Optional or Nullable. I saw the tests but none of them mention the javax.security.Principal class.

Using Optional, a "No value present" error is reached.

**Comment by asodja** [comment]
I dig into this a bit and it is a bug. The issue is that binding of `@RequestBean` happens before filters and Authentication is not set at that time. To workaround this you can implement your own Principal or Authentication that is lazy, i.e. values from HttpRequest are taken only when needed in request method. Example for Principal:
```
@Singleton
@Replaces(PrincipalArgumentBinder.class)
public static class LazyPrincipalArgumentBinder implements TypedRequestArgumentBinder<Principal> {
    @Override
    public Argument<Principal> argumentType() {
        return Argument.of(Principal.class);
    }
    @Override
    public BindingResult<Principal> bind(ArgumentConversionContext<Principal> context, HttpRequest<?> source) {
        return () -> Optional.of(new LazyPrincipal(source));
    }
}

public static class LazyPrincipal implements Principal {
    private HttpRequest<?> source;
    public LazyPrincipal(HttpRequest<?> source) {
        this.source = source;
    }
    @Override
    public String getName() {
        Optional<Principal> principal = source.getUserPrincipal();
        return principal.map(Principal::getName).orElse(null);
    }
}
```
A side effect of that is, that you'll never have null or Optional Principal (but that can be seen as a feature). Similar can be done for `Authentication` type, implement Authentication interface and binder. You can get Micronaut implementation out of HttpRequest with `source.getUserPrincipal(Authentication.class)`. 

**Note:** I am not sure what Micronaut does with Principal, my guess is that nothing special. But if you want to be 100% on a safe side, you can bind your type directly and avoid `@Replaces(PrincipalArgumentBinder.class)`. Just use `LazyPrincipal` in bean, set binder argumentType to `Argument.of(LazyPrincipal.class)` and remove `@Replaces(PrincipalArgumentBinder.class)`.
