### ISSUE TITLE
cntrl + c is not doing graceful shutdown.

### ISSUE THREAD

**Issue by Sai-Bhargavi** [micronaut-projects/micronaut-core#4056]
We have an application where we are using shutdown tasks(with some logs) in @PreDestroy and with cntl+c, we don't see any logs of shutdown logic getting printed.

We have observed the same issue with the "docker stop <container-id>" command.

Sample Application:
https://github.com/Sai-Bhargavi/SampleApp

Steps to Reproduce:
Start the application using ./gradlew run
When the application is up and running do "cntl+c"

Expected Behavior :
cntl+c does a graceful shutdown, thereby we should be able to see the logs of shutdown logic in @PreDestroy

Actual Behavior :
With cntl+c, it is directly exiting the terminal, thereby we are unable to see the logs of shutdown logic.

We have tried the following commands:
kill --INT <process-id>
kill --TERM <process-id>
and in both cases, we are able to see the logs of shutdown logic(which is written under @PreDestroy)

Environment Information
- Operating System: Linux
- Micronaut Version: 2.0.1
- JDK Version: 8

**Comment by graemerocher** [comment]
Whilst I can reproduce this with `./gradlew run` (maybe that is a hard kill?) I cannot reproduce this when doing `java -jar app.jar` and see output printed for `@PreDestroy` events.

The most likely reason is Gradle is sending a kill event which is terminating the process and not allowing shutdown hooks to run. Shutting down the context in this manner relies on the use of shutdown hooks https://www.baeldung.com/jvm-shutdown-hooks which is what Micronaut registers

I don't think there is anything specific we can do to address your problem beyond what the framework already does.

**Comment by graemerocher** [comment]
In addition, I cannot reproduce from Docker either. Doing the following steps:

```
mn create-app shutdown-test
cd shutdown-test
```

Add  to a bean

```java
   @PreDestroy
    void shutdown() {
        System.out.println("SHUTTING DOWN!");
    }
```

Then:

```
docker build . -t shutdown-test
docker run shutdown-test
CTRL+C
```

Results in 

```
^C09:47:59.229 [Thread-0] INFO  io.micronaut.runtime.Micronaut - Embedded Application shutting down
SHUTTING DOWN!
```

**Comment by croudet** [comment]
You have to run it without the daemon: `gradle run --no-daemon...`

**Comment by ALSowjanya** [comment]
@graemerocher In the above application, we have not provided the micronaut.host details in the application.yaml. If we set the host as localhost. We are able to reproduce the issue. Even with the jar, we dont see that shutdown events are triggered. It is basically because https://github.com/micronaut-projects/micronaut-core/blob/2.0.x/runtime/src/main/java/io/micronaut/runtime/Micronaut.java#L109 returns false, since we get connection refused exception when we try to connect to socket. 
When we dont provide host in application.yml it is working as expected. Is there any prerequisite for values of host. Is localhost not a valid value.
I have updated the same project for reproducible project(https://github.com/Sai-Bhargavi/SampleApp).

**Comment by Sai-Bhargavi** [comment]
Hi @graemerocher can you please reopen this issue. As we have producible environment now.

**Comment by graemerocher** [comment]
sure

**Comment by Sai-Bhargavi** [comment]
@graemerocher Do we have any update on this?
