### ISSUE TITLE
Cannot build app when lib and app depend on two different Micronaut versions.

### ISSUE THREAD

**Issue by oscarfh** [micronaut-projects/micronaut-core#4150]
I am trying to create a lib that depends on Micronaut that should provide some common features to the apps inside my company.
It works perfectly when the lib and the app have the same micronaut version, but the build fails when they differ (example: lib 2.0.0 and app 2.0.1) with the following message:
```
Could not determine the dependencies of task ':app:shadowJar'.
> Could not resolve all dependencies for configuration ':app:runtimeClasspath'.
   > Could not resolve io.micronaut:micronaut-bom:2.0.0.
     Required by:
         project :app > com.acme:lib:0.0.1-SNAPSHOT
      > No matching variant of io.micronaut:micronaut-bom:2.0.2 was found. The consumer was configured to find a runtime of a library compatible with Java 11, packaged as a jar, and its dependencies declared externally but:
          - Variant 'apiElements' capability io.micronaut:micronaut-bom:2.0.2:
              - Incompatible because this component declares an API of a platform and the consumer needed a runtime of a library
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them packaged as a jar)
          - Variant 'enforcedApiElements' capability io.micronaut:micronaut-bom-derived-enforced-platform:2.0.2:
              - Incompatible because this component declares an API of an enforced platform and the consumer needed a runtime of a library
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them packaged as a jar)
          - Variant 'enforcedRuntimeElements' capability io.micronaut:micronaut-bom-derived-enforced-platform:2.0.2 declares a runtime of a component:
              - Incompatible because this component declares an enforced platform and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them packaged as a jar)
          - Variant 'runtimeElements' capability io.micronaut:micronaut-bom:2.0.2 declares a runtime of a component:
              - Incompatible because this component declares a platform and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them packaged as a jar)
```

clarification: both lib and app depend on micronaut-bom.

Project to reproduce: https://github.com/oscarfh/mn-dependency

Steps to reproduce:
- checkout the project
- Uncomment `implementation project(":lib")`and comment `implementation "com.acme:lib:0.0.1-SNAPSHOT"` out
- run ./gradlew build

It will build successfully.

Now,
- Uncomment `implementation "com.acme:lib:0.0.1-SNAPSHOT"` and comment `implementation project(":lib")` out
- Install the lib using `./gradlew :lib:install`
- run `./gradlew build`

you will get the error shown above.

**Comment by dmagOM** [comment]
@oscarfh I'm not sure if you've managed to resolve this already yourself, but I was experiencing a similar problem in my own project and made some progress with it. 

The issue is effectively that more recent Micronaut versions (>= 2.0.1) publish a Gradle `module` file alongside the rest of the Maven metadata, which defines a set of Gradle variants. When you build your library it successfully takes this into account, but the `maven` plugin you're using _does not_. 

When you then attempt to use the library you've generated in your subsequent application, Gradle retrieves the module file from Micronaut and attempts to match the variants defined in it to the requirements in your lib's `.pom`. It can't reconcile the two, so the build fails. 

I checked your sample project, and can resolve the issue by changing the `maven` plugin to `maven-publish`, and adding something along the lines of: 

```
  publishing {
      publications {
          mavenJava(MavenPublication) {
              from components.java
              versionMapping {
                  usage('java-api') {
                      fromResolutionOf('runtimeClasspath')
                  }
                  usage('java-runtime') {
                      fromResolutionResult()
                  }
              }
          }
      }
 }
```

You can then run: `./gradlew :lib:publishToMavenLocal` (in place of your `:lib:install` command above). You can check the Maven cache and you'll see both the new `module` file and the updated `pom` file, both of which contain the more detailed dependency information required to allow your application to be built successfully via `./gradlew build` (you can also test removing the `module` file completely from the cache and rebuilding to see that it still resolves correctly). 

Let me know if that makes sense.

**Comment by graemerocher** [comment]
@dmagOM Thanks for taking the time to answer, looks like the correct thing to do. I believe the `maven` plugin is scheduled to be removed

**Comment by oscarfh** [comment]
Thanks a lot @dmagOM  ! ~I will try that!~ Works like a charm!
