### ISSUE TITLE
ReadTimeoutException during Spock Test

### ISSUE THREAD

**Issue by mattmoss** [micronaut-projects/micronaut-core#426]
### Steps to Reproduce

1. git checkout endpoint-loggers
2. ./gradlew management:test
3. Observe test: _test that an attempt to set ROOT logger to NOT_SPECIFIED level will fail_

### Expected Behaviour

The test should pass. In particular, the test should pass by receiving a `HttpClientResponseException` with status code BAD_REQUEST.

### Actual Behaviour

The test receives a `io.micronaut.http.client.exceptions.ReadTimeoutException`.

### Additional Notes

This seems to be an issue with the http client in context of the Spock test. A test application built against the BUILD-SNAPSHOT, and queried using curl, will return immediately with the expected results.

**Comment by graemerocher** [comment]
The fix resolves the timeout exception, although the test still fails.

The actual root cause is that your code was sending a string back https://github.com/micronaut-projects/micronaut-core/blob/endpoint-loggers/management/src/main/java/io/micronaut/management/endpoint/loggers/LoggersEndpoint.java#L104 when the response content type was `application/json`

If you send a string back you should set the response content type to `text/plain`. Otherwise send a `JsonError` instead.

**Comment by wafag** [comment]
I have the same eurreur using Junit !
