### ISSUE TITLE
Bean validation should fail if @Valid field is not introspected

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-core#4306]
2.1.0

If you are using `@Valid` on the body parameter there is a runtime error if the field type is not `@Introspected` (BTW: It would be great have compile-time error but I guess that wouldn't be correct for Hibernate validator)
That is not the case if you have a nested field with a type without introspection, the field is not validated and you are wondering was is wrong.

**Comment by jameskleeh** [comment]
@dstepanov Are you going to be submitting a PR? If not, can you upload an example app?

**Comment by dstepanov** [comment]
I haven't looked into it. The example is a simple case of:

```
@Introspected
class A {
   @Valid
   private List<B> bees;
   ...
}

// Not introspected
class B {
   @NotNull
   private String name;
   ...
}

@Post 
void submit(@Body @Valid A body) { ... }

`{"bees": {}}` is OK if `B` is not introspected

```

**Comment by jeffscottbrown** [comment]
> Bean validation should fail if @Valid field is not introspected

Should that be the requirement or should the requirement be that validation should work even if the class is not marked introspected?

**Comment by dstepanov** [comment]
An exception is thrown if `@Body` object class is not introspected it should also fail if nested objects aren't introspected and you requested them to be validated by `@Valid` annotation.

**Comment by dstepanov** [comment]
@wetted Are you working on it?

**Comment by wetted** [comment]
@dstepanov among other things, yes, so that non-introspected nested objects will fail the `@Valid` validation.

**Comment by dstepanov** [comment]
I have come up with this fix https://github.com/micronaut-projects/micronaut-core/pull/4405

**Comment by wetted** [comment]
I submitted [PR 4411](https://github.com/micronaut-projects/micronaut-core/pull/4411) for the basic case where just the @Valid annotation is on a container, where the container element type is not introspected. That fixes this case. 

However, it doesn't address bogus cases like `@Valid @SomeConstraint List<Foo> foosNotInstrospected` where `@SomeConstraint` doesn't support `Foo` directly. This is a bit more complicated since something like `@Valid @Size(min=1, max=2) List<String> strs` is perfectly valid, even though String isn't introspected. The fix is not so straightforward since any number of constraints are legitimate with @Valid on a container, as long as the container element type is a supported type for all the constraints. This needs to accommodate not only built-in constraints, but custom ones as well.
