### ISSUE TITLE
AnnotationMetadata.getAnnotationType(@Nonnull String name) do not use correct class loader

### ISSUE THREAD

**Issue by puneetbehl** [micronaut-projects/micronaut-core#4396]
This happens in the development environment with reloading in a Grails 4 application which creates a MethodInterceptor to set an attribute on the MethodInvocationContext and the problem happens because the `@io.micronaut.context.annotation.Type` value on custom annotation resolves the value from a different classloader [here](https://github.com/micronaut-projects/micronaut-core/blob/1.3.x/aop/src/main/java/io/micronaut/aop/chain/InterceptorChain.java#L300) while calling `InterceptorChain.resolveIntroductionInterceptors(beanContext,  method, ... interceptors)`

See grails/grails-core#11531 for more details. 

We probably need to add an additional method getAnnotationType(name, classloader) which also takes classloader as another argument. 

I will be sending a PR to Micronaut 2.1 regarding the same and this would be fixed in Grails 4.1.0.

**Comment by puneetbehl** [comment]
@jameskleeh Added a ticket to track this, please let me know if this makes sense.

**Comment by ilopmar** [comment]
I've been trying to debug this adding some `println`s to the different methods added in the related PR (#4406).

The problem is here https://github.com/micronaut-projects/micronaut-core/commit/0389f4d17a0f9ce6e9820e1941848166e3e9ea53#diff-80669c773e631d78f31f0b8c756e516df7388c4a8c03023cd04eea8a6c8080acR283.  
That code calls the new [default method `getAnnotationTypesByStereotype`](https://github.com/micronaut-projects/micronaut-core/commit/0389f4d17a0f9ce6e9820e1941848166e3e9ea53#diff-4afc5808da3bc4cbe273e24b5f36b417509f2e6acfeedccb53ac8c1fdc860a38R342-R344) added to `AnnotationMetadataDelegate` interface.
That call returns an empty list and the execution fails. The previous version of the code without the `classLoader` returns `[interface io.micronaut.http.client.annotation.Client]` and everything works.

[Graeme suggested here](https://github.com/micronaut-projects/micronaut-core/issues/4425#issuecomment-721670881) that we need to implement `default Optional<Class<? extends Annotation>> getAnnotationType(@NonNull String name, @NonNull ClassLoader classLoader)` in `DefaultAnnotationMetadata`, but as mentioned there, that new method is not called.

The following code in `InterceptorChain` makes it work again but I'm not sure if it's a hack, a workaround or the actual fix.

```java
private static Interceptor[] resolveInterceptorsInternal(ExecutableMethod<?, ?> method, Class<? extends Annotation> annotationType, Interceptor[] interceptors, ClassLoader classLoader) {
    List<Class<? extends Annotation>> annotations = method.getAnnotationTypesByStereotype(annotationType, classLoader);
    if (annotations.isEmpty()) {
        annotations = method.getAnnotationTypesByStereotype(annotationType);
    }
    ....
```

Maybe we need to implement the new method in some other class, but there are many classes that implement `AnnotationMetadata` and `AnnotationMetadataDelegate` so I'm not sure which one could fix this.
