### ISSUE TITLE
Wrong JSON generated from reactive controller

### ISSUE THREAD

**Issue by zinoviy23** [micronaut-projects/micronaut-core#4664]
### Steps to Reproduce

1. Create reactive controller
```java
package com.example;

import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import reactor.core.publisher.Flux;

@Controller("reactive")
public class ReactiveController {
    @Get(produces = MediaType.APPLICATION_JSON)
    Flux<String> many() {
        return Flux.just("aaa", "bbb", "ccc");
    }
}
```
2. Run app and check `/reactive` endpoint. It returns 

### Expected Behaviour
Endpoint returns:
```json
[
  "aaa",
  "bbb",
  "ccc"
]
```
like corresponding enpoint:
```java
import io.micronaut.http.MediaType;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;

import java.util.Arrays;
import java.util.List;

@Controller("/imperative")
public class ImperativeController {
    @Get(produces = MediaType.APPLICATION_JSON)
    List<String> many() {
        return Arrays.asList("aaa", "bbb", "ccc");
    }
}
```

### Actual Behaviour
It returns
```json
[
  aaa,
  bbb,
  ccc
]
```
which is invalid JSON.

### Environment Information

- **Operating System**: macOS Big Sur 11.0.1
- **Micronaut Version:** 2.2.0
- **JDK Version:** 11

**Comment by jameskleeh** [comment]
@zinoviy23 We make the assumption that if a string is returned then it has already been converted to JSON. We wouldn't be able to determine the difference between returning a JSON string and just a regular string. The non flowable version works because a list is returned and the entire list is encoded at once. If you changed the signature to be `Flowable<List<String>` that would work as well.
