### ISSUE TITLE
Allow custom HTTP response status codes

### ISSUE THREAD

**Issue by debuglevel** [micronaut-projects/micronaut-core#4791]
### Steps to Reproduce
`HttpResponse.ok().status(599)`

### Expected Behaviour
Some REST services may use custom HTTP status codes to indicate specific states. Let's say `599 Sorry, still processing your request check again in some minutes` or something like that.

Although that's probably quite a bad practise to use custom HTTP status codes, there are legacy services which use them. If somebody wants to migrate such a service to Micronaut, he cannot fulfill the REST API and must change the REST API and their clients first.

I'd totally understand if you do not want to support this, and I'd be fine with that ;-). I just stumbled across such a service and it gave me some headache during migration.

### Actual Behaviour
`HttpResponse.ok().status(599)` throws an Exception, as no such pre-defined HTTP status code is found.

### Environment Information
- **Micronaut Version:** 2.1
- **JDK Version:** 1.8

**Comment by utsav0209** [comment]
@graemerocher [HttpStatus](https://github.com/utsav0209/micronaut-core/blob/b5cc40ea85d020d875f5a95e570188d4a47890a1/http/src/main/java/io/micronaut/http/HttpStatus.java) is an ENUM, how do we allow this then?

**Comment by graemerocher** [comment]
would have to be an internal implementation of for example `NettyHttpResponseFactory`

**Comment by utsav0209** [comment]
@graemerocher, you mean to say that we should create a new `CustomerHttpresponseFactory` for this just the way we have `NettyHttpResponseFactory`?

**Comment by graemerocher** [comment]
Currently there are only methods variants that take the enum:

https://github.com/micronaut-projects/micronaut-core/blob/a237e29cf0baf2628a51c2e20d265bfb1f003b0e/http/src/main/java/io/micronaut/http/HttpResponseFactory.java#L48

We would need to add new methods like:

```java
   /**
     * Return a response for the given status.
     *
     * @param status The status code
     * @param reason An alternatively reason message
     * @param <T>    The response type
     * @return The response
     */
    default <T> MutableHttpResponse<T> status(int statusCode, String reason) {
            return status(HttpStatus.valueOf(statusCode), reason);
    }
```

And then implement these in `NettyHttpResponseFactory` by overriding the method to produce the underlying Netty status object

**Comment by utsav0209** [comment]
@graemerocher  If we add a default method as you suggested above, and override it like: 
```java
    @Override
    public MutableHttpResponse status(int statusCode, String reason) {
        HttpResponseStatus nettyStatus = new HttpResponseStatus(statusCode, reason);
        DefaultFullHttpResponse fullHttpResponse = new DefaultFullHttpResponse(HttpVersion.HTTP_1_1, nettyStatus);
        return new NettyMutableHttpResponse(fullHttpResponse, ConversionService.SHARED);
    }
```

this works I think, but as I see there is this method inside `NettyMutableHttpResponse`:
```java
    @Override
    public HttpStatus getStatus() {
        return HttpStatus.valueOf(nettyResponse.status().code());
    }
```

And this method is being overridden from `HttpResponse` interface. I am not sure if I am correct or not but I think wherever we are using this, it will break for custom response codes. What should we do about it?

**Comment by hernancerm** [comment]
Hi, @graemerocher I would like to take this issue

**Comment by hernancerm** [comment]
@graemerocher I ran into the same problem that @utsav0209 mentions about the `getStatus()` implementation of `NettyMutableHttpResponse`.

In order to be able to provide custom Http statuses, I considered refactoring the enum [`HttpStatus`](https://github.com/micronaut-projects/micronaut-core/blob/2.5.x/http/src/main/java/io/micronaut/http/HttpStatus.java) to an interface as well as to a class. Although both approaches seem to work, they both have one problem: the annotation [@Status](https://github.com/micronaut-projects/micronaut-core/blob/2.5.x/http/src/main/java/io/micronaut/http/annotation/Status.java) doesn't work, because according to the [JSL](https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.6.1), annotations don't allow an interface or a class as a member type.

Thus, to keep `@Status` working, I think it is necessary to keep `HttpStatus` as an enum, although there might be some possible refactoring I am not seeing.

I have a [draft PR open](https://github.com/micronaut-projects/micronaut-core/pull/5621) about my current implementation to allow the enum to hold a custom status. According to my manual checking, it works well with the `NettyHttpResponseFactory`.

Regarding the API, I am considering the following on `HttpResponse`:

```java
/**
  * Return a response for the given status, optionally a non-standard status.
  *
  * @param statusCode The status code
  * @param reason An alternatively reason message
  * @param <T>    The response type
  * @return The response
  */
static <T> MutableHttpResponse<T> status(int statusCode, String reason) {
    return HttpResponseFactory.INSTANCE.status(statusCode, reason);
}

/**
  * Return a response for the given status, optionally a non-standard status.
  *
  * @param statusCode The status code
  * @param <T>    The response type
  * @return The response
  */
static <T> MutableHttpResponse<T> status(int statusCode) {
    return HttpResponseFactory.INSTANCE.status(statusCode);
}
```

Caveats about my approach:

- I haven't checked if my implementation works for the other implementations of `HttpResponseFactory`, beyond `NettyHttpResponseFactory`.
- I removed `final`  from the attributes `code` and `reason` in `HttpStatus`, to allow setting a custom enum value.
- Some tests are failing. I wanted to post my approach before going in to fix the tests.

I would appreciate to know if I am in the right track with this approach

**Comment by graemerocher** [comment]
Looks ok to me, but maybe should target 3.0.x branch

**Comment by hernancerm** [comment]
@graemerocher I'll target branch 3.0.x instead

Regarding compatibility, **should custom response status codes also be possible on other [Micronaut runtimes](https://github.com/micronaut-projects/micronaut-gradle-plugin#micronaut-runtimes) beyond Netty?**

So far I've tried on `tomcat` and `jetty` using the new `HttpResponse.status(int)`; on the former the custom reason is not being set, and on the latter the reason phrase is being set the same as the status code, which is not consistent with the [generic reason](https://github.com/micronaut-projects/micronaut-core/pull/5621/files#diff-21e1a1f7e5dc28f5ba95ca8569d141ccd8cdb7e0628e9050a84ea858e6fafba8R281) I'm considering.

Similarly, **should custom status codes be possible on the [`SimpleHttpResponseFactory`](https://github.com/micronaut-projects/micronaut-core/blob/3.0.x/http/src/main/java/io/micronaut/http/simple/SimpleHttpResponseFactory.java)?** I'm not sure when is this implementation used.

About testing, I have a question about what should be the expected behavior of a currently failing test.

I have ran the tests (with my implementation now on the 3.0.x branch) and I see the following failure on [`InvalidStatusSpec.groovy`](https://github.com/micronaut-projects/micronaut-core/blob/c254c0f24fed03dbaca7bb50c873739da2d2bf9e/http-client/src/test/groovy/io/micronaut/http/client/InvalidStatusSpec.groovy#L30):

```
Expected exception of type 'java.lang.IllegalArgumentException', but got 'io.micronaut.http.client.exceptions.HttpClientResponseException'
```
`HttpClientResponseException` is thrown [in this line by `DefaultHttpClient`](https://github.com/micronaut-projects/micronaut-core/blob/f183e79e2506d41b035de877c3d95548aadc74d7/http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java#L2160).

`IllegalArgumentException` is not thrown anymore because of the change in `HttpStatus`, but **should `HttpClientResponseException` be thrown on custom status codes?** From [its JavaDoc](https://github.com/micronaut-projects/micronaut-core/blob/c254c0f24fed03dbaca7bb50c873739da2d2bf9e/http-client-core/src/main/java/io/micronaut/http/client/exceptions/HttpClientResponseException.java#L27) I'm thinking it should only when the code is equal to or greater than 400.

Lastly, **do I need to implement tests?** For instance, to check that the generic reason phrase is being set properly

**Comment by graemerocher** [comment]
> Regarding compatibility, should custom response status codes also be possible on other Micronaut runtimes beyond Netty?

Yes however since the PR adds new `default` methods these can be added over time

> So far I've tried on tomcat and jetty using the new HttpResponse.status(int); on the former the custom reason is not being set, and on the latter the reason phrase is being set the same as the status code, which is not consistent with the generic reason I'm considering.

It should propagate down the `servletResponse.sendError(..)` which is a weirdly named method but should allow a custom reason phrase. https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletResponse.html#sendError(int,%20java.lang.String)

> Similarly, should custom status codes be possible on the SimpleHttpResponseFactory? I'm not sure when is this implementation used.

Yes they should.

> IllegalArgumentException is not thrown anymore because of the change in HttpStatus, but should HttpClientResponseException be thrown on custom status codes? From its JavaDoc I'm thinking it should only when the code is equal to or greater than 400.

Correct greater than 400 should throw by default

> Lastly, do I need to implement tests? For instance, to check that the generic reason phrase is being set properly

Of course, tests are required to accept a PR

**Comment by hernancerm** [comment]
@graemerocher my [pull request](https://github.com/micronaut-projects/micronaut-core/pull/5621) is ready for review

I have researched how to support custom status codes in the servlet runtimes and have found that since [micronaut-servlet is using version 2.4.0 of Micronaut](https://github.com/micronaut-projects/micronaut-servlet/blob/2.2.x/gradle.properties#L3), I think implementing the support has to wait until it uses Micronaut v3.0.x, since it would depend on the changes of my PR
