### ISSUE TITLE
testcontainers 1.15.2 does not work on Apple Silicon M1 native JDK 

### ISSUE THREAD

**Issue by ecmel** [micronaut-projects/micronaut-core#5524]
testcontainers 1.15.2 does not work on Apple Silicon M1 native JDK.

Workaround for gradle:

```
testImplementation("org.testcontainers:testcontainers:1.15.3")
```

Please check https://github.com/testcontainers/testcontainers-java/issues/3834

**Comment by jjanczur** [comment]
I have the same issue. 
I'm running testcontainers in a maven project. Unfortunately, MySQL doesn't provide ARM images and migration to gradle is not an option.

I tried bumping testcontainers version to 1.15.3 (use 5.8.0 jna ), manually adding and I've tried as well to force maven to use only that dependency (in case something else is using lower version) with dependency manager:

```
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>5.8.0</version>
            <scope>test</scope>
        </dependency>
```

Apart from that I've added to the env:
`DOCKER_DEFAULT_PLATFORM=linux/x86_64` or `DOCKER_DEFAULT_PLATFORM=linux/amd64`
Nothing helped :(

**Comment by thisdavid** [comment]
I also have the same issue with Apple M1

**Comment by jjanczur** [comment]
@thisdavid 
On production I use MySQL:8. To run the tests on my local machine **I've just used MariaDB** (fork of MySQL) But It's not a good hotfix and I won't push it of course. 
The point of the testcontainers is to use DB as close to production as possible. Otherwise, I could use embedded or H2.

I saw in one of the posts somewhere that when you run docker on Apple M1 you can pull the image with --platform=linux/x86_64. I don't know how can I specify the platform so the testcontainer will pull container for the other platform

I thought about something like:
```Java
DockerImageName myImage = DockerImageName.parse("<<PLATFORM:linux/x86_64>><< image:mysql>>").asCompatibleSubstituteFor("mysql");
mySQLContainer = (MySQLContainer) (new MySQLContainer(myImage)
...
```

**Comment by dstepanov** [comment]
This works for me:
```
new MySQLContainer<>(DockerImageName.parse("mysql/mysqlserver:8.0").asCompatibleSubstituteFor("mysql"))
```
