### ISSUE TITLE
Kotlin: MDC attributes are lost when resuming after first suspension point

### ISSUE THREAD

**Issue by drmaas** [micronaut-projects/micronaut-core#5533]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. include `micronaut-tracing` dependency
2. Create a suspending controller function
2. Set an MDC attribute
3. call `delay`
4. retrieve the MDC attribute
5. assert that it is no longer set

### Expected Behaviour

When applying the micronaut-tracing dependency, it is expected that MDC attributes are propagated across thread boundaries. In suspending Kotlin functions, this is expected also when suspending on the netty event loop thread pool, and resuming on the Kotlin default dispatcher thread pool.

### Actual Behaviour

When a suspending function resumes after the first suspension point, the coroutine default dispatcher thread on which execution resumes will not contain any previously set MDC attributes.

### Environment Information

- **Operating System**: OSX / linux
- **Micronaut Version:** 2.5.x
- **JDK Version:** 11+

### Example Application

micronaut-tracing installed:
https://github.com/drmaas/micronaut-core/blob/fix-mdc-controller-suspend/test-suite-kotlin/build.gradle#L44

failing test:
https://github.com/drmaas/micronaut-core/blob/fix-mdc-controller-suspend/test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/SuspendControllerSpec.kt#L238

**Comment by jaecktec** [comment]
you need the dependency: `implementation("org.jetbrains.kotlinx:kotlinx-coroutines-slf4j:${coroutinesVersion}")`
and then use `withContext(MDCContext())` whenever you an mdc attribute

**Comment by drmaas** [comment]
@jaecktec looking at https://github.com/jaecktec/micronaut-issues/blob/slf4j-coroutines/src/main/kotlin/com/example/endpoints/TodosController.kt#L24 - this was my workaround as well. But, I see that as a workaround, not a fix. 

This used to not be required in prior versions of micronaut. This makes me think that something internal changed w.r.t how MDC attributes are handled across netty and coroutine thread boundaries when using the `micronaut-tracing` library.

**Comment by jaecktec** [comment]
we probably need to make this one more dependecy aware:

https://github.com/micronaut-projects/micronaut-core/blob/2.5.x/http/src/main/java/io/micronaut/http/bind/DefaultRequestBinderRegistry.java#L263

either to have the library being able to inject stuff or making this one more aware of what is available

**Comment by 22dasi1bwi** [comment]
For completeness I want to mention that for me the approach with `withContext(MDCContext()) {}` still worked with Micronaut 2.5.0 and stopped working beginning with Micronaut 2.5.1.

**Comment by 22dasi1bwi** [comment]
Any updates on this? That's blocking us from rolling out higher MN versions on production.

**Comment by graemerocher** [comment]
@22dasi1bwi will try look into it tomorrow

**Comment by 22dasi1bwi** [comment]
Awesome, thanks!

**Comment by graemerocher** [comment]
So some discovery. Neither 2.4.0 nor 2.5.7 work when doing:

```kotlin
    @Get("/keepMDCAfterSuspend")
    suspend fun keepMDCAfterSuspend(): String = withContext(MDCContext()) {
        val key = "test"
        val before = "test"
        MDC.put(key, before)
        delay(10) // suspend
        val after = MDC.get(key)
        "$before,$after"
    }
```

In both cases `test, null` is returned which is possibly undesirable behaviour but does not appear to be a regression in 2.5.x

@22dasi1bwi please provide an example of what was working for you (and in what version it was working) and now isn't with 2.5.x

It is extremely difficult to instrument this because everything after the `delay` call runs in a different thread and there appears no clear way to intercept that as far as I can see. @dstepanov is going to put another pair of eyes on this.

**Comment by 22dasi1bwi** [comment]
Thanks for looking into it @graemerocher .

I provided an example in the linked issue, see https://github.com/micronaut-projects/micronaut-core/issues/5656 . Please note, that in this example I used the `micronaut-tracing` dependency which includes a class called `MdcInstrumenter`. From what I have observed this class enables the application to track MDC correctly, especially when it comes to a mix between coroutines and reactor. That being said it doesn't help though in the example you have provided. That's why I think those are two different issues indeed.

In 2.5.0 having `micronaut-tracing` in place, allows for example a HttpFilter to access the correct data from MDC. That is not true for MN versions > 2.5.0 . Please see the details in the linked issue.

**Comment by 22dasi1bwi** [comment]
Hey guys, any updates on this?

**Comment by graemerocher** [comment]
As far as I can see this is not solvable to my knowledge on the Micronaut side since we cannot effectively instrument the creation and resumption of the suspended function as it would require byte code transformation.

This is also not a regression in behavior since it has been this way for some time 

As a workaround You will need to manually wrap the logic that propagates MDC

**Comment by 22dasi1bwi** [comment]
Thanks a lot of the update!

However, the linked issue (https://github.com/micronaut-projects/micronaut-core/issues/5656) definitely seems like a regression to me.

**Comment by dstepanov** [comment]
As stated above this is not Micronaut related, every call `withContext(MDCContext())` means: collect and propagate context, so for the modifications to be affected the call is required.

```
@Get("/keepMDCAfterSuspend")
    suspend fun keepMDCAfterSuspend(): String {
        val key = "test"
        val before = "test"
        MDC.put(key, before)
        return withContext(MDCContext()) {
            delay(10)
            // suspend
            val after = MDC.get(key)
            "$before,$after"
        }
    }
```
