### ISSUE TITLE
Micronaut application as a client for SpringBootAdmin

### ISSUE THREAD

**Issue by iBernd81** [micronaut-projects/micronaut-core#565]
We are monitoring our Grails and SpringBoot applications with SpringBootAdmin (https://github.com/codecentric/spring-boot-admin).

We already tried to monitor our first Micronaut application too but it seems that this is not working out of the box.

Therefore we included the client class to register in SpringBootAdmin but the registration gets never called.

How could we reach our goal?

**Comment by graemerocher** [comment]
how is the client class defined?

**Comment by iBernd81** [comment]
The client class I mentioned comes from a starter dependency in **build.gradle**. According to the docs we have to include the following code (of course a new setting in **application.yml** is required, too):

`compile "de.codecentric:spring-boot-admin-starter-client:2.0.2"`

I guess the only thing what is missing to get the registration well done is a manual call of the importet client or something similar. Grails and SpringBoot are doing this automatically as we all know.

**Comment by ctoestreich** [comment]
@iBernd81 I have worked a bit on SBA and it is VERY spring heavy.  It is working in BOOT and GRAILS due to the spring factories via https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-client/src/main/resources/META-INF/spring.factories

Specifically `de.codecentric.boot.admin.client.config.SpringBootAdminClientAutoConfiguration` and 
`de.codecentric.boot.admin.client.config.SpringBootAdminClientCloudFoundryAutoConfiguration`

To make this work you will need to minimally port 

https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-client/src/main/java/de/codecentric/boot/admin/client/config/SpringBootAdminClientAutoConfiguration.java

and 

https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-client/src/main/java/de/codecentric/boot/admin/client/config/SpringBootAdminClientCloudFoundryAutoConfiguration.java

away from using the spring @Bean, etc and use a micronaut factory that basically duplicates those classes in your application.  It shouldn't be "hard" persay but will require you to essentially recreate the auto configurations in micronaut.  

After that is done, only SOME of the SBA site will work. For example you will have to be using SBA 2.x+ to get support for metrics as spring boot 2 and micronaut use micrometer for metrics.  This was a breaking change from the way that boot 1.4 and 1.5 exposed metrics and the SBA prior to 2.x is only boot 1.5 compatible.

Also I am not sure how many more of the endpoints besides info and health in micronaut mirror the boot equivalent enough to render in SBA.

If you manage to get all your factories squared away you should probably create an open source lib that can be added like `spring-boot-admin-micronaut-client`.  Others would probably find it useful.

**Comment by ctoestreich** [comment]
@graemerocher I am not sure this is an issue as much as a feature request and I am not sure that it should hang on in any way specifically as an open item as the SBA is pretty much built for using boot applications and, speaking for myself, I don't want to see boot-isms creep into the micronaut realm in any way beyond 3rd party bridging libraries as mentioned in my previous comment.

**Comment by iBernd81** [comment]
@ctoestreich Thank you very much for your postings. I think I will give this a try when out first Micronaut application is getting close for release.

**Comment by joshiste** [comment]
At the end the `spring-boot-admin-starter-client` is "just" doing a POST-request to the SBA server to register so imho you should just implement that functionality on top of micronaut.
Also SBA can be integrated with Eureka - when using this nothing else is needed.

(I'm the mainteriner of Spring Boot Admin)
