### ISSUE TITLE
EmbeddedServer java.net.BindException: Address already in use

### ISSUE THREAD

**Issue by savage-matt-genie** [micronaut-projects/micronaut-core#6085]
### Expected Behavior

Spinning up `EmbeddedServer` should never throw `java.net.BindException: Address already in use`

### Actual Behaviour

Spinning up `EmbeddedServer` sometimes throws `java.net.BindException: Address already in use`.

My guess is that sometimes another process binds to the random port it has chosen before it has a chance to?

* `SocketUtils.findAvailableTcpPort()` starts looking at port `1024` rather than `5000`, increasing the probability of a clash with another container spun up during the test
* In any case, random ports should be generated by binding to port `0` and accepting whatever the OS gives us- all other implementations are buggy. The port is only guaranteed to be free at the point `SocketUtils` checks, not by the time the server tries to listen.

### Version

2.5.5

**Comment by jameskleeh** [comment]
I think it makes sense to do, however we would have to figure out how to get the actual bound port to make that available in the `getPort` method.

**Comment by jameskleeh** [comment]
@savage-matt-genie PR welcome

**Comment by cbeams** [comment]
I just upgraded my application from 3.0.3 to 3.1.0-SNAPSHOT while testing @yawkat's fix for #5005, and I noticed that my tests started to fail, saying that they couldn't bind to port `-1`.

Strange, I thought, because I had specifically set up my `application-test.yml` file to override the default `micronaut.server.port` value to `-1` in order to ensure my tests' `EmbeddedServer`s bind to a random port, a feature advertised at https://docs.micronaut.io/3.0.3/guide/index.html#runningSpecificPort.

This arrangement had been working perfectly, but stopped under 3.1.0-SNAPSHOT. Indeed, looking at @graemerocher's changes in https://github.com/micronaut-projects/micronaut-core/pull/6128/files#diff-ae5ec3499c014b9efa0ec7b4b72092983d393bdb159a15f14f2cb1a8376a62c8L300-L309, it appears the `-1` support has been removed entirely.

I tried changing my `application-test.yml` file to set `micronaut.server.port` to `0` instead of `1`, but this did not work either. The `0` value is taken literally, and my tests fail as they are unable to bind to it.

Perhaps I missed something? In any case, I guess the docs should be updated to reflect the new situation.

**Comment by graemerocher** [comment]
@cbeams I am struggling to reproduce the behaviour you mention. These are the steps I undertook:

1. Modify `application.yml` as follows:

```yaml
micronaut:
  application:
    name: fresh310
  server:
    port: 8080  
```

2. modify `application-test.yml` as follows:

```yaml
micronaut:
  server:
    port: -1  
```

3. Run the tests

I see the port bound to is a random one. Do you have any additional info to describe your setup?

**Comment by jameskleeh** [comment]
@cbeams We didn't have a test for this actually so I added one and it passes. https://github.com/micronaut-projects/micronaut-core/commit/f8c84bd08e4f102c90b9213bead327c14d332145

If you can reproduce in an example application please create a new issue

**Comment by cbeams** [comment]
Thanks for looking into this. @graemerocher and @jameskleeh, I just granted both of you access rights to my project repo. See https://github.com/cbeams/xnd/commit/7855732af for simple repro steps.

**Comment by jameskleeh** [comment]
@cbeams The server is binding correctly. See:

```
16:16:16.726 [Test worker] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test]
16:18:39.849 [Test worker] INFO  xnd.p2p.Network - connecting Node[address=http://localhost:-1] to network
16:18:39.850 [Test worker] INFO  xnd.p2p.Network - no seed nodes provided; bypassing discovery
16:18:40.093 [Test worker] INFO  io.micronaut.runtime.Micronaut - Startup completed in 143497ms. Server Running: http://localhost:62368
```

You are seeing `-1` there because you are injecting nodes which require the `EmbeddedServer` in an event listener for `StartupEvent`, where the server hasn't started yet, and thus the port that is bound has not yet been determined.

`public class Network implements ApplicationEventListener<StartupEvent> {`

```
@Factory
public class NodeFactory {

    @Inject
    private EmbeddedServer server;

    @Bean
    @Named("self")
    public Node self() {
        return new Node(server.getURL().toExternalForm());
    }
}
```

If you change `Network` to instead listen for `ServerStartupEvent`, you will see:

```
16:21:17.459 [Test worker] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test]
16:21:21.229 [Test worker] INFO  xnd.p2p.Network - connecting Node[address=http://localhost:62389] to network
16:21:21.229 [Test worker] INFO  xnd.p2p.Network - no seed nodes provided; bypassing discovery
16:21:21.234 [Test worker] INFO  io.micronaut.runtime.Micronaut - Startup completed in 4075ms. Server Running: http://localhost:62389
```

**Comment by cbeams** [comment]
Interesting, thanks. What I'm doing there is a bit of a hack anyway, perhaps I can find a better way. I see that changing from `StartupEvent` => `ServerStartupEvent` does in fact solve it, but it's still worth considering the fact that the original version works under 3.0.1 and suddenly doesn't under 3.1.0. Seems like something about the semantics of handling these events has changed. Not a big deal for me, but might cause more significant breakage for others?

**Comment by jameskleeh** [comment]
It's possible, however the alternative is go to back to the much more brittle way of doing it. Retrieving the port from the server before it has started doesn't seem like a very valid use case. I don't think we should revert that change, but I appreciate the report so we can more easily triage this in the future should it come up again.

**Comment by cbeams** [comment]
Agree, and there's no downside for me in this fix. Thanks again.

**Comment by jameskleeh** [comment]
One thought is to throw an exception in the getPort method before the server has started so if anyone came across this they would know what the issue is

**Comment by mwhiting-work** [comment]
We're experiencing this issue (`java.net.BindException: Address already in use`) when using micronaut-core 3.2.7. 

Can we re-open this issue please?

**Comment by yawkat** [comment]
@mwhiting-work that error alone just means that another process or thread is already listening on the same port as the server you're trying to spin up. This should not happen if the server is configured with `port: -1`. Is your server configured this way, and if so, can you give a test case to reproduce this issue?

**Comment by mwhiting-work** [comment]
We were using `port: {$random.port}`, so we've moved to using `port: -1` and will monitor for improvements. Thanks.

**Comment by kristofdho** [comment]
We recently also ran into this issue while using `${random.port}`, using Micronaut 3.2.4. We've updated to using -1 now too and we'll monitor what happens.
But it seems to occur on ports in the end of the available range for `SocketUtil.findAvailableTcpPort`, which uses `1024-65535` as range. Shouldn't this be `1024-49151`? https://datatracker.ietf.org/doc/html/rfc6335#section-6

**Comment by yawkat** [comment]
No, you can bind to ephemeral ports just fine. But either way -1 is the correct way to do it.
