### ISSUE TITLE
Request is blocking when filter throw exception

### ISSUE THREAD

**Issue by lost22git** [micronaut-projects/micronaut-core#6181]
### Expected Behavior

![image](https://user-images.githubusercontent.com/65008815/133892060-385bf747-a754-4caa-b77b-605c7411fd51.png)

![image](https://user-images.githubusercontent.com/65008815/133892100-bedc43a0-f2c3-4abd-a599-4149bfc5d4db.png)

![image](https://user-images.githubusercontent.com/65008815/133892128-d2c4b4b6-1d3d-4aa7-8e31-dcdab3b36634.png)

### Environment Information

windows 10
adopt11-hotspot

### Version

3.0.1

**Comment by ashishkujoy** [comment]
I would like to work on this.

From initial analysis, look like we are handling any publisher error in `onErrorResume` block, but in the reported issue the filter method is throwing an exception instead of returning a publisher which emit error event.
Ideally, user should instead of throwing exception should be emitting error.

Do micronaut team want to support this case if yes then I can add a fix, else we can explicitly add this in the relevant doc.

https://github.com/micronaut-projects/micronaut-core/blob/19fef5801f31a729d88d8df47c3410fbfa442eda/http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java#L334-L355

**Comment by ashishkujoy** [comment]
On a side not, checking the second `filters.isEmpty()` seems redundent, 

https://github.com/micronaut-projects/micronaut-core/blob/19fef5801f31a729d88d8df47c3410fbfa442eda/http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java#L316-L327

**Comment by graemerocher** [comment]
PRs welcome
