### ISSUE TITLE
BigDecimal precision is lost in integer cases (regression)

### ISSUE THREAD

**Issue by zdegner** [micronaut-projects/micronaut-core#6429]
### Expected Behavior

When passing in BigDecimal values on POJOs the precision should not be lost. For some business use cases the precision and rounding of decimals can be extremely important. (I noticed this on the upgrade from 2.x -> 3.1 as some of our test cases started to fail.)

### Actual Behaviour

Precision is lost in integer cases (it increases the precision by 1 by converting for example 100 to 100.0)

This appears to be caused by this line, converting Integer to BigDecimal (if it hit the Long case above it would work, but it does not since it seems to be Integer):
https://github.com/micronaut-projects/micronaut-core/blob/813923882bcfed158d136a27bf8010edf70bb613/json-core/src/main/java/io/micronaut/json/tree/JsonNode.java#L233

### Steps To Reproduce

1. Create a POJO/DTO with a BigDecimal field
2. Send in an integer value such as new BigDecimal("100")
3. Try to maintain the precision and return the same value as was sent in (it cannot be done)

See sample app:

expected: <100> but was: <100.0>
Expected :100
Actual   :100.0

### Environment Information

Windows

### Example Application

https://github.com/zdegner/int-to-big-decimal

### Version

3.1.1

**Comment by zdegner** [comment]
If anyone else runs into this issue, the following workaround appears to resolve the deserialization issue temporarily:

_application.yml_

```yaml
jackson:
  deserialization:
    useBigIntegerForInts: true
```

**Comment by yawkat** [comment]
Okay, I understand the issue, and the fix for this particular case is easy. But do we really want to open the can of worms that is a guarantee on preserving what is essentially representation metadata?

Also note that there is already a more severe problem in the same code path: if you have a decimal value that is not representable by double, it will be truncated. In your test project, this can be shown if you replace the decimalValue test with `100.12345678901234567890`. This is a result of the decision not to use bigint/bigdec for the intermediate JsonNode in the JacksonCoreProcessor unless explicitly configured. This is the same behavior as pre-3.1.

And finally, the intermediate conversion to double also means that the simple fix for integers won't work for decimals with trailing zeros, for example `100.120`, where the precision is definitely lost. I'm pretty sure this would already have been an issue pre-3.1, too.

IMO it makes sense not to guarantee precision when useBigIntegerForInts/useBigDecimalForFloats aren't enabled. A fix for this bug would be too narrow to be useful. Thoughts? @jameskleeh @graemerocher

**Comment by graemerocher** [comment]
Agreed, but probably needs good documentation
