### ISSUE TITLE
health endpoint status DOWN does not return 503 when app has context and custom endpoint path

### ISSUE THREAD

**Issue by rbhambhra** [micronaut-projects/micronaut-core#7605]
### Expected Behavior

When health check fails (status DOWN) the http status code should be 503

### Actual Behaviour

It appears that defining micronaut.server.context-path and endpoints.all.path is not catered for in filter HealthResultFilter. As such the fiter does not fire and when status is DOWN health returns http status 200

### Steps To Reproduce

Start sample application 
./gradlew run

health will always return DOWN as per https://github.com/rbhambhra/micronaut-health-endpoint/blob/master/src/main/java/com/example/MyHealthIndicator.java#L18

Get health to see http status 200 
curl -v http://localhost:8080/mycontext/admin/health

With workaround https://github.com/rbhambhra/micronaut-health-endpoint/blob/master/src/main/java/com/example/MyHealthResultFilter.java#L8 we get 503

MICRONAUT_ENVIRONMENTS=myfilter ./gradlew run

### Environment Information

Windows 11
openjdk 17.0.2 2022-01-18

### Example Application

https://github.com/rbhambhra/micronaut-health-endpoint

### Version

3.5.2

**Comment by wetted** [comment]
Your example application is setting the `endpoints.all.path` management configuration property with a value of `admin`. This is an endpoint base path that defaults to `/`. A non-default value for it also needs to end with `/`. When I change the value in your example to `admin/` it works per expected behavior (i.e. status 503).

We may want to clarify the documentation for [endpoints.all.path](https://docs.micronaut.io/latest/guide/configurationreference.html#io.micronaut.management.endpoint.EndpointDefaultConfiguration), or add a guard in the code to append the necessary `/` if it isn't present. (I prefer the former)

This is the same problem reported at PR #4416 in a recent [comment](https://github.com/micronaut-projects/micronaut-core/pull/4416#issuecomment-1160100895).

Thoughts @sdelamo ?

**Comment by rbhambhra** [comment]
Thanks @wetted for the quick response
Yes a trailing / was all that was needed
