### ISSUE TITLE
Unable to compile simple Hello World app to native image

### ISSUE THREAD

**Issue by Paullo612** [micronaut-projects/micronaut-core#7680]
### Expected Behavior

Should compile fine. Compiles fine with `3.4.x` branch.

### Actual Behaviour

Simple Hello World app fails to compile to native image if I add `micronaut-inject` Maven dependency:

```
Error: Classes that should be initialized at run time got initialized during image building:
 io.micronaut.core.io.service.SoftServiceLoader was unintentionally initialized at build time. To see why io.micronaut.core.io.service.SoftServiceLoader got initialized use --trace-class-initialization=io.micronaut.core.io.service.SoftServiceLoader
io.micronaut.core.optim.StaticOptimizations was unintentionally initialized at build time. To see why io.micronaut.core.optim.StaticOptimizations got initialized use --trace-class-initialization=io.micronaut.core.optim.StaticOptimizations
```

However, adding `micronaut-http-netty` dependency solves compilation problems. But I do not need HTTP server in my app at all.

### Steps To Reproduce

Try to compile example app to native image:
`./mvnw clean package -Dpackaging=native-image`

### Environment Information

- Operation System: `Ubuntu 20.04`
- JDK Version: `GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06)`

### Example Application

https://github.com/Paullo612/micronaut-native-image-test

### Version

3.5.3

**Comment by yawkat** [comment]
Thanks for the report. I've looked at the issue and the cause is that in the processor classpath, the `micronaut-http-server` dependency is missing, even though it is a transitive implementation dependency of `http-processor-netty`. I think this is a bug in the gradle groovy plugin, so I've made a bug report with gradle: https://github.com/gradle/gradle/issues/21539

**Comment by yawkat** [comment]
btw as a workaround you can add this to your dependencies: `compileOnly("io.micronaut:micronaut-http-server")`

As the name suggests this is compile only, so it does not add the dependency at runtime, but it fixes the issue.

**Comment by Paullo612** [comment]
Thanks for workaround for Gradle, but what about Maven? Tried

```xml
<project>
    ...
    <dependencies>
        ...
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-http-server</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
```

```xml
<project>
    ...
    <build>
        <plugins>
            ...
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>io.micronaut</groupId>
                        <artifactId>micronaut-http-server</artifactId>
                        <version>${micronaut.core.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>
```

```xml
<project>
    ...
    <build>
        <plugins>
            ...
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths combine.children="append">
                        <annotationProcessorPath>
                            <groupId>io.micronaut</groupId>
                            <artifactId>micronaut-http-server</artifactId>
                            <version>${micronaut.core.version}</version>
                        </annotationProcessorPath>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```
And still no luck :(

**Comment by yawkat** [comment]
no i'm an idiot and commented on the wrong issue. sorry.

**Comment by yawkat** [comment]
ok ive looked at this, it's caused by a missing `--initialize-at-build-time=io.micronaut`. this is configured by micronaut-runtime, so when that dependency is present, it works fine.

I'm confused by why this is only a problem in 3.5.0+, though. I've bisected core and the regression appears with #7195. This makes some sense since that PR touched service initialization, but I don't really see an obvious issue in that PR relating to native image config.

My proposed fix would be to simply move the `--initialize-at-build-time=io.micronaut` setting from micronaut-runtime to micronaut-core. What do you think @graemerocher ?
