### ISSUE TITLE
@ContinueSpan (Jaeger) on reactive method prints WARN logs

### ISSUE THREAD

**Issue by luckyswede** [micronaut-projects/micronaut-core#773]
Hey,
Reactive methods with `@ContinueSpan` annotations prints the following WARN logs: 
```
WARN  io.jaegertracing.internal.JaegerSpan - Span has already been finished; will not be reported again.
```
Eg 
```
    @ContinueSpan
    @Get("/test1")
    Single<String> getTest1() {
        return Single.just("test");
    }
```
the same happens in this case
```
    @NewSpan
    @Get("/test2")
    Single<String> getTest2() {
        return getTest3();
    }
    @ContinueSpan
    Single<String> getTest3() {
        return Single.just("test");
    }
```
but not if `@NewSpan` is used everywhere or if the `@ContinueSpan` annotated method is synchronous.

**Comment by graemerocher** [comment]
The last example doesn't make a huge amount of sense because nothing is actually executed until the `Single` is subscribed to. So doing a `@ContinueSpan` on an internal method call would likely have no material effect.

You should be able to use `@ContinueSpan` on the top level method however, will investigate that.
