### ISSUE TITLE
Issue with binding a property of type Map<String, Map<>> 

### ISSUE THREAD

**Issue by celcius112** [micronaut-projects/micronaut-core#776]
### Steps to Reproduce

When trying to bind a property of type `Map<String, Map<>>`, the inner Map type is lost at runtime. It becomes  a simple `LinkedHashMap`. 

### Expected Behaviour

Here, I expect my Map value to be type-safe, and that a Map as value be possible with any types (see my example project for a more complex type).

### Actual Behaviour

Given a field:
```java
private Map<String, Map<String, Integer>> myMap = new HashMap<>();
```
and a configuration file with property:
```yaml
  my-map:
    key:
      key2: "test"
```
my field `myMap` will have an entry whose value is not of type `Map<String, Integer>`.  

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 1.0.0
- **JDK Version:** 8

### Example Application

I have a more complex example [here](https://github.com/celcius112/micronaut-binding-map). Please refer to the unit test in `PropertiesTest`.

**Comment by graemerocher** [comment]
So we can probably support `private Map<String, Map<String, Integer>> myMap = new HashMap<>();` however your example uses `private Map<String, Map<String, Value>> myMap = new HashMap<>();` that isn't and won't be supported out of the box since it would require reflection to materialise the `Value` object and Micronaut is designed to be reflection free.

To support that you will need to implement a custom converter. See https://docs.micronaut.io/latest/guide/index.html#customTypeConverter

So you have a `class MyValueConverter implements TypeConverter<Map, Value> ` implementation that knows how to un-marshall the object from a map. You can use `ConvertibleValues.of(map)` if you want further type conversion from the map values.

**Comment by celcius112** [comment]
Fair enough, thanks a million for your answer. 

`TypeConverter` is what I need at the moment for my use-case. The `Map<String, Map<String, Integer>>` issue was found while experimenting, and I thought it would be linked to my use-case.

**Comment by celcius112** [comment]
Hello @graemerocher,
I tried to implement `TypeConverter<Map, MyProperties.Value>` as you suggested, but there is still an issue : 
In `DefaultConversionService#convert`, when trying to convert my property, the variable `pair` will have a source of type `java.util.LinkedHashMap` and a target `java.util.Map`, **a pair that has been previously cached**, the cached value being the `Map -> Map (inner type conversion)` implemented in `DefaultConversionService`. As such my converter `MyValueConverter` will never be called 😢. 

My [example project](https://github.com/celcius112/micronaut-binding-map) has been updated accordingly.

**Comment by graemerocher** [comment]
Ok, thanks we will take a look

**Comment by celcius112** [comment]
Works like a charm, many thanks @graemerocher
