### ISSUE TITLE
ResourceLoader is broken with JAR

### ISSUE THREAD

**Issue by ThraaxSession** [micronaut-projects/micronaut-core#8296]
### Expected Behavior

When the JAR is directly used, the `ResourceLoader` can load any resource from `Resources`

### Actual Behaviour

I get a call stack, when I want to get a resource from JAR.
When I run from Idea, it works fine.

In Kotlin constructor:
`private val resourceLoader: ResourceLoader`
Actual call:
`val logsScript = resourceLoader.getResource("commands/getLogs.sh")`

![image](https://user-images.githubusercontent.com/3085830/200194086-717cc1dc-9819-4d65-b8f3-76fde2d8fab5.png)

```06.11.2022 21:37:33.675 [default-nioEventLoopGroup-1-15] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: java.io.FileNotFoundException: /mnt/d/Projekte/Uberspace-Projekte/SpaceUp-Server/file:/mnt/d/Projekte/Uberspace-Projekte/SpaceUp-Server/build/libs/SpaceUp-0.26.0-SNAPSHOT-all.jar!/commands/getLogs.sh (No such file or directory)
com.jcraft.jsch.SftpException: java.io.FileNotFoundException: /mnt/d/Projekte/Uberspace-Projekte/SpaceUp-Server/file:/mnt/d/Projekte/Uberspace-Projekte/SpaceUp-Server/build/libs/SpaceUp-0.26.0-SNAPSHOT-all.jar!/commands/getLogs.sh (No such file or directory)
        at com.jcraft.jsch.ChannelSftp.put(ChannelSftp.java:485)
        at com.jcraft.jsch.ChannelSftp.put(ChannelSftp.java:367)
        at technology.iatlas.spaceup.services.SshService.upload$suspendImpl(SshService.kt:240)
        at technology.iatlas.spaceup.services.SshService.upload(SshService.kt)
```

### Steps To Reproduce

* Build a JAR
* Use the resource loader.
* Retreive a resource
* you get a stacktrace

### Environment Information

GraalVM 22 / Java 11
Micronaut 3.7.3

### Example Application

[Here is the service which crashes](https://github.com/SpaceUp-Cloud/SpaceUp-Server/blob/master/src/main/kotlin/technology/iatlas/spaceup/services/ServiceService.kt#L115)

### Version

3.7.3

**Comment by yawkat** [comment]
This is an issue in your code, you are incorrectly converting the URL returned by getResource into a file here: https://github.com/SpaceUp-Cloud/SpaceUp-Server/blob/0ce749634ec7c4cbc129a7e829dbdd305073b0a9/src/main/kotlin/technology/iatlas/spaceup/services/SshService.kt#L236-L241

When the application is packaged as a jar, the resources are entries in that jar file, they are not individual files on the file system. They have a proper URL (the one returned by getResource), but those URLs do not have an associated java.io.File, because they're inside the jar. You can probably call URL.openStream and pass the stream directly, though.

**Comment by ThraaxSession** [comment]
@yawkat oh yes, face palm to me. I changed that 2 weeks ago. My bad.
