### ISSUE TITLE
Version 3.8.0: Forgot update micronaut-opentelemetry to latest version 4.5.0

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#8548]
Micronaut 4.8.0 still related to micronaut-opentelemetry 4.4.0, but latest version is 4.5.0

### Version

3.8.0

**Comment by sdelamo** [comment]
I have a [utility to check if something needs to be updated in the BOM](https://github.com/sdelamo/bom-versions). It uses GitHub releases to check. The releases need to be not in a draft status. 

The problem is [open telemetry 4.5.0 released failed](https://github.com/micronaut-projects/micronaut-tracing/actions/runs/3426859052), and the GitHub release remained in draft status, and thus, my tool did not check.

**Comment by sdelamo** [comment]
Micronaut Framework 3.9.0 will include 4.5.0
