### ISSUE TITLE
Loss of precision in OffsetDateTime when using reactive APIs with declarative http client & JDK17

### ISSUE THREAD

**Issue by David-16** [micronaut-projects/micronaut-core#8848]
### Expected Behavior

Short story: When using Jackson to deserialize an `OffsetDateTime` from a JSON string returned from a reactive API on a Micronaut generated declarative HTTP client with JDK 17 & Micronaut 3.7.3, the precision is lower than when deserializing the same value from a non-reactive API on the same setup

Long story: Consider the following classes (assume they are implemented plainly and simply using Jackson serialization):

```
interface Foo {
  OffsetDateTime getCreatedTime();
}

interface FooService {
  Foo getFoo;
}

@Client
interface FooRestService {
  @Get("/1")
  Single<Foo> getFoo();

  @Get("/2")
  Flowable<Foo> getFoos();
}
```

Consider the following calls:
```
Foo f1 = fooService.getFoo();
Foo f2 = objectMapper.readValue(objectMapper.writeValueAsString(f1), Foo.class);
Foo f3 = fooRestService.getFoo().blockingGet();
Foo f4 = fooRestService.getFoos().blockingIterable().iterator().next();
```

With JDK 11, getCreatedTime() returns something like: `1677188061.644873000`

With JDK 17, getCreatedTime() returns something like: `1677188061.644872962` EXCEPT for `f4` which returns: `1677188061.644873000`

The only difference is the precision.  JDK 17 returns higher precision value in general, except in the Flowable call

Again, this ONLY happens with the Flowable / Flux call.  All other calls (including Single/Mono and even when using the plain http client) return the higher precision value

The expectation is that the `f1`, `f2`, `f3`, `f4` should return the exact same string

### Actual Behaviour

The value of `f4` is different than `f1`, `f2`, and `f3` due to `OffsetDateTime` being of lower precision

### Steps To Reproduce

Run attached project
[demo.zip](https://github.com/micronaut-projects/micronaut-core/files/10844793/demo.zip)

Here is sample output from Open JDK 11 & Oracle JDK 17

```
$> mvn --version | grep Java
Java version: 11.0.12, vendor: Oracle Corporation, runtime: .user/programs/sdkman/candidates/java/11.0.12-open

$> mvn clean test
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

-----------------------

$> mvn --version | grep Java
Java version: 17.0.6, vendor: Oracle Corporation, runtime: .user/programs/sdkman/candidates/java/17.0.6-oracle

$> mvn clean test
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[ERROR]   DemoTest.test:57 expected: <Foo{createdTime=2023-02-24T18:17:37.652966720Z}> but was: <Foo{createdTime=2023-02-24T18:17:37.652966700Z}>

```

### Environment Information

RedHat Linux
JDK 17.0.6

### Example Application

[demo.zip](https://github.com/micronaut-projects/micronaut-core/files/10844793/demo.zip)

### Version

3.7.3

**Comment by yawkat** [comment]
it's the node deserialization issue. the datetime is stored as double in an intermediate step, and loses some precision. you can change it to use BigDecimal like this:

```yaml
jackson:
  deserialization:
    USE_BIG_DECIMAL_FOR_FLOATS: true
```

Nothing we can really do about it, beyond avoiding to parse through intermediate JsonNodes. #8803 might fix it, i'm not sure.

**Comment by David-16** [comment]
@yawkat Hi, can you clarify why it only happens when passed through the reactive apis?

It does not seem sufficient to say it is just a 'node deserialization issue' when the example program proves it works in almost all other cases.  Are the reactive apis or something between them explicitly configuring jackson to do something different than all the other usecases?  Is this perhaps part of the non-blocking parser you referenced?

**Comment by yawkat** [comment]
i havent checked for this case specifically, but flux has different handling because it can handle multiple json values in a stream.

**Comment by David-16** [comment]
> i havent checked for this case specifically

@yawkat I would like to reiterate that this \*ONLY* happens when using Mono/Flux/Single/Maybe/Flowable/etc.  All other use cases (calling Jackson directly, Micronaut Rest Controller without reactive, and so on, return the correct value without rounding (see example program)

I am not sure what case you checked, but if you did not check this usecase then would you be kind enough to take a second look?  The reason for the ask is that we are moving to a reactive API and our expectation was that Jackson would be the least of our problems.  But, if Jackson does behave differently in the reactive world, then that is something we need to account for

**Comment by yawkat** [comment]
I'm sorry but I won't spend more time on finding out exactly why it is happening. The workaround I provided above fixes your test case. I also think #8803 might help though that is more "by accident". So unless you can show that a similar issue happens with 4.0-SNAPSHOT or with the workaround, then I don't see the value in investigating this further. Conversions to and from json nodes happen at various stages in the pipeline, and that will remain an issue.

fwiw this is more of a micronaut thing instead of a jackson thing, specifically related to this code: https://github.com/micronaut-projects/micronaut-core/blob/991a6b4b0411e96380ca79784b0cb040d5831160/jackson-core/src/main/java/io/micronaut/jackson/core/tree/JsonStreamTransfer.java#L122 – jackson has similar issues with TokenBuffer but they're working on fixing those.

If you're really interested in a deeper analysis of the issue I'm sure you could pay the objectcomputing folks to do it, but I don't really see the value.

**Comment by yawkat** [comment]
sorry @David-16, I didn't realize you also worked for oracle and didn't want to do free work figuring it out for the specific case, since the config option fixes the specific issue.

I've checked again, and the reason why the test fails specifically lies on the client side. The declarative client uses client.jsonStream when the return type is a non-single (i.e. not Mono) publisher. For this the client also supports "json streams", as in multiple json objects after another which would then be returned as multiple items of the Flux. In order to support this, the client makes use of JacksonCoreProcessor, which buffers the json in intermediate JsonNodes which is where the loss of precision happens. The config option makes the intermediate representation use bigdecimal instead.

It's not really a jackson issue, this is solely on the micronaut side. Jackson has similar issues with their TokenBuffer (though they're working on them), but our implementation of this buffering step is independent, so the same issue would happen e.g. with micronaut-serialization.

**Comment by David-16** [comment]
@yawkat Thanks for the follow up and I appreciate the second look and fast turn-around

Ideally, I wish the Flux and Mono APIs behaved similarly, but I understand this is a bit of an edge case and I am fine with the workaround.
