### ISSUE TITLE
Add support for HashiCorp Vault

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-core#904]

**Comment by sic-bre** [comment]
This HashiCorp Vault integration has been deprioritized since we last reviewed this issue last year.  We were waiting until both Consul and Vault integration were available "out of the box" before evaluating micronaut (as we are currently using Springboot with the spring-cloud-* libraries and require both integrations).  Given the change of status we are wondering:

1) Where can we find out where this fits in the backlog of requested features (sooner or later)
2) Are there suggested approaches to do our own limited integration with Vault that would minimize rework with an eventual planned official integration?
3) Has any work started on an official integration that we could contribute to to bring the feature forward sooner?

**Comment by graemerocher** [comment]
@sic-bre 

1. Roadmap planning is largely done here https://github.com/micronaut-projects/micronaut-core/projects/5
2. Vault has a REST API, you can always define your own declarative client to talk to Vault. That is what we do for Consul.
3. No work has started yet, contributions are absolutely welcome. @alvarosanchez is focused on improved Kubernetes support and may get to this issue later in the year. 

Thanks for the feedback.

**Comment by thiagolocatelli** [comment]
Has any work started for this one? If not, I would like to give it a try @graemerocher, since I have already built the integration to get configuration properties from spring config, to get from Vault it should not be too different from that. Vault has a few caveats with their REST apis and the type of secret store you pick, but I think I can make it. I will start working on a local version next week.

**Comment by graemerocher** [comment]
@thiagolocatelli awesome, contributions welcome!

**Comment by thiagolocatelli** [comment]
@graemerocher is there a way to debug the application startup in order to see why some of my @Requires are not working? I created the base implementation but it seems my criteria are not being matched. I followed basically the same idea I applied to the spring cloud config server implementation but something might be wrong.

**Comment by thiagolocatelli** [comment]
I found out how to debug conditions on the document, going to keep working on it.

**Comment by thiagolocatelli** [comment]
@graemerocher have made a lot of progress but I can't figure it out why my emitter is not calling onComplete. Let's say we use dev as environment name, we have to make two calls to vault, one using /v1/backendv1/${application-name} and one using /v1/backendv1/${application-name}/{environment-name}, in our case 'dev'.

Because I am making more than one call, I have an object List<Flowable<VaultResponse>>. I am trying to iterate over this list in order to emit the PropertySource, but my code emits only once, while I have 2 flowables in my list.

```java
        List<Flowable<VaultResponse>> configurationValuesList = retrieveVaultProperties(activeNames, errorHandler);

        final AtomicInteger priority = new AtomicInteger(Integer.MAX_VALUE);
        final AtomicInteger source = new AtomicInteger(0);

        Flowable<PropertySource> propertySourceFlowable =
                Flowable.fromIterable(configurationValuesList).flatMap(vaultResponseFlowable ->
                        vaultResponseFlowable.flatMap(vaultResponse -> Flowable.create(emitter -> {
                        VaultResponseData vaultResponseData = vaultResponse.getData();

                        if (CollectionUtils.isEmpty(vaultResponseData.getData())) {
                             emitter.onComplete();
                        } else {
                            if (LOG.isInfoEnabled()) {
                                LOG.info("Obtained property source [{}] from Vault", activeNames.toArray()[source.getAndIncrement()]);
                            }

                            emitter.onNext(PropertySource.of("Vault", vaultResponseData.getData(), priority.getAndDecrement()));

                            if(source.get() == configurationValuesList.size()) {
                                emitter.onComplete();
                            }
                        }
                }, BackpressureStrategy.ERROR)));

        if (executorService != null) {
            return propertySourceFlowable.subscribeOn(io.reactivex.schedulers.Schedulers.from(
                    executorService
            ));
        } else {
            return propertySourceFlowable;
        }
```

Would you be able to tell me what would be the correct way to emit propery sources from a List<Flowable<VaultResponse>>? Once I figure this out, I should be almost done. Thank you.

**Comment by graemerocher** [comment]
@thiagolocatelli you may need to use `onErrorResume` in your reactive logic to handle errors

**Comment by thiagolocatelli** [comment]
@graemerocher I will give it a try on your suggestion. At the moment I am trying to generate a native image. I notice the file `native-image.properties` created by the cli does not include `bootstrap.yml`, and the vault config only works if it is inside the `bootstrap.yml` and not inside `application.yml`. I changed the file to look like this:

```
Args = -H:IncludeResources=logback.xml|boostrap.yml|application.yml \
       -H:Name=vault-config-sample \
       -H:Class=com.github.thiagolocatelli.Application
```

**Comment by thiagolocatelli** [comment]
Native image is working as well, on my mac, but not the one created by the Dockerfile generated by the cli, it simply ignores what it's inside the 'bootstrap.yml'. Back to working on the 'onErrorResumeNext' now.

**Comment by thiagolocatelli** [comment]
All issues resolved, will run more tests and should be sending the Pull Request in a couple of days.

@graemerocher I think we have to include bootstrap.yml in the native-image.properties too.

**Comment by thiagolocatelli** [comment]
@graemerocher I thought I had it working but for some reason it does fail when the tests run in Travis (https://travis-ci.org/micronaut-projects/micronaut-core/builds/532568222). On both laptops I have the build works fine for the entire project or just for discovery client (logs -> https://pastebin.com/s7d7LjFU).

The code is in this repository `https://github.com/thiagolocatelli/micronaut-core`, branch `vault-config-client`. Both discovery-client and documentation were updated. If you have any idea of what could be happening, I'd appreciate. Thank you.

**Comment by thiagolocatelli** [comment]
It is building now with the help from @jameskleeh
