### ISSUE TITLE
HTTP Client Filter can't change request URI

### ISSUE THREAD

**Issue by Hades32** [micronaut-projects/micronaut-core#917]
Tested using Java 11 and Micronaut 1.0.1, the following code only works partially:

``` kotlin
package mn.max

import io.micronaut.http.HttpResponse
import io.micronaut.http.MutableHttpRequest
import io.micronaut.http.annotation.Filter
import io.micronaut.http.filter.ClientFilterChain
import io.micronaut.http.filter.HttpClientFilter
import org.reactivestreams.Publisher
import java.net.URI

@Filter("/**")
class GoogleRequestSigner : HttpClientFilter {
    override fun doFilter(req: MutableHttpRequest<*>, chain: ClientFilterChain): Publisher<out HttpResponse<*>> {
        val uri = req.uri
        val signature = signUrl(uri)
        val previousQuery = if (uri.query != null && uri.query.isNotEmpty()) uri.query + "&" else ""
        val newQuery = previousQuery + "signature=" + signature
        val signedUri = URI(uri.scheme, uri.userInfo, uri.host, uri.port, uri.path, newQuery, uri.fragment)
        return chain.proceed(req.uri(signedUri).header("X-Blubb",signature))
    }

    private fun signUrl(uri: URI): String {
        return "TODO"
    }
}
```

The outgoing request will have the "signature" placed in the injected header, but there will be NO additional query param.

**Comment by Hades32** [comment]
@graemerocher are you already working on this? If you'd point me in the right direction I'd also be happy to do a PR

**Comment by graemerocher** [comment]
@Hades32 you are welcome to take a look, probably won't get to it for a little while (unless someone else on the Micronaut team does).

The issue is a little bit more complex than headers because the URI is resolved ahead of time for load balancing purposes:

https://github.com/micronaut-projects/micronaut-core/blob/master/http-client/src/main/java/io/micronaut/http/client/DefaultHttpClient.java#L1089

And then passed downstream to the reactive streams subscribers:

https://github.com/micronaut-projects/micronaut-core/blob/master/http-client/src/main/java/io/micronaut/http/client/DefaultHttpClient.java#L978

So we would have to check again if the original URI was modified and then rebuild it combining the URI found via service discovery and the URI mutated by the user.

Ribbon does something similar which may serve as inspiration https://github.com/Netflix/ribbon/blob/master/ribbon-loadbalancer/src/main/java/com/netflix/loadbalancer/LoadBalancerContext.java#L572

**Comment by aseychell** [comment]
I'm experiencing a similar issue in the latest versions (tested on 3.6.0 and 3.7.2) of Micronaut.  Was this changed intentionally or is it a regression?
