### ISSUE TITLE
version shown on startup is core version not platform version

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#9190]
### Issue description

DEFAULT 2023-05-04T14:22:02.374979Z Micronaut (v4.0.0-M2)
DEFAULT 2023-05-04T14:22:02.372840Z |_| |_|_|\___|_| \___/|_| |_|\__,_|\__,_|\__|
DEFAULT 2023-05-04T14:22:02.372816Z | | | | | (__| | | (_) | | | | (_| | |_| | |_
DEFAULT 2023-05-04T14:22:02.372811Z | |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
DEFAULT 2023-05-04T14:22:02.372804Z | \/ (_) ___ _ __ ___ _ __ __ _ _ _| |_
DEFAULT 2023-05-04T14:22:02.372776Z __ __ _ _

**Comment by melix** [comment]
One option we have is to change core so that it reads the version from a conventional classpath resource, e.g `/META-INF/micronaut-version.txt`. If that file is present, then show the version. If not, then don't show it. Then the build plugins can generate that file and put it on classpath.

A variant is to not limit that to version, but generalize that to the whole banner, so that the banner is read from classpath, and that the banner includes the version.

**Comment by wetted** [comment]
@sdelamo @melix 

Cedric and I talked about this and we agreed that a way to get around this is to leverage the existing feature for customizing the banner (see https://docs.micronaut.io/latest/guide/#environments) and add build tasks to the Gradle and Maven plugin that generate the default banner text to the user's `src/main/resources/micronaut-banner.txt` file, with the platform version, since that is available to the plugins, whereas it is not available to core. Something like this:

```
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut Framework (4.0.0)

```
My question is, if the user's banner file isn't present should we display the default banner text – as we do now – but without the version text line, or do we display nothing at all? The core code is easy enough to change for it either way.

**Comment by melix** [comment]
I think that if the user has a `micronaut-banner.txt` file, then we shouldn't try to display the version. If there isn't, then the build plugin can generate one, with the version.

**Comment by graemerocher** [comment]
relying on build plugins for this behaviour seems like a hack to me as does writing files to their source tree that have to potentially be added to .gitignore. If it is the only solution then the build plugins should write the file to the `build` / `target` directory and not the source tree.

However this would mean again that we have a situation where when running from the IDE this will not work as it is build system dependent.

**Comment by melix** [comment]
Absolutely, the idea would be to have, at least in Gradle, a `generateBanner` task, which does nothing if `src/main/resources/micronaut-banner.txt` already exists, and generates such a resource in the build directory instead. As for the difference in the IDE, for the banner that's probably not a big deal, and there are many more things which could be broken if not using delegation to the build tool (basically any user plugin generating sources would be broken).

**Comment by wetted** [comment]
There's another issue I thought of. I don't think we can generate the text file to `src/main/resources/micronaut-banner.txt`. If the user accepts it as is and never runs the task to regenerate it, there's no guarantee that the platform version the banner shows is correct. For example, if user updates the build to a newer Micronaut Framework but does not regenerate the file, it will be wrong.

This is staring to seem more complicated than worth and maybe not better than just keeping a property in core with the platform version we have to maintain (I'm not really suggesting it but that would work easily enough).

**Comment by alvarosanchez** [comment]
Generating the whole banner just because we don't have the version string handy seems overkilling to me too.

What if we generate a source file in core or platform (with a task from micronaut-build) which then goes compiled into the jar, that has that version string? (and potentially others). This:

1. Works without the build plugins.
2. Doesn't mess with user's source.
3. Provides a way for the future control panel module to display such version(s).

**Comment by melix** [comment]
Core doesn't depend on platform, and it must not. So we cannot generate a jar which contains a version in `core`. Platform is a platform BOM, it doesn't have a jar (and shouldn't, it would break a lot of assumptions if it switched from type pom to jar), so we cannot either.

That's why leveraging the banner feature seems reasonable to me.

**Comment by alvarosanchez** [comment]
Platform is a BOM, yes, but we can create a "io.micronaut.platform:platform-version" module can't we?

I'm very hesitant to keep adding things like this in the build plugins, I believe we are shooting ourselves in our feet.

**Comment by melix** [comment]
Adding a module with platform-version would require adding a project with just a string in a jar, plus either adding a dependency in the user build or having the build plugins add the platform dependency version _just to display a version_, which would be dropped anyway as soon as a user disables the banner. This seems much more overkill to me than a task generating a banner if it doesn't exist.

**Comment by graemerocher** [comment]
it is behaviour that is coupled to build plugins though, which I am not a fan of. It may seem overkill to have a single module in platform that just holds the ability to resolve the version, but I personally I think it is the right way forward.

**Comment by graemerocher** [comment]
it also means the code here doesn't have to be altered https://github.com/micronaut-projects/micronaut-core/blob/4.0.x/core/src/main/java/io/micronaut/core/version/VersionUtils.java

**Comment by graemerocher** [comment]
And note that this logic has impacts on other parts of the framework like when using `@Requires(sdk=MICRONAUT, value="4.0.0")` 

see https://github.com/micronaut-projects/micronaut-core/blob/4.0.x/inject/src/main/java/io/micronaut/context/annotation/Requires.java#L84

**Comment by graemerocher** [comment]
The other alternative and possibly simpler solution is we should could change the output to instead print `Micronaut (Core v4.0.0)` and be done with it

**Comment by melix** [comment]
The problem is that you get a redundant dependency (jar) for something that doesn't really belong here. The version of the platform is already defined in the user build, so the build plugins _know_ about it. There is also the possibility that you get a different version jar from the version of the platform (because nothing can prevent this from happening, it's conflict resolution after all...). Instead of generating the banner (or in complement too), we could also have the build plugins generate the version.properties file.

Regarding the `Requires` annotation. What is it supposed to work on now? Core version of Platform version?

**Comment by graemerocher** [comment]
it has historically always used the core version and using the same logic to resolve the version as the version utils.

frankly I don't like this idea of generating files with build tools, it just sounds like a hack so IMO we should just change the output to clarify it is the core version.

**Comment by alvarosanchez** [comment]
No, it has historically always used **the Micronaut version**, which is now the Platform version - likely the only one that users will care about. Separating core and platform versions have these hidden gems :)

I also think that generating a class just for this is suboptimal, but also, the "less bad" of all the alternatives.

**Comment by melix** [comment]
I'm fine with using "Micronaut Core" in the version that we display. I'm clearly not fond of the idea of having a "version jar", which sounds like a terrible hack to me). The reason I was keen on moving that to the build plugins is that this is the only place where the platform version is defined. I'm personally -1 on the "jar" solution but will comply with whatever the team chooses.

**Comment by wetted** [comment]
Can we set a property in micronaut-core, in `gradle.properties` or in the version catalog for the platform version, without making it a dependency otherwise, and read that in the core build where we already read `projectVersion` for the banner implementation? Then it would be pretty straightforward to implement entirely in core. Maybe renovate could be used to update that platform property, keeping it decoupled from the platform otherwise.

**Comment by graemerocher** [comment]
core can't depend on platform

**Comment by melix** [comment]
This would require to upgrade the version of the platform in core _before_ the platform is released, which would create at best a lot of confusion. I think it's better to let core independent of platform altogether.

**Comment by wetted** [comment]
This all seems overly complicated for a banner. What if we just print "Micronaut Platform 4" and nothing more fine-grained than that?

**Comment by melix** [comment]
I'm +1 on printing "Micronaut Platform 4". I would be more keen on adding some kind of standard mechanism so that _all_ modules publicize their version so that it can be discovered at runtime. This would be useful for a "developer UI", and in that case, we could have a module in platform which would implement that standard mechanism (which would probably be a combination of a properties file and a bean). I would leave that for Micronaut 4.1+.
