### ISSUE TITLE
Response filters are executed in min-max order when request in max-min order

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-core#9390]
### Expected Behavior

Both are executed in the same order.

### Actual Behaviour

The current behaviour is a bit confusing
```java
        @Order(1)
        @RequestFilter
        void myRequestFilter1() {
        }

        @Order(2)
        @RequestFilter
        void myRequestFilter2() {
        }

        @Order(2)
        @ResponseFilter
        void myResponseFilter1() {
        }

        @Order(1)
        @ResponseFilter
        void myResponseFilter2() {
        }
 ```

### Version

4.0.0-M3

**Comment by yawkat** [comment]
this behavior is intentional. the order is kind of like a "layer". so if you have a filter A with order 1, and a filter B with order 2, the filter A will wrap around the execution of filter B. so the request filter A will execute before the request filter B, but the response filter B will execute before response filter A. it's basically the same as the legacy filter api, and imo it's the most sensible behavior.

**Comment by yawkat** [comment]
you can see this in your snippet, the two filter methods with Order 1 wrap the two filter methods with Order 2.

**Comment by dstepanov** [comment]
IMHO, it's very confusing @micronaut-projects/core-developers WDYT?

**Comment by graemerocher** [comment]
my concerning with reversing this would be how it interplays with the constants defined in https://github.com/micronaut-projects/micronaut-core/blob/4.0.x/http/src/main/java/io/micronaut/http/filter/ServerFilterPhase.java

**Comment by yawkat** [comment]
it seems to work the same way in jax-rs: https://www.logicbig.com/tutorials/java-ee-tutorial/jax-rs/filters-ordering.html

**Comment by graemerocher** [comment]
if it works the same way then I don't think we should change it
