### ISSUE TITLE
@PostConstruct not working

### ISSUE THREAD

**Issue by Hades32** [micronaut-projects/micronaut-core#943]
This is not working with Micronaut 1.0.1 and Kotlin

```kotlin

import io.micronaut.context.annotation.Value
import javax.annotation.PostConstruct
import javax.inject.Singleton

@Singleton
class WebhookRegistrationService(
        private val botClient: BotClient
) {

    @Value("\${telegram.webhook-url}")
    var webhookUrl: String = ""

    @PostConstruct
    fun registerHook() {
        println("webhok post construct")
        botClient.registerWebHook(WebhookConfig(webhookUrl))
    }
}
```

UNLESS you do this

```kotlin
applicationContext.getBean(WebhookRegistrationService::class.java)
```

And ONLY this. If the singleton just "exists" nothing happens. Even if you reference it from another bean in the constructor it does just nothing...

**Comment by graemerocher** [comment]
beans by default are lazy, you can replace `@Singleton` with `@Context` scope to eager initialise the bean

**Comment by Hades32** [comment]
Note to my future self and other people running into this:

What you probably REALLY want to do is something like this:

```kotlin
@Singleton
open class WebhookRegistrationService{
    @Async
    @EventListener
    protected open fun registerHook(event: ServiceStartedEvent) {
        // TODO do it
        log.info("web hook post registered")
    }
}
```

**Comment by asarkar** [comment]
@graemerocher I came here for the exact same issue. This should be documented because it's not clear at all. Since beans are singleton by default, `@PostConstruct` won't work OOTB until something else is done (use `@Context`).

@Hades32 I don't think event listener does quite the same thing. If `@PostConstruct` fails, the application will fail to start (haven't verified in Micronaut but that's what happens using Spring); however, the event listener method won't fail the startup. Depending on your needs, you may actually want to fail the startup.
My workaround is to use an `init` block for singleton beans. Problem solved.

**Comment by jeffbrown** [comment]
>  Since beans are singleton by default, @PostConstruct won't work OOTB until something else is done (use @Context).

I don't think it is true that `@PostConstruct` won't work OOTB until something else is done.  The intent of `@PostConstruct` is to mark a method that will be invoked after the instance is constructed.  That appears to be what is happening.  A bean marked with `@Singleton` will be constructed the first time it is needed.  If your intent is have the method executed at application startup time, an event listener will often make more sense.

**Comment by asarkar** [comment]
@jeffbrown See my comment why an event listener and `PostConstruct` aren’t necessarily the same thing

**Comment by graemerocher** [comment]
Using @EventListener on a method that takes a StartupEvent and throws an exception will fail startup
