### ISSUE TITLE
Request body not available in @Error method

### ISSUE THREAD

**Issue by francisf2** [micronaut-projects/micronaut-core#9583]
### Expected Behavior

Main controller:

```
@Controller( "/path" )
public class Controller
{
	@Post
	@Consumes( MediaType.APPLICATION_JSON )
	public HttpResponse< Void > create( @Body( ) Request request )
	{
		<...>
	}
}
```

Exception handler:

```
@Controller( "/Exception" )
public class HttpExceptionController
{
	@Error( global = true )
	public HttpResponse< String > GenericException( HttpRequest request, Exception e )
	{
		Optional<String> body = request.getBody( String.class );
	}
}
```

If request body is malformed (`e instanceOf ConversionErrorException`), I expect the body to be present in `GenericException` (this is the case with Micronaut 3.9.4)

### Actual Behaviour

Body is not present

### Steps To Reproduce

Netty server
Send `{}` body to application

### Environment Information

JDK 17

### Version

4.0.0

**Comment by rbhambhra** [comment]
Thanks for reporting this @francisf2 
I see the same and look forward to a resolution so can upgrade to Micronaut 4

**Comment by yawkat** [comment]
can you use `@Body String content` instead of using getBody?

It would be easy for us to allow access via getBody, but this carries some implications with it that I don't like. In particular, it would allow access to the raw body bytes also at earlier stages, e.g. in request filters. But in those cases it would be an unreliable api, because it will only work with immediate requests, not streaming requests. The `@Body`-based approach however will work for any kind of request because it can delay the method execution to buffer if necessary.

**Comment by rbhambhra** [comment]
@yawkat 
I could use @Body String content

But I would rather let Micronaut deserialize the object for me. Getting the content as String then using an injected objectmapper seems like a bad idea for my service as it is high volume (60k requests/min)
I only really care about the body in the error handler so that I can log if we receive json that fails to parse. In my use case, have no need to look at body in a filter

**Comment by yawkat** [comment]
no i mean you can use `@Body String` in the error handler

**Comment by rbhambhra** [comment]
@yawkat 

Thanks for helping on this

I tried it with the following signatures, but always get content as an empty string

`@Error(global = false)
  public HttpResponse<Response> error(HttpRequest<?> request,  @Body String content, Exception e)
  `
  
  ` @Error(global = false)
  public HttpResponse<Response> error(@Body String content, Exception e)`

**Comment by yawkat** [comment]
oh, you're right. i will fix that, i have less concerns about that.

**Comment by rbhambhra** [comment]
Thanks @yawkat and Micronaut team - this now works as expected in 4.0.2
