### ISSUE TITLE
Allow the use of dashes in management endpoint names

### ISSUE THREAD

**Issue by katrotz** [micronaut-projects/micronaut-core#9607]
### Feature description

Consider below management endpoint definition:
```
import io.micronaut.management.endpoint.annotation.Endpoint;

@Endpoint("service-metadata")
public class ServiceMetadataController {
... 
}
```

### Current behaviour:
When defining a new management endpoint that contains dashes (e.g. /service-metadata) does not work, since when accessing this endpoint the application returns 404.

### Desired behaviour:
Allow defining management endpoints containing dashes. 
Ideally it should allow using any name for the management endpoint that is a valid URL path. 

The management endpoint id is verified against [this regex](https://github.com/micronaut-projects/micronaut-core/blob/4.0.x/management/src/main/java/io/micronaut/management/endpoint/processors/AbstractEndpointRouteBuilder.java#L52).

**Comment by pragyamutluru** [comment]
Hi,
I would like to work on this issue.
I tried to push a branch with the changes, in order to create the pull request.
However, it is giving me 403.

It is my first time contributing, is there any particular access I need to raise or a process to follow?
There is no special access mentioned in https://github.com/micronaut-projects/micronaut-core/blob/4.6.x/CONTRIBUTING.md

Edit: Raised PR after forking.

**Comment by pragyamutluru** [comment]
PR https://github.com/micronaut-projects/micronaut-core/pull/10998 has been raised.

Please let me know if something needs to be improved/changed.
