### ISSUE TITLE
HttpClient jsonStream: clients might not get/know about a server exception

### ISSUE THREAD

**Issue by asantare** [micronaut-projects/micronaut-core#9652]
### Issue description

The test `StreamRequestSpec#"test json stream post request with POJOs flowable error"` seems to be non-deterministic, I managed to get an error after running the whole file few times.

The gist of the test is to expect an exception when the server receive an error (on Book 3), but the client doesn't fail (i.e. the test fails) if the server closes the connection (`PipelineServerHandler$StreamingOutboundHandler#onError`) exactly when a valid json buffer has been transferred.

To consistently reproduce this behaviour the channel content can be flushed before closing in `PipelineServerHandler$StreamingOutboundHandler#onError` method (see image below, btw is this a change that makes sense to commit?)

With this change the client always gets valid json pieces, all Books before number 3 (Books 0, 1, 2) and continues happily without knowing about the error server side on Book 3, so the test fails because no exceptions are thrown.

I don't know how it was in `3.9.x` but it seems to be something missing in the jsonStream protocol or in the client implementation itself, or in the server? just closing the channel without notifying any error.

![image](https://github.com/micronaut-projects/micronaut-core/assets/2014232/3ca01897-0092-4418-9896-ceb4d7d4809a)

**Comment by yawkat** [comment]
Ok I've thought about this a bit more. The basic problem we have here is that we have no way of signalling errors to the client after the response headers are written, which happens along with the first piece of the body. So if there is an error in the publisher after the first item, we can do very little. This is also why there is a log warning on the server, users should avoid hitting this case.

The inconsistency of the test case comes because with the new server optimizations, flushes can be delayed, so the channel is closed before even the response headers are written. It's now possible for the channel to close even before the response headers are flushed. Thanks for showing how to consistently reproduce this with the added flush call, the unreliability was why I didn't investigate this before.

However, I don't believe server changes are the right way here. Yes, we could flush early, but in the end this code branch should not be hit, it's an application bug when it is. So I've stuck with the current behavior on the server side.

On the client side though, I added a commit to #9483 with two changes: Errors during the http headers are now thrown as the new ResponseClosedException type, and errors during the stream body emit this same error type. This fixes the todo and makes the test pass consistently.

**Comment by yawkat** [comment]
A similar patch would be possible for 4.0.x, but the issue is minor enough that I think waiting for 4.1.x, where all this code has been rewritten, is fine.
