### ISSUE TITLE
403 response from /login endpoint after successful jwt authentication with cookie enabled

### ISSUE THREAD

**Issue by jamiebernardin** [micronaut-projects/micronaut-core#970]
I followed authentication guide exactly, but only set up a user db, not ldap:  
http://guides.micronaut.io/micronaut-database-authentication-provider-groovy/guide/index.html

If I use Bearer enabled, I successfully login with a 200 response which includes bearer, refresh etc in the body.  When I switch to cookie enabled, I get a valid cookie that works great... but the response from the login endpoint is a 403, not 200.  

- **Operating System**: Mac Mohave
- **Micronaut Version:** 1.0.1
- **JDK Version:**  1.8.0_191

Attached is the application.yml:
[application.yml.txt](https://github.com/micronaut-projects/micronaut-core/files/2618141/application.yml.txt)

**Comment by goeh** [comment]
I think you stumbled upon the same issue that I did. Micronaut does not set a path for the JWT cookie, so the path default to /login. The response code from /login is actually a 307 redirect to /. And I guess you have secured /. Because the JWT cookie path is /login the cookie is not sent by the browser.
You can fix this by setting cookie path explicitly in Micronaut.
micronaut.security.token.jwt.cookie.cookie-path: /
IMO / should be set by default
See https://github.com/micronaut-projects/micronaut-core/issues/798

**Comment by goeh** [comment]
Maybe the default JWT cookie path could be set to / in Micronaut 1.1?
I wanted to discuss this in https://github.com/micronaut-projects/micronaut-core/pull/799 but it got lost somehow.

**Comment by goeh** [comment]
Default JWT cookie path was changed to "/" in version 1.1.x 👍
https://github.com/micronaut-projects/micronaut-core/commit/6cb0aafe6ff5cba546606c6e50bdefa428862db1

**Comment by jamiebernardin** [comment]
Thanks for the info.  setting micronaut.security.token.jwt.cookie.cookie-path: /   doesn't seem to change anything in 1.0.1.  also tried micronaut.security.token.jwt.cookie.path: / and still getting 403.  Will see if 1.1 makes a difference.

**Comment by jameskleeh** [comment]
@jamiebernardin Can you provide a sample application that exhibits the behavior with 1.1.0.BUILD-SNAPSHOT?

**Comment by jameskleeh** [comment]
Closing this due to lack of feedback
