### ISSUE TITLE
Validation of controller responses doesn't work

### ISSUE THREAD

**Issue by luckyswede** [micronaut-projects/micronaut-core#977]
Thanks for a great product.
There is no validation of response objects from a `@Validated` controller.
My workaround is to wrap all responses with a call to an internal validation method, eg in the following example a call to `/asyncok` fails as expected but calling `/asyncnotok` returns an empty object:
```
public class Pojo {
    @NotBlank
    private String text;
...
}

@Validated
@Controller("/")
public class TestController {
    @Get("/asyncok")
    @Valid
    public Single<Pojo> asyncok() {
        return Single.just(validate(new Pojo("")));
    }

    @Get("/asyncnotok")
    @Valid
    public Single<Pojo> asyncnotok() {
        return Single.just(new Pojo(""));
    }

    public <T> T validate(@Valid T t) {
        return t;
    }
}
```
The same goes for sync methods.
- **Micronaut Version:** 1.0.1
- **JDK Version:** 8

### Example Application
https://github.com/luckyswede/validationtest

**Comment by luckyswede** [comment]
You may think it's low prio, but it's definitely a bug, not an enhancement.

**Comment by meyerinj** [comment]
So I've been tinkering around with this and it looks like the appearance of a bug comes from the validation interceptor being unable to validate objects wrapped in a reactivex object. So the syncnotok method fails as expected because the validation interceptor validates the return object and rejects it whereas asyncnotok attempts to validate io.reactivex.Single, which has no validation criteria and thus can't really fail.

Is this the intended behavior? I could throw in some logic that would attempt to find the wrapped POJO in the reactivex objects so that it can be validated.

**Comment by jameskleeh** [comment]
This was implemented via https://github.com/micronaut-projects/micronaut-core/issues/2180
